### ISSUE TITLE
[WebToolsE2E][Aspire] In Aspire 9.1 dashboard, the symbol for ascending shows by default in Type column.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6686] opened 2024-11-15 05:55 UTC
**NOTE**
1. This is a regression and it doesn't repro with 9.0.0

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2
2. Install VS 17.13 P2
3. Install Aspire 9.1 P1

**REPRO STEPS**
1. New Project > Aspire Starter App  > .NET 9.0 (Standard Term Support) > Create
2. Build and F5

**ACTUAL**
The symbol for ascending shows by default in Type column.
![Image](https://github.com/user-attachments/assets/1ae758ee-d140-4a3d-b1b5-1e6e9cc8cee9)

**EXPECTED**
There should be no arrow symbol shown when sort is not selected.

**Comment by JamesNK** [comment] 2024-11-19 05:51
Dispite not being clicked on, this is the default sort order. Is showing the arrow really a bug?

**Comment by joperezr** [comment] 2024-11-20 00:40
Great find @vmykagapuz thanks for the report. In this case, as @JamesNK said it was by design, so closing this as such.

**Closed by joperezr** 2024-11-20 00:40 UTC
Labels: untriaged

**Comment by v-elenafeng** [comment] 2024-11-20 00:52
@JamesNK @joperezr This (showing the arrow) is a regression from 9.0.0 and ascending is the default order for Name / State / Start time /Type, so why do we need an arrow next to Type. This is a minor issue but not sure if it's intentional.

**Comment by JamesNK** [comment] 2024-11-20 01:26
The default sort order has always been type first. That hasn't changed. The only thing has changed is an arrow is added to the UI to show the default sort order.
