### ISSUE TITLE
When launching an Aspire project without Docker installed we still run

### ISSUE THREAD

**Issue by glennc** [dotnet/aspire#3112] opened 2024-03-22 20:04 UTC
Watched a person install and use Aspire for the first time today. They forgot to install Docker and the experience was that they got the prompt in VS to go install it, but that was immediately covered by the launched console window with an error about not being able to find the docker exe. Which they didn't really understand, can we/should we not launch the app if we pop one of the docker dialogs until that dialog is resolved?

**Comment by iantasker** [comment] 2024-03-22 23:09
Similar issue to #2922

**Comment by maddymontaquila** [comment] 2024-10-24 21:00
Fixed with new experience in 9 - dupe of #5533 and fixed in #6135

**Closed by maddymontaquila** 2024-10-24 21:00 UTC
Labels: area-tooling, untriaged
