### ISSUE TITLE
Resource types All checkbox not working correctly

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1256] opened 2023-12-06 23:47 UTC
The `All` checkbox only goes into an intermediate state if you first uncheck everything.

![all-checkbox](https://github.com/dotnet/aspire/assets/303201/b734d413-4a04-4ff7-a561-21aa7f361025)

**Comment by JamesNK** [comment] 2023-12-07 01:09
It seems to be random. Checking and unchecking the same item sometimes works, but most of the time it doesn't.

@drewnoakes Could this have started with your change here?

**Comment by drewnoakes** [comment] 2023-12-07 01:20
Yes this was identified prior to merging, as per https://github.com/dotnet/aspire/pull/1221#issuecomment-1843805855.

Current theory is that it's an issue in FluentUI's control, and @tlmii has a thread going on it apparently.

**Comment by JamesNK** [comment] 2023-12-07 01:25
Does this need to be fixed in Fluent Blazor?

**Comment by JamesNK** [comment] 2024-01-11 23:07
Was this fixed in FluentUI?

**Comment by tlmii** [comment] 2024-01-11 23:12
It was fixed in 4.2 and we updated to that a few weeks ago. I just confirmed it seems to be working fine in what I've got installed now. I'll close this issue.

**Closed by tlmii** 2024-01-11 23:12 UTC
Labels: area-dashboard
