### ISSUE TITLE
Feature - Add Existing Running Process In AppHost or Allow to keep running some project

### ISSUE THREAD

**Issue by jp1482** [dotnet/aspire#1623] opened 2024-01-10 08:04 UTC
As of now, AppHost become the entry point for solution. This is good if we have to just check running project and no. of project that start are lower. There are few such cases. 

- In one scenario, if project has many components like Web Apps, Web API and mostly developer at a time working on one or two of such component. Now if they are developing something and checking in overall flow, each time running all the project and when app host stop working as to accommodate new  change in one project , it will become time consuming.  Someone might suggest that use Container but that is not always choice and also container also stop and start required some time. 

- I know this is kind of feature and may or may not possible but in case consider for future.

**Comment by DamianEdwards** [comment] 2024-01-11 02:12
I think this might be a dupe of #303?

**Comment by mitchdenny** [comment] 2024-01-11 03:55
I think what @jp1482 is asking for is allowing apps/containers to keep running instead of always restarting them. I don't think that this is realistically an option for GA. I think the furthest we'll get to be enabling more data persistence scenarios around volumes for containers, so you don't always need to initialize your test data for inner loop.

**Comment by jp1482** [comment] 2024-01-19 10:53
I think thing that I mention will support this because if we just talk about dotnet core app then if it configured then it will sent data when AppHost is up. Also in some case I just needs to know that specific process is running.  @mitchdenny clearly put what I thought about this.

**Comment by mitchdenny** [comment] 2024-01-19 21:35
We've now got some capabilities for persistent containers added to our underlying orchestrator but we won't have the bandwidth to tackle this in the short term.

The some of the wrinkles are things like if you have two container they depend on one another do we throw if you mark one as persistent and not the other.

There will be other things like when we have to restart a container because inputs have changed.

**Comment by SteveSandersonMS** [comment] 2024-06-24 11:01
Can we update this issue title so it covers keeping containers running across AppHost restarts (since @mitchdenny mentions this above), or should that be tracked as a separate issue?

**Comment by mitchdenny** [comment] 2024-06-24 11:57
@SteveSandersonMS closing this in favor of https://github.com/dotnet/aspire/issues/923

**Closed by mitchdenny** 2024-06-24 11:57 UTC
Labels: area-app-model
