### ISSUE TITLE
When a service is finished, the dashboard shows a red warning icon even if the return code is 0

### ISSUE THREAD

**Issue by sandord** [dotnet/aspire#4432] opened 2024-06-09 14:25 UTC
I assume that the icon is only reflecting the health state -- which is fundamentally different from the return code -- but the way it works at the moment can be confusing if you have services that stop by design.

For example, I have a service that seeds sample data and stops when finished.

**Comment by davidfowl** [comment] 2024-06-09 19:37
Dupe of https://github.com/dotnet/aspire/issues/4127

**Closed by davidfowl** 2024-06-09 19:37 UTC
Labels: area-dashboard
