### ISSUE TITLE
The time format on the dashboard does not use local culture

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspire#2530] opened 2024-02-29 01:17 UTC
My local cultural time format is `H:mm:ss`, but the dashboard is now using `tth:mm:ss`

![image](https://github.com/dotnet/aspire/assets/5714438/4f54d717-f3ee-4757-a324-a62fb8f7fed3)

**Comment by kvenkatrajan** [comment] 2024-03-01 19:29
Similar to #2567  - this is more to do with the time format localization rather than the labels themselves.

**Comment by joperezr** [comment] 2024-03-01 21:31
Temporarily assigning to @kvenkatrajan so she can assign to the right person.

**Comment by adamint** [comment] 2024-03-12 20:50
@Varorbc which culture is this? I'm assuming the problem is that TT is not necessary?

**Comment by adamint** [comment] 2024-03-13 16:32
Duplicate of #2632

**Comment by adamint** [comment] 2024-03-14 03:11
@JamesNK your PR did not seem to fix this issue

**Comment by JamesNK** [comment] 2024-03-14 04:00
I didn't expect it to. My change was about getting the browser time zone. This is a culture problem. They're separate concerns.

**Comment by adamint** [comment] 2024-03-14 14:38
Ah, i misunderstood.

**Comment by adamint** [comment] 2024-03-14 18:23
@Varorbc I looked into this more. .NET's `zh-Hans` DateTime locale has its long time format as `下午H:MM:SS`.
Are you able to give me any other examples of a time format for a Microsoft product that does not follow this pattern? Otherwise, you may need to submit a ticket in https://github.com/dotnet/sdk

**Comment by JamesNK** [comment] 2024-03-14 23:37
I tested this locally and I found that local changes were still detected.

@Varorbc If I make some changes on a branch, could you get the source code and test it out on your local computer?

**Comment by JamesNK** [comment] 2024-03-14 23:43
I haven't done it yet. I'll have something you can try out in 30-60 mins.

**Comment by JamesNK** [comment] 2024-03-15 00:03
Try out https://github.com/dotnet/aspire/pull/2909.

I don't think this will fix your issue. The date you showed in one of the pictures was on the resources page. That date doesn't get its formating from the code I'm changing.

**Comment by sebastienros** [comment] 2024-04-03 21:23
AFAIR zh-CN is the common culture sent by common web browsers in China: QQ and Chrome. However, dotnet doesn't have this one **anymore** (at least from 7.0) as it is not a standard one. The standard equivalent one is zh-Hans. So without adding it explicitly in the supported cultures it won't be recognized and used. Is different app we decided to add it explicitly because it's still commonly used.

**Comment by kvenkatrajan** [comment] 2024-04-08 16:33
@Varorbc  thanks for confirming the fix works
@sebastienros , its good to know its commonly used.

We will be working on a fix for preview 6. Thanks for your patience!

**Comment by danmoseley** [comment] 2024-04-22 19:22
@kvenkatrajan guessing this is 8.1 now

**Comment by adamint** [comment] 2024-06-18 19:52
@Varorbc could you share what you mean by 
> fixed the culture cache

We can easily add zh-CN to the allowed culture list.

**Comment by JamesNK** [comment] 2024-06-18 23:42
I don't know much about cultures and translating. I assume the list we have today was chosen for a reason.

We could add zh-CN to the list for this one particular case, but then what about all the other more specific cultures? There are a huge number of those. We don't want to add them all.

**Comment by sebastienros** [comment] 2024-06-18 23:45
@JamesNK 

> but then what about all the other more specific cultures

This one is very special. It's not listed by .NET anymore though it's the one that all Chinese browsers request.

**Comment by JamesNK** [comment] 2024-06-19 00:27
Ok. My only ask is we have a comment to explain why the list of cultures is chosen. A comment can go against `zh-CN` that it is what all Chinese browsers request, and explicitly specifying it allows OS culture customization to flow through into the dashboard.

**Comment by joperezr** [comment] 2024-06-19 17:07
I'm not 100% sure (as it wasn't me who set it up) but I believe the initial list of cultures was driven off from the ones that our compliance requirements list, which are the ones that arcade repo defaults to (we use arcade to produce xlf files)

**Comment by adamint** [comment] 2024-06-19 17:27
> I'm not 100% sure (as it wasn't me who set it up) but I believe the initial list of cultures was driven off from the ones that our compliance requirements list, which are the ones that arcade repo defaults to (we use arcade to produce xlf files)

You are correct - it was just copied from the list of cultures we have localized. This should be the only exception that we need to make, as zh-CN is the only non-standard proliferous culture

**Closed** 2024-06-26 14:41 UTC
Labels: bug, area-dashboard, user-experience
