### ISSUE TITLE
Protected storage configuration is lost between dashboard runs from a container

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#4949] opened 2024-07-17 23:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The dashboard uses protected storage to save orientation/size of details views. This data is protected using data protection. Data protection keys are recreated each time the dashboard is run from the container in typical usage.

The end result is orientation/size of details views is lost between runs of the standalone dashboard. Theme selection doesn't have this problem because it is saved to a cookie.

Possible solutions

This data isn't sensitive and doesn't need to be encrypted. We can use a solution that doesn't do any encryption to fix this issue.

* Switch to using a cookie.
* Continue to use localStorage but don't protect saved data. I think it's important we **don't** completely replace `ProtectedLocalStorage` in DI with an instance that doesn't encrypt. It might be used internally by Blazor or other libraries to protect data that is actually sensitive. Perhaps have a keyed registration of `ProtectedLocalStorage` that isn't protected by specifying `IDataProtectionProvider` option that doesn't do anything.

### Expected Behavior

Orientation/size of details views is remembered.

**Comment by samsp-msft** [comment] 2024-07-22 17:28
@amcasey - do you have any suggestions?

**Comment by amcasey** [comment] 2024-07-22 17:49
I'm not sure I understand the scenario.  There _is_ persistent storage for app data but there _isn't_ persistent storage for data protection keys?  Under those circumstances, I agree that any app data encrypted by data protection will be inaccessible in subsequent runs.

I'm guessing the issue is that there's no way to protect the data protection keys without setting up AKV or something, which we don't want to do?

**Comment by JamesNK** [comment] 2024-07-23 01:26
People casually run the dashboard from the docker command line. We don't want to make them have to think about setting up persistent storage of data protection keys.

**Comment by amcasey** [comment] 2024-07-23 14:08
There may be a solution where you protect the keys with a certificate.  Otherwise, I would tend to agree that this scenario isn't particularly Data Protection friendly.  I don't have enough context to comment on the security implications of leaving the data unprotected.

**Closed** 2024-08-26 23:54 UTC
Labels: area-dashboard
