### ISSUE TITLE
#dotnet Aspire with IP from local network

### ISSUE THREAD

**Issue by Mafyou** [dotnet/aspire#5792] opened 2024-09-19 22:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Is it possible to change "localhost" in #Aspire?

I have an API in local IP starting by 192.168 and I would like to "map" it to Aspire to be requested from other apps in my local network.

Can someone help me ?

Regards, Mafyou.

PS : I tried put IP in the profile of launchSettings.json but it replace the IP by localhost.

### Expected Behavior

Working with custom local IP to be hosting multiple app and able to see logs

### Steps To Reproduce

In launchSettings.json put:
"applicationUrl": "http://192.168.1.102:6969" for example
See it, will be replaced by localhost

### .NET Version info

8.0

**Comment by davidfowl** [comment] 2024-09-22 05:17
Dupe of https://github.com/dotnet/aspire/issues/2887

**Closed** 2024-09-22 23:08 UTC
Labels: area-app-model, enhancement

**Comment by Mafyou** [comment] 2024-09-22 23:10
Why isn't it planned?
Why did you hardcoded this feature?
Aspire will only be a local thing? What's the point?

**Comment by davidfowl** [comment] 2024-09-22 23:16
> Why isn't it planned?

It's a duplicate of #2887

> Aspire will only be a local thing? What's the point?

Yes, the orchestrator is for local development only. You can learn more about aspire on the docs https://learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview
