### ISSUE TITLE
Delete methods marked obsolete during previews

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2628] opened 2024-03-04 21:19 UTC
As we changed APIs during the previews we made a bunch of members obsolete. We should delete these members before the final release for GA (maybe in the final GA release?).

**Comment by davidfowl** [comment] 2024-03-04 21:30
closing as dupe of https://github.com/dotnet/aspire/issues/2417

**Closed by davidfowl** 2024-03-04 21:30 UTC
Labels: area-meta
