### ISSUE TITLE
Aspire.StackExchange.Redis.OutputCaching only works with .NET 9.0

### ISSUE THREAD

**Issue by jcjiang** [dotnet/aspire#3376] opened 2024-04-03 23:47 UTC
I am working through this tutorial: https://learn.microsoft.com/en-us/dotnet/aspire/caching/caching-components and am getting an error when I run: 

`dotnet add package Aspire.StackExchange.Redis.OutputCaching --prerelease`

![image](https://github.com/dotnet/aspire/assets/23298667/b30a8c7a-5662-4b96-9413-b765f451f585)

The version downloaded is only compatible with .NET 9 so doesn't work with my Aspire project which is .NET 8.

**Comment by eerhardt** [comment] 2024-04-04 03:38
@jcjiang - you need to use the `8.0.0-*` version of the package. The 9.0 version is for when you are targeting net9.0.

@joperezr - a good reason why we shouldn't be producing 9.0 packages until after we GA 8.0. But we will only be in this situation for a little while longer.

Closing as this is by design.

**Closed by eerhardt** 2024-04-04 03:38 UTC
Labels: needs-area-label

**Comment by joperezr** [comment] 2024-04-04 16:48
>  a good reason why we shouldn't be producing 9.0 packages until after we GA 8.0. 

I was thinking more that instead of not producing packages, we should be making sure that all packages we produce target both 8.0 and 9.0. We have a workitem scheduled for 9.0 preview 4 to get Aspire 9.0 support 8.0 Aspire apps, which of course involves work in the workload but I also see this to be part of it.

**Comment by eerhardt** [comment] 2024-04-04 17:36
> we should be making sure that all packages we produce target both 8.0 and 9.0. 

This isn't the plan for Aspire - both components and Hosting packages. The plan is Aspire is "part of .NET". You use the 8.* packages when on net8.0. You use the 9.* packages when on net9.0. It makes it simple to understand. 

cc @DamianEdwards

**Comment by DamianEdwards** [comment] 2024-04-04 18:27
This might change actually. Targeting both net8 and net9 (or net9 when required at least) might be what we end up doing in order to support .NET 8 LTS customers.
