### ISSUE TITLE
[WebToolsE2E][Aspire] Running AspireAppx.Web as a Startup project, weather data loading fails with System.Net.Http.HttpRequestException: No such host is known. (apiservice:443).

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/aspire#3478] opened 2024-04-08 05:57 UTC
**Azure DevOps work item**
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2014711

**REGRESSION INFO** 

Reproduces with Aspire 8.0 Preview 4

**INSTALL STEPS**

Clean machine: Win11 x64 23h2 ENU

1. Install VS 17.10 Preview 3 FB

   - Web Workload
   - Includes Aspire 8.0.0-preview.5.24201.12
   - Includes SDK 8.0.300-preview.24203.14 and runtime 8.0.2

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > .NET 8.0

1. From the Startup items drop-down list, select AspireAppx.Web
    
   ![image](https://github.com/dotnet/aspire/assets/78580199/bb5c0a41-38cb-42a7-9b48-50f6c661cb5c)

1. Run the app and go to Weather page in the browser

**ACTUAL**
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Net.Http.HttpRequestException: No such host is known. (apiservice:443)
       ---> System.Net.Sockets.SocketException (11001): No such host is known.
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
![image](https://github.com/dotnet/aspire/assets/78580199/40d8ee8e-9011-4003-a02a-da8d061ff806)

Note: 
- Doesn't repro when running AspireAppx.AppHost and go to Blazor Web App > Weather in the Dashboard.
- Doesn't repro when running Blazor Web App with "Blazor Web App + Aspire support". 

**EXPECTED**
The data can be loaded successfully without any errors when running the AspireAppx.Web project.
![image](https://github.com/dotnet/aspire/assets/78580199/c697f5ff-164d-44bd-a49e-6f0734448bcc)

**Comment by davidfowl** [comment] 2024-04-08 07:33
When this happens it means that service discovery isn’t wired up or working. Can you share the frontend project?

**Comment by balachir** [comment] 2024-04-08 13:43
@davidfowl I believe this is just the default Aspire Starter App template. Instead of running the AppHost project, they right-clicked the frontend Web project and tried running it directly as a stand-alone web app.

**Comment by davidfowl** [comment] 2024-04-08 13:52
Ah so the configuration isn’t being provided. I think this is by design.

@ReubenBond is the error you’d expect too? Seems like this isn’t a regression.

**Comment by ReubenBond** [comment] 2024-04-08 15:05
This looks expected - there is no configuration, so it is trying the provided address directly (pass-thru).

**Comment by timheuer** [comment] 2024-04-08 16:15
Agreed by design. The Aspire templates explicitly rely on apphost orchestration and aren't intended to run independently without more work (e.g., the web project is using an HttpClient that is using a baseaddress that isn't resolved without apphost -- or other means)

**Comment by Shak-o** [comment] 2024-04-13 10:47
Hey, I'm facing a similar issue but I'm running the application via AppHost. I added my API and client application in the AppHost project:

```csharp
var userManagerApi = builder.AddProject<Projects.UserManager_Api>("usermanagerapi")
    .WithReference(userManagerDb)
    .WithReference(messaging)
    .WithEnvironment("SigningKeySecret", signingKey);

var userManagerAdmin = builder.AddProject<Projects.UserManager_Admin>("userManagerAdmin")
    .WithReference(userManagerApi)
    .WithEnvironment("SigningKeySecret", signingKey);
```

Then, I configured `HttpClient` in my client application:

```csharp
builder.Services.AddHttpClient<UserManagerApiClient>(client =>
{
    client.BaseAddress = new System.Uri("https://usermanagerapi");
});
```

When I call anything from `UserManagerApiClient`, I get an error:

```
System.Net.Http.HttpRequestException: No such host is known. (usermanagerapi:443)
```

**Comment by balachir** [comment] 2024-04-22 14:14
Closing this issue as it's By Design.

**Closed by balachir** 2024-04-22 14:14 UTC
Labels: area-tooling
