### ISSUE TITLE
[WebToolsE2E][Aspire] After manually select a theme in the Aspire dashboard, closing and reopening the settings option, It display jumping from the "System" theme to the selected theme instead of navigating directly to the selected theme

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire#5307] opened 2024-08-15 08:39 UTC
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.400
3. Install Aspire 8.1.0
4. Install latest released azd v1.9.6
5. Install git v2.46.0

**REPRO STEPS**
1. Open CMD, run following command to create an Aspire Starter App project and deploy it
```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
azd init
azd up
```
2. After successful deployment, open the deployed "Aspire Dashboard" URL
![Screenshot 2024-08-15 153624](https://github.com/user-attachments/assets/87047661-248f-4dee-967b-f47d4db9938f)
3. Click the "Launch settings" option, select "Light" or "Dark" theme first, then close and reopen "Launch settings" option

**Note:**
1. This issue also repro on in the Aspire dashboard after dotnet run, but it is unstable

**ACTUAL**
It display select the "System" theme first, then jump to the "Light" or "Dark" theme
![Setting](https://github.com/user-attachments/assets/e2a84b82-ba48-4321-bba9-809a0738ed27)

**EXPECTED**
It should navigating directly to the "Light" or "Dark" theme.

**Comment by JamesNK** [comment] 2024-10-14 00:44
I believe this is a duplicate of https://github.com/dotnet/aspire/issues/6020

Was fixed recently.

**Closed by JamesNK** 2024-10-14 00:44 UTC
Labels: bug, area-dashboard, azure
