### ISSUE TITLE
[WebToolsE2E][Aspire] Do not start Docker Desktop first after installed, create an Aspire Starter App with Redis checked using CMD, F5/Ctrl F5 failed with 'Container runtime 'docker' was found but appears to be unhealthy.'

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2307] opened 2024-02-19 09:50 UTC
**REGRESSION INFO**: Also repro on Aspire.ProjectTemplates.8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.300-preview.24101.10
3. Install Aspire.ProjectTemplates.8.0.0-preview.4.24118.4
4. Apply NuGet Feeds
5. Install Docker Desktop

**REPRO STEPS**

1. Do not start docker first.
2. Open CMD, running following commands:
```
dotnet new aspire-starter -o aspire1 --use-redis-cache
cd aspire1
dotnet build
cd aspire1.AppHost
dotnet run
```

**Notes**:

1. If start docker first, then create app and run, it can run successfully.

**ACTUAL**
It shows 'Container runtime 'docker' was found but appears to be unhealthy.'
![image](https://github.com/dotnet/aspire/assets/82028229/d5754918-255a-4b3f-8473-88668e61dde3)

**EXPECTED**
Running successfully.
![image](https://github.com/dotnet/aspire/assets/82028229/6ce09f12-2278-44b8-80e3-2d327f617b8f)

**Comment by davidfowl** [comment] 2024-02-21 06:51
cc @danegsta

**Comment by davidfowl** [comment] 2024-02-26 15:02
@danegsta Giving this to you as we made changes here wrt how we support podman and docker in the app host.

**Comment by dbreshears** [comment] 2024-02-26 19:07
@davidfowl , I think this is won't fix.  We don't attempt to start Docker Desktop or Podman automically but just require it to be running.

**Comment by davidfowl** [comment] 2024-02-26 19:27
There used to be logic that made VS start it right? Based on some exit code returned from the AppHost that enabled VS to start it on the next run right? Where is that logic now?

**Comment by dbreshears** [comment] 2024-02-26 20:02
Per repro steps this is command line.  I don't see any indication that VS is involved outside of maybe the title?   @v-cazhang can you clarify if VS is involved?

**Comment by dbreshears** [comment] 2024-02-26 22:05
I took a look at this from cmd line and VS.   In both P3/P4 we started Docker Desktop on F5/Ctrl-F5.  From "dotnet run" the error message is slightly different but seems but appears sufficient to determine the issue.   There are no plans for the orchestrator to start Docker Desktop.

From "dotnet run"

Preview 3 :

Docker was found but appears to be unhealthy. Exit code for 'docker ps --latest --quiet' was 1

Preview 4:

Container runtime 'docker' was found but appears to be unhealthy. The error from the container runtime check was error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/system/df": open //./pipe/docker_engine: The system cannot find the file specified..

**Comment by davidfowl** [comment] 2024-02-26 22:08
@dbreshears if you run it again on preview 3, does it work?

**Comment by dbreshears** [comment] 2024-02-26 22:21
@davidfowl ,  no I keep getting the same error each time.  I have to to start Docker Desktop manually.

**Comment by davidfowl** [comment] 2024-02-26 22:23
Excellent, then there's no regression. Just a different error message. We can close this as by design.

**Closed** 2024-02-26 22:23 UTC
Labels: area-tooling, area-orchestrator
