### ISSUE TITLE
Is it possible to run Aspire dashboard within one process along with the app

### ISSUE THREAD

**Issue by krzysiek-b** [dotnet/aspire#4493] opened 2024-06-13 07:41 UTC
Curently when I enable orchiestration AppHost project is created. VS runs two processes. One ow them is aspire host another is the app itself. 

How do you see the possibility to run both in one process? Forget for a moment about having monitoring and app in one process as it looks like a bad idea :)

**Comment by davidfowl** [comment] 2024-06-13 07:44
Dupe of https://github.com/dotnet/aspire/issues/846.

**Closed** 2024-06-13 07:45 UTC
Labels: area-app-model
