### ISSUE TITLE
Unable to detect what resources used `WaitFor`

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#5558] opened 2024-09-05 18:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The `WaitOn` implementation in main doesn't seem to leave behind any observable marker of it's use on the resource.

It would be helpful if there was a way to interrogate which resources make use of `WaitFor`.  For example in a `BeforeStartEvent`, find all resources with `.WaitFor(db)` and add an additional `.WaitFor(migrator)`

### Describe the solution you'd like

I'd like some way to find out from an `IResource` that had `WaitFor` configured - likely through some kind of annotation.

**Comment by davidfowl** [comment] 2024-09-05 19:41
cc @mitchdenny

**Comment by mitchdenny** [comment] 2024-09-06 05:01
With the implementation of `WaitFor` in main we avoided introducing another annotation and instead just made use of the event subscriptions. The downside of this is that we don't have a lot of introspection ability which could be useful.

An example of where it could be useful is where we might want to redirect health check error details in logs to dependent resources to make the cause of a resource in a `Waiting` state more useful.

I'm contemplating introducing a `WaitForAnnotation` or a `DependencyAnnotation` and storing a reference to the subscription on it. Alternatively, @JamesNK was introducing a relationship annotation in #5311 (but has other priorities right now).

I think this is a good suggestion no matter which way we tackle it.

**Comment by mitchdenny** [comment] 2024-09-06 07:16
I'll work on this after #5515 merges in.

**Comment by mitchdenny** [comment] 2024-09-23 03:28
https://github.com/dotnet/aspire/pull/5842 should address this issue. As part of the PR we add some additional logging to make it clear when a dependent resource has finished waiting. Additionally the eventing hookup has been changed so that the waits occur concurrently so you'll see log entries for all dependency resources.

**Comment by mitchdenny** [comment] 2024-09-24 01:09
Fixed in #5842 but wasn't closed automatically. /cc @afscrome

**Closed** 2024-09-24 01:51 UTC
Labels: area-app-model, enhancement
