### ISSUE TITLE
`AddContainer` annotation limitations (-w & args)

### ISSUE THREAD

**Issue by gerneio** [dotnet/aspire#936] opened 2023-11-17 16:11 UTC
`ContainerResource` has pretty limited options for configuring a container. So far we can do port bindings, volume mounting, & environment variables, but we can't specify container arguments, working directory, and tons of other container specific configuration.

For example, I would want the equivalent of [this example](https://github.com/nodejs/docker-node/blob/main/README.md#run-a-single-nodejs-script) docker-node command:

`docker run -it --rm --name my-running-script -v "$PWD":/usr/src/app -w /usr/src/app node:8 node your-daemon-or-script.js`

Notice the `-w` switch and passing of the `node your-daemon-or-script.js` args to the container.

Right now, it doesn't look like we have the ability to do either of those with Aspire, w/o first having created our own docker image and uploading it to our local container registry. There's probably too many container/docker specific configuration items that Aspire would have to mimic, so in addition to adding new basic annotations (like what I mentioned above), I wonder if having Aspire just point to a docker file (or compose file?) would be more practical.

**Comment by davidfowl** [comment] 2023-11-17 16:19
Dupe of https://github.com/dotnet/aspire/issues/177

> I wonder if having Aspire just point to a docker file (or compose file?) would be more practical.

Possibly related to https://github.com/dotnet/aspire/issues/769 as well.

I'm not sure why we'd want native support for docker compose files. What would that accomplish that you can't already do today? What would aspire be adding in that scenario?

**Comment by davidfowl** [comment] 2023-11-17 16:20
BTW these seem like fairly simple features to add... 😄 . We do accept pull requests!

**Comment by gerneio** [comment] 2023-11-17 16:45
I agree, the args one seems pretty simple to add. And hopefully the working directory too, but I don't think that's been discussed yet.

As for compose, just throwing stuff out there, so I'm not opposed to having it or not having it. I'm mostly just pointing out that I can't even really use Aspire for simple container configurations from vendor base images (as you already eluded to in that other issue). For example, I was trying to re-work yalls sample with nodejs as front-end and set it up so that was running from a container instead, and was unable to do it successfully.

I would NOT expect Aspire to have every possible container option available in a native way, there's just too many configuration options. But ultimately as soon as I come across something that's not configurable from within Aspire, then it kind of loses its value 🙃. So having some sort of extensible way of "making it happen" (w/o forking) would be appreciated. Could be I'm just missing the point of this tool altogether, but I see great potential, once its polished.

Thanks for replying so quickly! And looking forward to see this tool develop further.

**Comment by davidfowl** [comment] 2023-11-17 16:49
You mean we don't support all of the features of compose in the first preview release? (tongue in cheek). It's not ready for those scenarios as yet, but there's nothing outside of time that is preventing it from working. I's early, but I love the enthusiasm. 

I think we should add more of those features before prematurely building any extensiblilty model. We already have the executable backdoor you can use if you want full control, run the docker command yourself 😄

**Comment by gerneio** [comment] 2023-11-17 16:51
That's fair, thanks for pointing that out.

**Comment by Depechie** [comment] 2023-11-20 19:05
Was also trying out to convert some docker compose samples... like this one:
```
  tempo:
    image: grafana/tempo:2.3.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ${PWD}/tempo.yml:/etc/tempo.yaml
      - tempo:/tmp/tempo
    restart: unless-stopped
    ports:
      - 3200:3200  # tempo
      - 4007:4317  # otlp grpc
    depends_on:
      - otel-collector      
    networks:
      otel:
```
I think we are also missing the command option for the moment right?
And setting the general volume binding, is that automaticall? ( the ` -tempo:/tmp/tempo` part )

**Comment by davidfowl** [comment] 2023-11-24 16:49
Closing this as dupe of https://github.com/dotnet/aspire/issues/177, which will happen for preview 2

**Closed by davidfowl** 2023-11-24 16:49 UTC
Labels: area-app-model

**Comment by davidfowl** [comment] 2023-12-01 03:48
This was completed in https://github.com/dotnet/aspire/pull/1121
