### ISSUE TITLE
[AzureTools][Aspire] It would be better to make the error message clearer if Aspire does not support Docker Desktop Windows container

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#4717] opened 2024-06-28 11:12 UTC
**Regression:** Not a regression, this issue also **reproduces** on VS 17.10.3 with Aspire 8.0.0

**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.10.3
**Aspire Version**: 8.0.2
Apply NuGet Feeds
**Docker Desktop:** 4.32.0

**REPRO STEPS:**

1. Make sure the Docker Desktop is Windows container.
2. Create a new .NET Aspire Starter Application with redis checked -> Run `dotnet run` in the AppHost.project folder.
3. Check whether the error message is clear.

**Actual:**
The error message is not clear.
![image](https://github.com/dotnet/aspire/assets/62053665/42fefd08-cc2d-4bf1-914d-906516495d13)

**Suggestion:**
1. It would be better to make the error message clearer if Aspire does not support Docker Desktop Windows container.
2. It would be even better if a similar switching pop-up window could pop up to directly switch Docker Desktop to a matching container OS when clicking F5 button in VS.
   ![image](https://github.com/dotnet/aspire/assets/62053665/644f7c93-25a7-4ef6-ae9b-7ecfaa7a673d)

**Comment by davidfowl** [comment] 2024-09-15 18:22
Closing as dupe of https://github.com/dotnet/aspire/issues/5533

**Closed by davidfowl** 2024-09-15 18:22 UTC
Labels: area-app-model
