### ISSUE TITLE
"Unknown" container state in aspire dashboard

### ISSUE THREAD

**Issue by hades200082** [dotnet/aspire#5109] opened 2024-07-29 16:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm having a problem with Aspire where it seems to randomly be unable to detect the state of containers. They show up as "Unknown" in the aspire dashboard. This causes the .WaitFor() to never see them as running preventing my stack from booting up.

It's not the same containers each time and sometimes it all spins up fine. Any ideas what might be going on?

![image](https://github.com/user-attachments/assets/55440441-c6a5-46b4-96f4-37c4defc7dc1)

When I check in Docker Desktop I can see the containers running just fine.

### Exceptions (if any)

none seen

### .NET Version info

.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.d7126b9e
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.132 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  6.0.424 [C:\Program Files\dotnet\sdk]
  7.0.120 [C:\Program Files\dotnet\sdk]
  8.0.107 [C:\Program Files\dotnet\sdk]
  8.0.200 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by karolz-ms** [comment] 2024-07-29 17:14
@hades200082 thank you for reporting the issue, much appreciated. A few clarifying questions

1. Just to make sure all the binaries are as expected: when you run your application, could you verify `dcp.exe` comes from `C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.1.0\tools\` (note version 8.1.0) and when you run 

    `& 'C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.1.0\tools\dcp.exe' version`

    it reports version 0.5.7?

2. What version of Docker Desktop are you using?

3. How often do you encounter this? Every 10 runs, every 100 runs... ? Any errors/warnings in Aspire app host output?

**Comment by Alirexaa** [comment] 2024-07-29 21:10
@karolz-ms, I see random `Unknown` state when running `PostgresEndToEnd.AppHost` in the playground.

**Comment by hades200082** [comment] 2024-07-30 07:31
@karolz-ms 

**#1**

```
C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.1.0\tools>dcp version
{"version":"0.5.7","commitHash":"1ac6336f6fd9d61844304b3046a9391a980fad95","buildTimestamp":"2024-07-09T16:07:33Z"}
```

**#2** 

I updated Docker Desktop when I started having this issue as there was an update pending. After the update it seemed to behave worse than before, then stabilised for a while. I finished for the day shortly after that but will let you know how it goes today.

My current version of Docker Desktop is 4.33.0

![image](https://github.com/user-attachments/assets/4f61bfa2-4d3d-48d0-bd68-e3947a429212)

**#3**

It was almost every run for a while - each time different services/containers would show the "unknown" status. It felt random. 

When it happens I stop the whole solution, wait for the containers to all vanish from Docker Desktop, then start the AppHost again. 

I can restart in this manner 3-4 times before I get a run that shows everything as "Running". In some cases, I settle for having 1-2 "Unknown" as long as they are not services that my projects are using `.WaitFor()` with (i.e. things like RedisCommander or PGAdmin if I don't explicitly need them on that run.

Sometimes it can go multiple runs without happening.

**Comment by karolz-ms** [comment] 2024-07-30 22:44
Thanks to both of you. Looks like we all have all correct, freshest bits.

I tried to use `PostgresEndToEnd` playground project to reproduce the issue. Did several runs in rapid succession, with- and without debugging (F5 and Ctrl-F5 in Visual Studio). No joy. 😞 

@hades200082 or @Alirexaa could you add the following to the launch profile for the application that you can reproduce the problem with (these would go into  `environmentVariables` object that is part of the launch profile):

```json
        "DCP_DIAGNOSTICS_LOG_LEVEL": "debug",
        "DCP_DIAGNOSTICS_LOG_FOLDER": "C:\\Users\\karolz\\code\\scratch\\dcplogs\\issue5109"
```
(replacing the folder with your own as necessary). 

Then (after the problem repros) look into the folder, there should be several files in it, but one that we are interested in, and by far the biggest, should be one that starts with `dcpctrl`. Please share the file with me, but be careful, there might be some sensitive info in it. Thank you ❤️

**Comment by hades200082** [comment] 2024-07-31 11:04
@karolz-ms  I added the environment variables as you suggested to the AppHost project:

![image](https://github.com/user-attachments/assets/3058545a-77ac-4b4d-8cb0-0bb8365873ff)

However, it never created the logs folder.

**Comment by karolz-ms** [comment] 2024-07-31 13:32
I am sorry, I should have mentioned this, that folder needs to be created in advance, before the app is run.

**Comment by hades200082** [comment] 2024-07-31 15:21
@karolz-ms Still not getting any logs:

![image](https://github.com/user-attachments/assets/b0e4a72b-a604-417d-af1d-82b8fd31f65e)

**Comment by Alirexaa** [comment] 2024-07-31 15:56
@karolz-ms how can I share this file with you?
I should mention that I run this https://github.com/dotnet/aspire/pull/5098.
Can you run this source?

**Comment by karolz-ms** [comment] 2024-07-31 16:47
@Alirexaa you can send me an email (GH has the address) or via Discord I am `karolzms` there

Will try #5098 later today, thanks. 

@hades200082 strange... this should have worked. You are changing app host launch profile, correct?

**Comment by Alirexaa** [comment] 2024-07-31 16:59
> @Alirexaa you can send me an email (GH has the address) or via Discord I am `karolzms` there

Please check your email.

**Comment by karolz-ms** [comment] 2024-08-01 00:43
@Alirexaa thank you, this is very helpful, I see the problem in the logs. Investigating...

**Comment by hades200082** [comment] 2024-08-01 06:53
@karolz-ms yes, added to the app host. 

I'm using JetBrains Rider if that makes any difference?

**Comment by karolz-ms** [comment] 2024-08-05 17:34
@hades200082 it **should not** but then weird things can happen... ☺️ 

If you set some other environment variable in the launch profile (e.g. `MYTEST`), does the app host and your programs "see" it?

BTW, I have been working offline with @Alirexaa to get the problem narrowed down and fixed.

**Comment by hades200082** [comment] 2024-08-05 20:42
@karolz-ms 

> If you set some other environment variable in the launch profile (e.g. MYTEST), does the app host and your programs "see" it?

Yes. I set a couple of others there.

**Comment by karolz-ms** [comment] 2024-08-07 20:49
The fix has been integrated into Aspire main https://github.com/dotnet/aspire/pull/5217

Many thanks to @hades200082  and especially @Alirexaa for providing additional information that helped narrow down the problem and testing various attempts at fixing the issue.

**Closed by karolz-ms** 2024-08-07 20:49 UTC
Labels: area-orchestrator

**Comment by hades200082** [comment] 2024-08-10 01:43
@karolz-ms When will this release for a `dotnet workload update`?

**Comment by hades200082** [comment] 2024-08-10 18:41
![image](https://github.com/user-attachments/assets/fd179455-549e-4f25-a992-02c74f94b10f)

This dev machine uses Podman Desktop instead of Docker Desktop if that makes a difference

@karolz-ms

**Comment by davidfowl** [comment] 2024-08-10 20:19
What was the issue @karolz-ms ? I saw this Monday in a workshop that @DamianEdwards and I gave

**Comment by karolz-ms** [comment] 2024-08-12 16:25
@hades200082 The fix (that is, DCP component) is part of the Aspire.Orchestration.Hosting NuGet package; since Aspire 8.1 DCP is no longer dependent on the workload. It is already part of the "daily" NuGet feed (https://github.com/dotnet/aspire/blob/main/docs/using-latest-daily.md#add-necessary-nuget-feeds) and it will be delivered as part of Aspire 8.2 release. Not exactly sure if the release date is set already, but it is in the "weeks, not months" category.

@davidfowl As part of container orchestration, we do inspect running containers several times. In Aspire 8.0, if inspect command failed, we would re-try the inspection indefinitely. This mostly works, but if the container was deleted from under us, we would not notice (there was a customer issue reported about that). So in Aspire 8.1 we changed that to make the container as state Unknown if the inspection failed. 

Turns out the `docker container inspect` command can fail sometimes for reasons that are not entirely clear https://github.com/docker/cli/discussions/5319 I implemented a workaround where we try the inspection several times, with exponential backoff, before giving up and deeming the container as being in Unknown state. That is the change for Aspire 8.2.

**Comment by karolz-ms** [comment] 2024-08-12 16:48
@hades200082 I would appreciate a report if the new version of the hosting package solves the problem for you. The fact that it reproduces with Podman does make a difference and suggests maybe it is a problem on the DCP side... but the workaround should still help.

**Comment by karolz-ms** [comment] 2024-08-12 22:58
@hades200082 I am sorry, my mistake, the move to NuGet packages has not been quite completed yet. That said the instructions to use daily builds should enable you to test the fix. Pro tip: do a snapshot of your machine first, so that you can revert to a published workload quickly.

**Comment by hades200082** [comment] 2024-08-16 22:01
@karolz-ms I'm not certain about using the daily builds as I have a lot of production work and am worried about messing something up that will take too much time to put right.

By snapshot were you referring to a system restore point?

**Comment by karolz-ms** [comment] 2024-08-16 23:19
Totally understand. And yes, system restore point is what I meant.

**Comment by hades200082** [comment] 2024-08-31 16:12
@karolz-ms I've been using 8.2 over the past couple of days on different PCs using both Docker Desktop and Podman Desktop and haven't seen the unknown state once so far.

**Comment by karolz-ms** [comment] 2024-09-03 00:00
@hades200082 thanks for letting me know. Glad it is working for you!
