### ISSUE TITLE
[WebToolsE2E][Aspire] Reduce the browser window, drag the dividing line between elements, and then enlarge the browser. The format in the dashboard is incorrect.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#2009] opened 2024-01-31 07:52 UTC
**REGRESSION INFO**: Repro on Aspire 8.0.0-preview.1.23557.2 and 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.0 Preview 1.0 [34530.244.main]
3. Install 8.0.200 RTM SDK
4. Install Aspire Preview 3 latest build 8.0.0-preview.3.24080.1
5. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web App (Razor Pages) > Next > .NET 8.0 > check "Enlist in .NET Aspire orchestration" > Create,
2. F5 to run the project
3. Click the browser's shrink button to shrink the browser, drag the dividing line between any elements, Then click the browser's magnify button to enlarge the browser

**Notes**:
Manually refresh the page and the page format returns to normal.

**ACTUAL**
The content format in Resources does not change after enlarging the browser window.
![aspire](https://github.com/dotnet/aspire/assets/109339894/ac3a4773-7b10-4f0a-a5d8-a7975c04fdbe)
![image](https://github.com/dotnet/aspire/assets/109339894/f56f10d8-01e3-432f-92b2-39fcb64dd636)

**EXPECTED**
The browser page format should be as shown below.
![image](https://github.com/dotnet/aspire/assets/109339894/4331a3ff-0918-441d-86f9-637a0c13a13b)

**Comment by davidfowl** [comment] 2024-01-31 08:13
@kvenkatrajan I put this in preview 4 since it isn't a regression. Feel free to move it if you feel strongly about it.

**Comment by kvenkatrajan** [comment] 2024-01-31 15:54
The dashboard UI doesnt currently support responsive layout, that would be a much bigger change post v1. There is another similar item tracking this - #1740

Moving this if you dont have any immediate concerns here.

**Comment by davidfowl** [comment] 2024-02-03 05:40
Closing as duplicate

**Closed by davidfowl** 2024-02-03 05:40 UTC
Labels: area-dashboard, untriaged
