### ISSUE TITLE
[WebToolsE2E][Aspire] Restarting the project in Resources for 9.0 blazor web app, an 'Exception Unhandled' error occurred in VS.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6372] opened 2024-10-18 09:32 UTC
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2
2. Install VS 17.12 P4 candidate
 
**REPRO STEPS**
1. New Project > Blazor Web App > Individual Account > Auto > Global > .NET 9.0 (Preview) > Individual > checked 'Enlist in Aspire orchestration'> Create
2. Build solution and run the project
3. Restart the project in Resources

**NOTE**
1. This is not reproduce in 8.0 framework

**ACTUAL**
'Exception Unhandled' error occurred in VS
![Image](https://github.com/user-attachments/assets/d09a22c8-2bdb-4e0c-b3bc-37e5b5ca9fa6)

**EXPECTED**
The project in Resources can be restart successfully without an error.

**Comment by joperezr** [comment] 2024-10-22 23:09
Thanks for the report @vmykagapuz. Can you please push the repro project into GH so that we can take a peek?

**Comment by v-elenafeng** [comment] 2024-10-23 10:05
@joperezr This is a 9.0 Blazor WASM project with Aspire checked on the NPD.
[BlazorWASMAppWithAspire](https://github.com/v-elenafeng/BlazorWASMAppWithAspire)

**Comment by balachir** [comment] 2024-11-08 17:20
@vmykagapuz using the latest build of VS 17.12 GA, I'm unable to reproduce this issue. If I turn on 'Enable New .NET 9+ Mono Debugger' in Tools - Options - Environment - Preview features, then I can see a different issue when I follow your repro steps. Can you try it? 

If you can repro as well, please open a new bug in AzDO for 17.13 and we can take a look. I'll go ahead and close this GitHub issue for now.

![Image](https://github.com/user-attachments/assets/f4ff7eeb-4e17-4e62-8e2f-108619922f00)

cc: @v-elenafeng

**Closed by balachir** 2024-11-08 17:20 UTC
Labels: area-tooling, external

**Comment by v-elenafeng** [comment] 2024-11-15 08:17
> [@vmykagapuz](https://github.com/vmykagapuz) using the latest build of VS 17.12 GA, I'm unable to reproduce this issue. If I turn on 'Enable New .NET 9+ Mono Debugger' in Tools - Options - Environment - Preview features, then I can see a different issue when I follow your repro steps. Can you try it?
> 
> If you can repro as well, please open a new bug in AzDO for 17.13 and we can take a look. I'll go ahead and close this GitHub issue for now.
> 
> ![Image](https://github.com/user-attachments/assets/f4ff7eeb-4e17-4e62-8e2f-108619922f00)
> 
> cc: [@v-elenafeng](https://github.com/v-elenafeng)

Bug in AzDo: [2301374](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2301374).
