### ISSUE TITLE
Argument validation in model

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2799] opened 2024-03-12 02:07 UTC
The model is annotated properly for null. However, there is no runtime validation. If someone is configuring the model without nullable analysis enabled, then they could quite easily get hard to solve NRE.

The model should validate arguments. If something shouldn't be null then add `ArgumentNullException.ThrowIf(xxx)`.

**Comment by davidfowl** [comment] 2024-03-12 02:10
Dupe of https://github.com/dotnet/aspire/issues/2649

**Closed by davidfowl** 2024-03-12 02:10 UTC
Labels: area-app-model, untriaged
