### ISSUE TITLE
AppHost terminates during startup missing kubeconfig

### ISSUE THREAD

**Issue by attilah** [dotnet/aspire#3091] opened 2024-03-22 01:43 UTC
I've an aspire solution on Preview 4 which was working good, and suddenly Today AppHost started to fail to start :-/

I've experienced 2 possible outcomes:
- AppHost fails to start and file is not there
- AppHost complains that file is not there, but then it is created and starts, but still inoperable, as dashboard runs but there are no resources in the dashboard.

It waits long before dumping the stacktrace and failing. 

I've tried the typical steps of removing aspire workload, reinstalled, etc.

I'm on MacOS, .NET Runtime 8.0.3 SDK 8.0.200.

Here is the stacktrace from AppHost:
```
AppHost
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.0-preview.4.24156.9+692dc41a65da572a7df25d53a9f2880afe59fdd8
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: /Users/attila/workspaces/rendering/Posta.Creator/Posta.Creator.AppHost
fail: Aspire.Hosting.Dashboard.DcpDataSource[0]
      Watch task over kubernetes Endpoint resources terminated
      k8s.Exceptions.KubeConfigException: kubeconfig file not found at /var/folders/l1/s577klg931l7lz01x503kvgw0000gn/T/aspire.PGyJWz/kubeconfig
         at k8s.KubernetesClientConfiguration.LoadKubeConfigAsync(FileInfo kubeconfig, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)
         at Aspire.Hosting.Dcp.KubernetesService.EnsureKubernetes() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 234
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 200
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 208
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 138
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Aspire.Hosting.Dashboard.DcpDataSource.<>c__DisplayClass9_1.<<-ctor>g__WatchKubernetesResource|1>d`1.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DcpDataSource.cs:line 70
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dashboard.DcpDataSource.<>c__DisplayClass9_1.<<-ctor>g__WatchKubernetesResource|1>d`1.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DcpDataSource.cs:line 70
fail: Aspire.Hosting.Dashboard.DcpDataSource[0]
      Watch task over kubernetes Executable resources terminated
      k8s.Exceptions.KubeConfigException: kubeconfig file not found at /var/folders/l1/s577klg931l7lz01x503kvgw0000gn/T/aspire.PGyJWz/kubeconfig
         at k8s.KubernetesClientConfiguration.LoadKubeConfigAsync(FileInfo kubeconfig, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)
         at Aspire.Hosting.Dcp.KubernetesService.EnsureKubernetes() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 234
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 200
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 208
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 138
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Aspire.Hosting.Dashboard.DcpDataSource.<>c__DisplayClass9_1.<<-ctor>g__WatchKubernetesResource|1>d`1.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DcpDataSource.cs:line 70
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dashboard.DcpDataSource.<>c__DisplayClass9_1.<<-ctor>g__WatchKubernetesResource|1>d`1.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DcpDataSource.cs:line 70
fail: Aspire.Hosting.Dashboard.DcpDataSource[0]
      Watch task over kubernetes Service resources terminated
      k8s.Exceptions.KubeConfigException: kubeconfig file not found at /var/folders/l1/s577klg931l7lz01x503kvgw0000gn/T/aspire.PGyJWz/kubeconfig
         at k8s.KubernetesClientConfiguration.LoadKubeConfigAsync(FileInfo kubeconfig, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)
         at Aspire.Hosting.Dcp.KubernetesService.EnsureKubernetes() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 234
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 200
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 208
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 138
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Aspire.Hosting.Dashboard.DcpDataSource.<>c__DisplayClass9_1.<<-ctor>g__WatchKubernetesResource|1>d`1.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DcpDataSource.cs:line 70
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dashboard.DcpDataSource.<>c__DisplayClass9_1.<<-ctor>g__WatchKubernetesResource|1>d`1.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DcpDataSource.cs:line 70
fail: Aspire.Hosting.Dashboard.DcpDataSource[0]
      Watch task over kubernetes Container resources terminated
      k8s.Exceptions.KubeConfigException: kubeconfig file not found at /var/folders/l1/s577klg931l7lz01x503kvgw0000gn/T/aspire.PGyJWz/kubeconfig
         at k8s.KubernetesClientConfiguration.LoadKubeConfigAsync(FileInfo kubeconfig, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
         at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)
         at Aspire.Hosting.Dcp.KubernetesService.EnsureKubernetes() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 234
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 200
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 208
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 138
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Aspire.Hosting.Dashboard.DcpDataSource.<>c__DisplayClass9_1.<<-ctor>g__WatchKubernetesResource|1>d`1.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DcpDataSource.cs:line 70
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dashboard.DcpDataSource.<>c__DisplayClass9_1.<<-ctor>g__WatchKubernetesResource|1>d`1.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DcpDataSource.cs:line 70
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: http://localhost:5001
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
```

**Comment by aaronpowell** [comment] 2024-03-22 05:14
This is caused by the DCP exceeding the timeout that was set while waiting for the kubeconf file to be written. In preview 4 this was 5s but has been increased in preview 5.

Without upgrading to preview 5 I wasn't able to work around this problem.

@karolz-ms

**Comment by davidfowl** [comment] 2024-03-27 05:20
@mitchdenny this should be fixed in p5 right?

**Comment by martinjt** [comment] 2024-03-31 19:00
Is there any other workaround for this? I'm getting it 100% of the time for my WSL2 instance making it unusable :/

**Comment by mitchdenny** [comment] 2024-04-01 00:05
Yes, this should be fixed in P5. There is a race condition in P4. Unfortunately I don't think there is a workaround.

What is curious is that you are seeing two possible outcomes. I'm speculating but it could be the previous instance of DCP has finished starting, writes its kubeconfig file, the AppHost reads it and connects but then it self terminates because it finally figures out the process it launched from is gone and self terminates.

That said there are few things in the code that should stop that from happening (including the Kubeconfig file being written to a random directory). Would be very interested to know if you can repro this on P5.

**Closed** 2024-04-09 05:05 UTC
Labels: area-app-model
