### ISSUE TITLE
[WebToolsE2E][Aspire] Using VS Code to Debug Aspire App with an exception of type 'System.AggregateException': "ASPNETCORE_URLS environment variable not set".

### ISSUE THREAD

**Issue by v-gaolisa** [dotnet/aspire#1939] opened 2024-01-29 07:33 UTC
**REGRESSION INFO**: Not repro on Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

Clean machine: Win11 x64 23h2 ENU
Install VS Code[1.85.2]
Install C# Dev Kit[1.3.6]
Install SDK 8.0.200
Install Aspire Preview 3 latest build 8.0.0-preview.3.24078.5
Apply NuGet Feeds

**REPRO STEPS**

1. Create .NET Project > .NET Aspire Application > give a name > Create
2. Right-click xxx.AppHost name > Debug > Start New Instance

**ACTUAL**
Run with Exception thrown: 'System.AggregateException' in System.Private.CoreLib.dll, ASPNETCORE_URLS environment variable not set.
![image](https://github.com/dotnet/aspire/assets/89128759/3cbc598b-12cb-42ca-b6ba-83bc2a65d631)
Exception has occurred: CLR/System.AggregateException
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Aspire.Hosting.DistributedApplicationException : ASPNETCORE_URLS environment variable not set.
   at Aspire.Hosting.Dcp.ApplicationExecutor.<StartDashboardAsDcpExecutableAsync>d__14.MoveNext()
   at Aspire.Hosting.Dcp.ApplicationExecutor.<RunApplicationAsync>d__12.MoveNext()
   at Aspire.Hosting.Dcp.DcpHostService.<StartAsync>d__10.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<<StartAsync>b__15_1>d.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<ForeachService>d__18`1.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Aspire.Hosting.DistributedApplication.<RunAsync>d__13.MoveNext()
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: ASPNETCORE_URLS environment variable not set.
         at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 202
         at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 91
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Microsoft.Extensions.Hosting.Internal.Host: Error: Hosting failed to start

Aspire.Hosting.DistributedApplicationException: ASPNETCORE_URLS environment variable not set.
   at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 202
   at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 91
   at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Exception thrown: 'System.AggregateException' in System.Private.CoreLib.dll

**EXPECTED**
No error and warning shows with run the project.

**Comment by davidfowl** [comment] 2024-01-29 07:35
Dupe of https://github.com/dotnet/aspire/issues/1928

**Closed by davidfowl** 2024-01-29 07:35 UTC
Labels: area-app-model
