### ISSUE TITLE
When Aspire.Dashboard added to a Web project it's appsettings and launcConfiguration takes over the "host" project.

### ISSUE THREAD

**Issue by attilah** [dotnet/aspire#1271] opened 2023-12-07 06:03 UTC
I tried to use the Aspire.Dashboard in a project outside of Aspire and while everything worked, I found out (the hard way) that it's NuGet package contains the `launchConfiguration.json` and `appSettings*.json` files.

It seems that the default SDK behavior is that it is copied over when the project is running so any custom configuration I've in my own web project's appSettings will not be read.

Are those files have to be packaged with the dashboard or is it just an oversight?

I think (haven't tried) that if you add an appSettings to the Hosting project where it's referenced within an Aspire solution, the same problem will arise.

**Comment by DamianEdwards** [comment] 2023-12-07 15:17
The Aspire.Dashboard package isn't currently in a state that it can be easily consumed from other projects but that's something we're currently working towards

Dupe of #846

**Closed by DamianEdwards** 2023-12-07 15:17 UTC
Labels: area-dashboard
