### ISSUE TITLE
Aspire Dashboard Metrics: Meter tags do not display

### ISSUE THREAD

**Issue by JackRhodes** [dotnet/aspire#4380] opened 2024-06-04 14:56 UTC
Originally posted in the https://github.com/open-telemetry/opentelemetry-dotnet/discussions/5669#discussioncomment-9665983 but re-directing here:

Aspire dashboard does not show Meter defined Tags in the dashboard

Example code:

```
// See https://aka.ms/new-console-template for more information

using System.Diagnostics.Metrics;
using OpenTelemetry;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;

using var meter = new Meter("TestMeter", "1.0.0", new[]
{
    new KeyValuePair<string, object?>("namespace", "jacklocaldev")
});

var providerBuilder = Sdk.CreateMeterProviderBuilder()
    .ConfigureResource(r => r.AddService("testservice"))
    .AddMeter(meter.Name); // All instruments from this meter are enabled.

providerBuilder.AddOtlpExporter();

var provider = providerBuilder.Build();

while (true)
{
    await Task.Delay(TimeSpan.FromSeconds(1));
    meter.CreateCounter<int>("foo").Add(1);
}
```

Aspire Dashboard:

I would be expecting the `namespace` tag to show.

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/23398170/7d1ce634-8c48-4acd-ac91-0f22815df7c7)

**Comment by JamesNK** [comment] 2024-07-24 08:50
Hi, I tested this out and confirmed what you're seeing. I believe the issue is inside opentelemetry-dotnet. It doesn't send the meter tags so it's impossible for the dashboard to display them.

Here is the issue on the opentelemetry repo: https://github.com/open-telemetry/opentelemetry-dotnet/issues/5478

**Comment by cijothomas** [comment] 2024-07-24 16:22
> I believe the issue is inside opentelemetry-dotnet. It doesn't send the meter tags

@JamesNK Meter tags are supported in OTLP Exporters. Is the issue *only* when using Aspire dashboard, or can be repro-ed with OTel Collector?

**Comment by JamesNK** [comment] 2024-07-25 01:05
I took a closer look and I see they're reported on the instrument scope. I expected them to be merged into the attributes collection on a data point.

I'll update the UI to combine them.

**Closed** 2024-07-25 14:50 UTC
Labels: area-dashboard, area-telemetry, blocked
