### ISSUE TITLE
resource healthcheck

### ISSUE THREAD

**Issue by gabriel-systems** [dotnet/aspire#2487] opened 2024-02-27 23:21 UTC
please consider using injection of healthchecks for projects where .WithReference({serviceName}) is configured; example would be where the serviceName = redisContainer and the redis container has been configured would inject the health check for redis into the projects that are configured .WithReference(redisContainer)

**Comment by davidfowl** [comment] 2024-02-27 23:39
Dupe of https://github.com/dotnet/aspire/issues/890

**Closed by davidfowl** 2024-02-27 23:39 UTC
Labels: area-components, untriaged
