### ISSUE TITLE
[WebToolsE2E][Aspire] Set the dashboard theme to dark, then click the Settings button again, the theme color will automatically return to the system default.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#6264] opened 2024-10-12 07:24 UTC
**REGRESSION INFO:** worked in aspire 8.2.1

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 9.0 RC2
3. Install Aspire 9.0 template -latest version 9.0.0-rc.1.24511.1
    - Add dotnet8 feed
    - dotnet new install Aspire.ProjectTemplates::9.0.0-rc.1.24511.1 --force

**REPRO STEPS**

1. Open CMD, run following command to create an Aspire Starter App project
```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
```
2. Dotnet run the project in CMD, and open URL in the browser
`dotnet run`
3. Set the dashboard theme to Dark, then click the Settings button again, the theme color will automatically return to the system default 

**ACTUAL**

![Image](https://github.com/user-attachments/assets/19ad97f5-8760-489a-b394-e2eeaefc7faf)

**EXPECTED**

Click the Settings button again, the theme color will still be the one you selected last time.

**Comment by JamesNK** [comment] 2024-10-14 00:43
Duplicate of https://github.com/dotnet/aspire/issues/6020

Was fixed recently.

**Closed by JamesNK** 2024-10-14 00:43 UTC
Labels: bug, area-dashboard
