### ISSUE TITLE
[CodeSpaces] The `launchSettings.json` of AppHost doesn't seem to be properly respected

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#1296] opened 2023-12-08 16:54 UTC
The `launchSettings.json` of AppHost doesn't seem to be properly respected - `launchSettings.json` of AppHost has these two attributes like:
```
"applicationUrl": "http://localhost:<random_port_number>",
"environmentVariables": {
  "DOTNET_DASHBOARD_OTLP_ENDPOINT_URL": "http://localhost:<random_port_number>"
}
```
I initially expected that the applicationUrl attribute will be used to launch the dashboard page, but it uses http://localhost:18888. I'm not sure what these applicationUrl and DOTNET_DASHBOARD_OTLP_ENDPOINT_URL are for.

**Comment by DamianEdwards** [comment] 2023-12-08 20:23
This seems to be missing some detail?

**Comment by justinyoo** [comment] 2023-12-09 04:20
Hi, @DamianEdwards It's in the context of GitHub Codespaces (and possibly VS Code). When I check it in VS, the URLs defined in `launchSettings.json` are properly used. However, when it comes to GitHub Codespaces, it uses pre-configured (or hard-coded port numbers like 1888 or 18889.

Wonder whether it's by design or not.

**Comment by mitchdenny** [comment] 2024-10-08 05:37
Closing this. In terms of the port mappings for the dashboard it seems to be detecting the right URL (I launch with `dotnet run -lp http` (the proxy doesn't like out SSL cert).

It correctly opens the dashboard at the value specified for `applicationUrl`. Its possible that this earlier behavior was a bug that we had in .NET Aspire 8.x.

FYI, I've done some experimentation on making the URLs in the dashboard show the proxied URLs:

#1178

**Closed by mitchdenny** 2024-10-08 05:37 UTC
Labels: bug, area-tooling
