### ISSUE TITLE
AppHost should write Dashboard logs to console when it fails

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#3429] opened 2024-04-05 15:58 UTC
When the Dashboard fails to launch, it is not easy to debug why. You get a "normal" console log output and things look like they are running. But when you try to hit the Dashboard it refuses the connection (because the process isn't running anymore).

We need to write the logs from the Dashboard to the console in this case. Users will have no idea how to figure out what happened. The only way I know today is to dig into DCP and ask it for the logs.

An easy way to get into this situation today is to install the `8.0-preview5` of the workload. And then use a recent `8.1` build of Aspire.Hosting in your AppHost. You can do this by just lifting up an Aspire.Hosting package to 8.1.

```xml
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.0.0-preview.5.24201.12" />
    <PackageReference Include="Aspire.Hosting.Qdrant" Version="8.1.0-preview.1.24204.10" />
  </ItemGroup>
```

Running the AppHost gives me:

```
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.1.0-preview.1.24204.10+45df94ff325848fefe58a7668817c4c7b3981b4e
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: C:\Users\eerhardt\source\repos\AspireApp13\AspireApp13.AppHost
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: https://localhost:17150
info: Aspire.Hosting.DistributedApplication[0]
      Login to the dashboard at https://localhost:17150/login?t=2284270edba1ece85eb9b043fc27cb2f
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
```

but when I hit the Dashboard it fails:
![image](https://github.com/dotnet/aspire/assets/8291187/2ad37a3a-9b53-484f-8e6e-a8b3617ff6ea)

And then digging into the DCP logs of the Dashboard gives me:

```
Unhandled exception. System.InvalidOperationException: Failed to convert configuration value at 'Dashboard:Frontend:AuthMode' to type 'Aspire.Dashboard.Configuration.FrontendAuthMode'.
 ---> System.FormatException: BrowserToken is not a valid value for FrontendAuthMode.
 ---> System.ArgumentException: Requested value 'BrowserToken' was not found.
   at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
   at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, String path, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
   at Aspire.Dashboard.DashboardWebApplication.GetDashboardOptions(WebApplicationBuilder builder, IConfigurationSection dashboardConfigSection) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 234
   at Aspire.Dashboard.DashboardWebApplication..ctor(Action`1 configureBuilder) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 82
   at Program.<Main>$(String[] args) in /_/src/Aspire.Dashboard/Program.cs:line 7

```

**Comment by davidfowl** [comment] 2024-04-06 18:48
I think it's important we fix this in p6 to help diagnosability for ourselves.

**Comment by davidfowl** [comment] 2024-04-06 19:28
Dupe of https://github.com/dotnet/aspire/issues/2911

**Closed by davidfowl** 2024-04-06 19:28 UTC
Labels: area-app-model
