### ISSUE TITLE
Support for AddPooledDbContextFactory

### ISSUE THREAD

**Issue by jkears** [dotnet/aspire#1781] opened 2024-01-23 15:33 UTC
I am looking to include tracing to EF Core SQL however our services need to utilize ContextFactory and more specifically Pooled DB ContextFactory using `AddPooledDbContextFactory`. 

Having reviewed the code for the current Aspire component for SQL it is very limited so as an interim I added these lines to my logic that seem to provide the tracing into SQL.   
```
  builder.Services.AddOpenTelemetry().WithTracing(tracerProviderBuilder =>
    {
        tracerProviderBuilder.AddEntityFrameworkCoreInstrumentation();
    });
       
    builder.Services.AddOpenTelemetry().WithMetrics(meterProviderBuilder =>
    {
        meterProviderBuilder.AddEventCountersInstrumentation(eventCountersInstrumentationOptions =>
        {
            // https://github.com/dotnet/efcore/blob/main/src/EFCore/Infrastructure/EntityFrameworkEventSource.cs#L45
            // https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientEventSource.cs#L73
            eventCountersInstrumentationOptions.AddEventSources("Microsoft.EntityFrameworkCore", "Microsoft.Data.SqlClient.EventSource");
        });
    });
```
Here is the entire DB configuration logic... 

```
public static IHostApplicationBuilder AddDbContext(this IHostApplicationBuilder builder, SecretClient secretClient)
{
    var primarySqlConfigKey = builder.Configuration["PrimarySQLConfigKey"];
    if (string.IsNullOrEmpty(primarySqlConfigKey))
    {
        primarySqlConfigKey = "PrimaryPortDomainServiceDbConn";
    }
    // Retrieve KeyVault secrets for initialization
    var primaryPortDomainServiceDbConnSecret = secretClient.GetSecret(primarySqlConfigKey);
                                                                
    builder.Services.AddPooledDbContextFactory<AppDbContext>((_, o) =>
        o.UseSqlServer(primaryPortDomainServiceDbConnSecret.Value.Value,
                b =>
                        b.MigrationsAssembly("NextWare.UI.Builder.EditServices.API")));
      
    builder.Services.AddOpenTelemetry().WithTracing(tracerProviderBuilder =>
    {
        tracerProviderBuilder.AddEntityFrameworkCoreInstrumentation();
    });
       
    builder.Services.AddOpenTelemetry().WithMetrics(meterProviderBuilder =>
    {
        meterProviderBuilder.AddEventCountersInstrumentation(eventCountersInstrumentationOptions =>
        {
            // https://github.com/dotnet/efcore/blob/main/src/EFCore/Infrastructure/EntityFrameworkEventSource.cs#L45
            // https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientEventSource.cs#L73
            eventCountersInstrumentationOptions.AddEventSources("Microsoft.EntityFrameworkCore", "Microsoft.Data.SqlClient.EventSource");
        });
    });

    return builder;
}
```
The trace shows a call via a GraphQL gateway, routing over DAPR to a downstream service and includes the trace into SQL ...  

![image](https://github.com/dotnet/aspire/assets/1290937/8384990b-c6d9-4922-8482-5d75eadc5e55)

This is running on my local machine, with the SQL DB hosted in Azure, so I get the 42ms it takes to invoke the call into SQL and I assume any additional delay is due to the extensive tracing and logging that is turned on.   

Is there a better way to create the same Pooled DB Context Factory using the existing EF SQL component? 

Cheers

**Comment by eerhardt** [comment] 2024-01-29 20:31
This will be fixed by https://github.com/dotnet/aspire/issues/1403. Closing as a dupe of it.

**Closed by eerhardt** 2024-01-29 20:31 UTC
Labels: area-components, untriaged
