### ISSUE TITLE
Allow Dashboard to be used standalone

### ISSUE THREAD

**Issue by martinjt** [dotnet/aspire#847] opened 2023-11-15 18:58 UTC
The Dashboard is great, and something that is much needed for local development, that's beyond the Cloud Native part.

I think it would be great if the Dashboard were to be available as a docker image that people could spin up and use. A few things that would make that more useful.

* Make TelemetryRepository an interface
* Add Http Ingest
* Allow removing of dashboard items that aren't configured (like tailed logs etc.)

Making the TelemetryRepository an interface would allow for the container to have something like a sqlite db under the hood so it can live beyond restarts, but obviously wouldn't be great performance wise, so it could be used in production.

If it's something that's of interest, I could definitely PR some of it in.

**Comment by leslierichardson95** [comment] 2023-12-13 23:43
Duplicate of #846

**Comment by martinjt** [comment] 2023-12-14 12:00
I don't think this is duplicate of that one.

Adding Aspire to an existing project (as in no extra workload process) is different that running Aspire as a standalone project.

From what I can gather, there is more appetite inside Microsoft to do a standalone instance than make it work as an add on to an existing app.

**Comment by DamianEdwards** [comment] 2023-12-14 23:27
Agreed @martinjt, re-opening this to track the standalone scenario, e.g. as  dotnet tool.

**Comment by davidfowl** [comment] 2023-12-14 23:28
We have no plans to do this to the existing dashboard. I think if someone is interested, they can come up with a proposal based on the existing work we're doing.

**Comment by davidfowl** [comment] 2024-01-10 06:11
I'm closing this in favor of https://github.com/dotnet/aspire/issues/1003

**Closed by davidfowl** 2024-01-10 06:11 UTC
Labels: area-dashboard
