### ISSUE TITLE
[WebToolsE2E][Aspire] After adding an ASP.NET Core Empty project to an existing Aspire project's solution, then add project reference from xxx.AppHost to empty, a warning occurs "The type name 'empty' only contains lower-cased ascii characters. Such names may become reserved for the language.".

### ISSUE THREAD

**Issue by v-polly** [dotnet/aspire#2609] opened 2024-03-04 08:45 UTC
**REGRESSION INFO**: Repro on Aspire 8.0.0 preview 3.24105.21

**INSTALL STEPS**

1.Clean machine: Win11 x64 23h2 ENU
2.Install VS Code[1.87.0]
3.Install C# Dev Kit[1.4.6]
4.Install SDK 8.0.202
5.Install Aspire.ProjectTemplates.8.0.0-preview.4.24129.7
6.Apply NuGet Feeds

**REPRO STEPS**

1.Open CMD, creating an Aspire App using following commands:
`dotnet new aspire -o aspire1`
`cd aspire1`
`code .`
2.'Ctrl-Shift-P' to add a new ASP.NET Core Empty / ASP.NET Core Web App / ASP.NET Core Web App (Model-View-Controller) project under this solution > give a name 'empty'
3.Right-click the xxx.AppHost > Add project reference to empty
4.Buld Solution.

**ACTUAL**
A warning occurs "The type name 'empty' only contains lower-cased ascii characters. Such names may become reserved for the language.[C:\Users\v-xxx\aspire1\aspire1\aspire1.AppHost\aspire1.AppHost.csproj] ([CS8981](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/warning-waves?f1url=%3FappId%3Droslyn%26k%3Dk(CS8981)))"

![image](https://github.com/dotnet/aspire/assets/88425944/d2c4cde1-cf1b-4850-996b-f86687620244)

**EXPECTED**
There won't be any warnings.

**Comment by DamianEdwards** [comment] 2024-03-04 19:11
I'm not sure we should do anything about this. If the user names their project with all lowercase letters then that's the type name we'll produce. Alternatively we could attempt to always PascalCase their project name but it feels odd to me for us to do that.

Thoughts @eerhardt @davidfowl @mitchdenny @ReubenBond?

**Comment by eerhardt** [comment] 2024-03-04 19:21
> I'm not sure we should do anything about this. If the user names their project with all lowercase letters then that's the type name we'll produce.

I agree with this. We should just be using the value given to us as much as possible IMO.

**Comment by mitchdenny** [comment] 2024-04-01 00:46
Agree. Closing this one as its by design.

**Closed by mitchdenny** 2024-04-01 00:46 UTC
Labels: area-app-model
