### ISSUE TITLE
[WebToolsE2E][Aspire] Install Aspire 9.0 rc1 template, then install Aspire 8.2.2, cannot create Aspire 8.2.2 project.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#6427] opened 2024-10-22 09:33 UTC
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 9.0 RC2
3. Install Aspire 9.0 RC1[9.0.0-rc.1.24511.1]
4. Install Aspire 8.2.2

**REPRO STEPS**

1. Open CMD, create an Aspire Starter App project
`dotnet new aspire-starter-8 -o AspireApp`

**NOTE**:
Aspire template:
![Image](https://github.com/user-attachments/assets/533542ba-66b5-43d0-9a12-30047c4802e4)

**ACTUAL**:
The Aspire version of the created project is 8.2.1
![Image](https://github.com/user-attachments/assets/4dcb9b54-98bc-434e-bc33-d7637d09f531)

**EXPECTED**
After installing Aspire 8.2.2, should be able to create Aspire 8.2.2 projects.

**Comment by balachir** [comment] 2024-10-24 16:01
I believe this kind of issue will go away if we fix https://github.com/dotnet/aspire/issues/6483. I don't know if there will be an Aspire 8.2.3 though and this issue can re-appear then.

@v-elenafeng does this issue reproduce now with 'SDK 9.0 GA + Aspire 9.0 (includes Aspire 8.2.1 at the moment) + Aspire 8.2.2' configuration?

**Comment by v-sherryfan** [comment] 2024-10-25 06:54
@balachir @v-elenafeng Yes, this issue still repro on SDK 9.0 GA + Aspire 9.0.0 + Aspire 8.2.2

**Comment by v-elenafeng** [comment] 2024-10-28 05:46
This issue no longer exists due to the fix for [#6483](https://github.com/dotnet/aspire/issues/6483).

**Comment by balachir** [comment] 2024-10-28 14:09
Closing this issue as it does not repro anymore. Fyi, @v-elenafeng @v-sherryfan

**Closed by balachir** 2024-10-28 14:09 UTC
Labels: untriaged
