### ISSUE TITLE
`CosmosClient` can't connect to Cosmos DB Emulator created through aspire

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#6349] opened 2024-10-17 01:16 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

If you create a cosmos emulator instance with aspire, and then try to connect to it from another application `CosmosClient`, attempting to do anything will hang nearly indefinitely.  (I've waited 5+ mins - maybe it fails eventually, but I didn't have patience to find out).

When looking at the debug logs, an initial connection is successfully made to `https://localhost:59029`, however the CosmosClient very shortly decides to use `https://172.17.0.2:8081/` instead - the IP is the raw IP address of the container, and the port is the container port, not the DCP proxy port.
```
DocDBTrace Information: 0 : DocumentClient with id 1 initialized at endpoint: https://localhost:59029/ with ConnectionMode: Gateway, connection 
...
DocDBTrace Information: 0 : Current WriteEndpoints = (https://172.17.0.2:8081/) ReadEndpoints = (https://172.17.0.2:8081/)
```

On the aspire side, you can work around this by setting `AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE` and also exposing the 8081 directly on port 8081 (although I suspect this will break containers trying to talk to cosmos).

```cs
.RunAsEmulator(container =>
{
    var endpoint = container.GetEndpoint("emulator");

    container
        .WithEnvironment("AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE", "127.0.0.1")
        .WithHttpsEndpoint(port: endpoint.TargetPort, targetPort: endpoint.TargetPort, isProxied: false);
        // May be able to do something with `AZURE_COSMOS_EMULATOR_ARGS="/port 12345"` if you can update the targetport to match the dynamically allocated dcp port
    ;
});
```

Alternatively on the caller side, you can work around this by setting `LimitToEndpoint` to true - this has been done for the cosmosdb health checks - https://github.com/dotnet/aspire/blob/7d66c53f697d35d4a01963bc824c29d63931d9f8/src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs#L170 .

### Expected Behavior

I'd expect `CosmosClient` to be able to connect to the emulator without having to set `LimitToEndpoint`.  If `LimitToEndpoint` is needed, then I'd expect to see this requirement documented at https://learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-integration?tabs=dotnet-cli .

I'd also like to see the cosmos client provide some kind of error, within 5 minutes to let you troubleshoot the problem, but that's an issue with the Azure SDK, not aspire.

### Steps To Reproduce

Aspire:
```cs
var cosmos = builder.AddAzureCosmosDB("cosmosDb")
    .RunAsEmulator(container =>
    {
        container
            .WithLifetime(ContainerLifetime.Persistent)
            .WithDataVolume()
            ;
    });
```

Console App
```cs
var client = new CosmosClientBuilder("AccountEndpoint=https://localhost:32787/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==")
         .WithHttpClientFactory(() => new HttpClient(new HttpClientHandler()
         {
             ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
         }))
         .WithConnectionModeGateway()
    .Build();

var db = await client.CreateDatabaseAsync("foo123"); // This will hang indefinitely
```

### Exceptions (if any)

Debug output 
```
DocDBTrace Information: 0 : DocumentClient with id 1 initialized at endpoint: https://localhost:59029/ with ConnectionMode: Gateway, connection Protocol: Https, and consistency level: null
DocDBTrace Information: 0 : Azure Environment metadata information not available. A socket operation was attempted to an unreachable network. (169.254.169.254:80)
DocDBTrace Information: 0 : SystemUsageMonitor started
DocDBTrace Information: 0 : Current WriteEndpoints = (https://172.17.0.2:8081/) ReadEndpoints = (https://172.17.0.2:8081/)
DocDBTrace Information: 0 : GlobalEndpointManager: StartLocationBackgroundRefreshWithTimer() refreshing locations
DocDBTrace Warning: 0 : ClientRetryPolicy: Gateway HttpRequestException Endpoint not reachable. Failed Location: https://172.17.0.2:8081/; ResourceAddress: 
DocDBTrace Information: 0 : GlobalEndpointManager: Marking endpoint https://172.17.0.2:8081/ unavailable for read
DocDBTrace Information: 0 : Current WriteEndpoints = (https://172.17.0.2:8081/) ReadEndpoints = (https://172.17.0.2:8081/)
DocDBTrace Information: 0 : Endpoint https://172.17.0.2:8081/ unavailable for Read added/updated to unavailableEndpoints with timestamp 10/16/2024 23:51:35
DocDBTrace Information: 0 : GlobalEndpointManager: Marking endpoint https://172.17.0.2:8081/ unavailable for Write
DocDBTrace Information: 0 : Current WriteEndpoints = (https://172.17.0.2:8081/) ReadEndpoints = (https://172.17.0.2:8081/)
```

### .NET Version info

		<PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0-rc.1.24511.1" />
		<PackageReference Include="Aspire.Hosting.Azure.CosmosDb" Version="9.0.0-rc.1.24511.1" />

```
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.47119bbc
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.403\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 8.0.400, VS 17.11.35222.181
   Manifest Version:    8.2.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.1\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  6.0.427 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Anything else?

Using `LimitToEndpoint` is the easier solution here, however I'm trying to wire cosmosdb up to azure functions, and I don't see a way to set `LimitToEndpoint` in Azure functions.

**Comment by davidfowl** [comment] 2024-10-17 02:13
Looks like a dupe of https://github.com/dotnet/aspire/issues/6349

**Comment by Mrxx99** [comment] 2024-10-17 06:14
You linked the issue to itself. did you mean #5364?

**Comment by davidfowl** [comment] 2024-10-17 06:18
Ah yes

**Comment by joperezr** [comment] 2024-10-22 23:29
Closing as duplicate of #5364

**Closed by joperezr** 2024-10-22 23:29 UTC
Labels: area-integrations, azure, azure-cosmosdb, untriaged
