### ISSUE TITLE
[WebToolsE2E][Aspire] Create a project with Enlist in .NET Aspire orchestration checked, but it fails when using "dotnet build" in cmd to build the project.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#1716] opened 2024-01-19 08:54 UTC
**REGRESSION INFO**: Also repro on Aspire 8.0.0-preview.1.23557.2 and Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.0 Preview 1.0 [34518.193.main]
3. Install Aspire Preview 3 latest build 8.0.0-preview.3.24068.3
4. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web App (Razor Pages) > Next > .NET 8.0 > check "Enlist in .NET Aspire orchestration" > Create, waited for restore to complete in VS
2. Right-click solution, Open Folder in File Explorer > open command prompt
3. Run "dotnet build"

**Note:**

1. If not check "Enlist in .NET Aspire orchestration", build can successful.
2. If you first right-click the solution to build the project, and then run "dotnet build" in cmd, the build will be successful.

**ACTUAL**
The build failed and two errors were displayed in cmd.
MSBuild version 17.9.2+bb6fadf23 for .NET
  Determining projects to restore...
  Restored D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\WebApplication5.csproj (in 167 ms).
  Restored D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5.AppHost\WebApplication5.AppHost.csproj (in
   556 ms).
  1 of 3 projects are up-to-date for restore.
D:\Program Files\dotnet\sdk\8.0.200-preview.24064.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInfer
ence.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-po
licy [D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5.ServiceDefaults\WebApplication5.ServiceDefaults
.csproj]
D:\Program Files\dotnet\sdk\8.0.200-preview.24064.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInfer
ence.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-po
licy [D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\WebApplication5.csproj]
D:\Program Files\dotnet\sdk\8.0.200-preview.24064.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInfer
ence.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-po
licy [D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5.AppHost\WebApplication5.AppHost.csproj]
  WebApplication5.ServiceDefaults -> D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5.ServiceDefaults\
  bin\Debug\net8.0\WebApplication5.ServiceDefaults.dll
D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\Program.cs(3,9): error CS1061: 'WebApplicationBuilder
' does not contain a definition for 'AddServiceDefaults' and no accessible extension method 'AddServiceDefaults' accept
ing a first argument of type 'WebApplicationBuilder' could be found (are you missing a using directive or an assembly r
eference?) [D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\WebApplication5.csproj]
D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\Program.cs(10,5): error CS1061: 'WebApplication' does
 not contain a definition for 'MapDefaultEndpoints' and no accessible extension method 'MapDefaultEndpoints' accepting
a first argument of type 'WebApplication' could be found (are you missing a using directive or an assembly reference?)
[D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\WebApplication5.csproj]

Build FAILED.

D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\Program.cs(3,9): error CS1061: 'WebApplicationBuilder
' does not contain a definition for 'AddServiceDefaults' and no accessible extension method 'AddServiceDefaults' accept
ing a first argument of type 'WebApplicationBuilder' could be found (are you missing a using directive or an assembly r
eference?) [D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\WebApplication5.csproj]
D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\Program.cs(10,5): error CS1061: 'WebApplication' does
 not contain a definition for 'MapDefaultEndpoints' and no accessible extension method 'MapDefaultEndpoints' accepting
a first argument of type 'WebApplication' could be found (are you missing a using directive or an assembly reference?)
[D:\Users\v-reinawang\source\repos\WebApplication5\WebApplication5\WebApplication5.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:07.06
![image](https://github.com/dotnet/aspire/assets/109339894/24d5f247-4f84-47c2-ac9b-a72c0e4a65bb)

**EXPECTED**
Should build successfully.

**Comment by balachir** [comment] 2024-01-19 12:21
@v-reinawang spme questions
- After creating the project in step 1, can you clarify whether you waited for restore to complete in VS before doing 'dotnet build' using CLI?
- Without building the solution using VS, if you run 'dotnet restore' for the solution and then do 'dotnet build', does it work using CLI this time?

cc: @v-sherryfan @v-cazhang

**Comment by mitchdenny** [comment] 2024-01-22 00:03
I'm actually able to reproduce this. Its a little bit more complex, you'll get other build failures before it settles on the one above. Then if you do a rebuild in VS, then it'll build successfully from the command-line.

**Comment by mitchdenny** [comment] 2024-01-22 00:16
It seems to be something to do with the solution not being saved. If you do a save all in VS, and then do a `dotnet build` it works. You can see that the solution file after adding the project does not include a reference to service defaults or the app host:
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.9.34414.90
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "WebApplication7", "WebApplication7\WebApplication7.csproj", "{85006EA2-8559-40D6-94ED-98D15762FD8F}"
EndProject
Global
        GlobalSection(SolutionConfigurationPlatforms) = preSolution
                Debug|Any CPU = Debug|Any CPU
                Release|Any CPU = Release|Any CPU
        EndGlobalSection
        GlobalSection(ProjectConfigurationPlatforms) = postSolution
                {85006EA2-8559-40D6-94ED-98D15762FD8F}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
                {85006EA2-8559-40D6-94ED-98D15762FD8F}.Debug|Any CPU.Build.0 = Debug|Any CPU
                {85006EA2-8559-40D6-94ED-98D15762FD8F}.Release|Any CPU.ActiveCfg = Release|Any CPU
                {85006EA2-8559-40D6-94ED-98D15762FD8F}.Release|Any CPU.Build.0 = Release|Any CPU
        EndGlobalSection
        GlobalSection(SolutionProperties) = preSolution
                HideSolutionNode = FALSE
        EndGlobalSection
        GlobalSection(ExtensibilityGlobals) = postSolution
                SolutionGuid = {4E3E8F63-7728-4B08-9DDD-98B89C0CFF96}
        EndGlobalSection
EndGlobal
```

**Comment by mitchdenny** [comment] 2024-01-22 00:17
... in fact the `WebApplication.csproj` file doesn't get saved either, which is why `dotnet build` doesn't work (because even if the solution file wasn't saved, you should still be able to build the web app project file and it would result in the service defaults not being built.

**Comment by v-reinawang** [comment] 2024-01-22 02:00
@balachir @mitchdenny 

- I have added "waited for restore to complete in VS" in Step 1.
- I run 'dotnet restore' for the solution and then do 'dotnet build', this issue is still repro.
- I do a save all in VS, and then do a dotnet build it works.

**Comment by mitchdenny** [comment] 2024-01-24 09:11
@phenning has the fix made its way into a build?

**Comment by phenning** [comment] 2024-01-25 17:51
Yes, this made it into main on Tuesday, so it should be in the latest internal preview builds.

**Comment by balachir** [comment] 2024-01-26 19:10
@v-reinawang can you verify this fix and close it? 

cc: @v-cazhang @v-sherryfan

**Comment by v-reinawang** [comment] 2024-01-29 04:49
Verify this issue is not repro on latest Aspire version, so closed it.

**Closed** 2024-01-29 04:50 UTC
Labels: bug, area-tooling
