### ISSUE TITLE
Error logs when stopping distributed host with CTRL-C

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2240] opened 2024-02-15 02:00 UTC
Fail log messages are written after pressing CTRL-C.
```
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: C:\Development\Source\aspire\playground\TestShop\AppHost
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: https://localhost:15887
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press CTRL-C to stop.
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"catalogservice-11g5tc0"}, "Reconciliation": 77, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogservice-11g5tc0_out_6f9a023b-4461-4ce4-99ee-be5bcfc9d79e", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogservice-11g5tc0_out_6f9a023b-4461-4ce4-99ee-be5bcfc9d79e: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"catalogservice-11g5tc0"}, "Reconciliation": 77, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogservice-11g5tc0_err_6f9a023b-4461-4ce4-99ee-be5bcfc9d79e", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogservice-11g5tc0_err_6f9a023b-4461-4ce4-99ee-be5bcfc9d79e: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"catalogservice-shhd1k0"}, "Reconciliation": 78, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogservice-shhd1k0_out_3b164f36-247f-4c62-bde1-986a6caab6a3", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogservice-shhd1k0_out_3b164f36-247f-4c62-bde1-986a6caab6a3: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"catalogservice-shhd1k0"}, "Reconciliation": 78, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogservice-shhd1k0_err_3b164f36-247f-4c62-bde1-986a6caab6a3", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogservice-shhd1k0_err_3b164f36-247f-4c62-bde1-986a6caab6a3: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReplicaSetReconciler[0]
      ExecutableReplicaSet status update failed {"ExecutableReplicaSet": {"name":"frontend"}, "Reconciliation": 99, "DesiredReplicas": 1, "TotalReplicas": 1, "ActiveReplicas": 1, "error": "executablereplicasets.usvc-dev.developer.microsoft.com \"frontend\" not found"}
fail: Aspire.Hosting.Dcp.dcpctrl.ControllerManager[0]
      Reconciler error  {"controller": "executablereplicaset", "controllerGroup": "usvc-dev.developer.microsoft.com", "controllerKind": "ExecutableReplicaSet", "ExecutableReplicaSet": {"name":"frontend"}, "namespace": "", "name": "frontend", "reconcileID": "5ce5e48d-d744-44f3-9582-97cca1b14b40", "error": "executablereplicasets.usvc-dev.developer.microsoft.com \"frontend\" not found"}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"basketservice-0cc6s1o"}, "Reconciliation": 79, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\basketservice-0cc6s1o_out_57f88c1c-fdeb-4256-a183-0fcaf0be8b32", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\basketservice-0cc6s1o_out_57f88c1c-fdeb-4256-a183-0fcaf0be8b32: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"basketservice-0cc6s1o"}, "Reconciliation": 79, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\basketservice-0cc6s1o_err_57f88c1c-fdeb-4256-a183-0fcaf0be8b32", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\basketservice-0cc6s1o_err_57f88c1c-fdeb-4256-a183-0fcaf0be8b32: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"frontend-r15fsao"}, "Reconciliation": 81, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\frontend-r15fsao_out_d5b1dff5-e2bd-45e3-9b06-c0a84faae6d5", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\frontend-r15fsao_out_d5b1dff5-e2bd-45e3-9b06-c0a84faae6d5: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"frontend-r15fsao"}, "Reconciliation": 81, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\frontend-r15fsao_err_d5b1dff5-e2bd-45e3-9b06-c0a84faae6d5", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\frontend-r15fsao_err_d5b1dff5-e2bd-45e3-9b06-c0a84faae6d5: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"orderprocessor-d4uguro"}, "Reconciliation": 83, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\orderprocessor-d4uguro_out_cdd368f4-25ba-4af6-af75-927e38f52eea", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\orderprocessor-d4uguro_out_cdd368f4-25ba-4af6-af75-927e38f52eea: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"orderprocessor-d4uguro"}, "Reconciliation": 83, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\orderprocessor-d4uguro_err_cdd368f4-25ba-4af6-af75-927e38f52eea", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\orderprocessor-d4uguro_err_cdd368f4-25ba-4af6-af75-927e38f52eea: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"apigateway-njj2nq8"}, "Reconciliation": 85, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\apigateway-njj2nq8_out_cc33273d-4df3-46d0-bd79-22f1aa37e076", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\apigateway-njj2nq8_out_cc33273d-4df3-46d0-bd79-22f1aa37e076: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"apigateway-njj2nq8"}, "Reconciliation": 85, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\apigateway-njj2nq8_err_cc33273d-4df3-46d0-bd79-22f1aa37e076", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\apigateway-njj2nq8_err_cc33273d-4df3-46d0-bd79-22f1aa37e076: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"catalogdbapp-6r4td1g"}, "Reconciliation": 86, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogdbapp-6r4td1g_out_b8bfdec8-410a-4535-ad85-c4598056fb92", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogdbapp-6r4td1g_out_b8bfdec8-410a-4535-ad85-c4598056fb92: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"catalogdbapp-6r4td1g"}, "Reconciliation": 86, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogdbapp-6r4td1g_err_b8bfdec8-410a-4535-ad85-c4598056fb92", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\catalogdbapp-6r4td1g_err_b8bfdec8-410a-4535-ad85-c4598056fb92: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"aspire-dashboard-03a8tig"}, "Reconciliation": 88, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\aspire-dashboard-03a8tig_out_88a21db3-9876-49cc-b817-6ebf8d38db97", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\aspire-dashboard-03a8tig_out_88a21db3-9876-49cc-b817-6ebf8d38db97: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"aspire-dashboard-03a8tig"}, "Reconciliation": 88, "path": "C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\aspire-dashboard-03a8tig_err_88a21db3-9876-49cc-b817-6ebf8d38db97", "error": "remove C:\\Users\\jamesnk\\AppData\\Local\\Temp\\aspire.wknvs11h.iqr\\aspire-dashboard-03a8tig_err_88a21db3-9876-49cc-b817-6ebf8d38db97: The process cannot access the file because it is being used by another process."}
```

**Comment by JamesNK** [comment] 2024-02-15 02:11
@karolz-ms Error messages coming from DCP.

**Comment by danegsta** [comment] 2024-02-16 17:41
Looks like a duplicate of #1683, which we're looking into.

**Closed by danegsta** 2024-02-16 17:41 UTC
Labels: area-dashboard, untriaged
