### ISSUE TITLE
Improve connection string to add debug options

### ISSUE THREAD

**Issue by meziantou** [dotnet/aspire#5014] opened 2024-07-22 17:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Aspire is mostly used for development purposes. So, it would be nice to enable debug options in the connection strings to help devs. 

For instance, on postgresql, you can enable the two following options to the connection string to get better error messages ([doc](https://www.npgsql.org/doc/connection-string-parameters.html)):
- `Include Error Detail=true`
- `Log Parameters=true`

### Describe the solution you'd like

I don't know if it's possible to enable these options by default. It could also be an extension method on resources that provide a database connection string.

````
var postgres = builder.AddPostgres("postgresdb");
var db = postgres.AddDatabase("sample")
    .AddConnectionStringOptions("Include Error Detail", "true")
    .AddConnectionStringOptions("Log Parameters", "true");
````

**Comment by davidfowl** [comment] 2024-09-07 10:48
Dupe of https://github.com/dotnet/aspire/issues/2964

**Closed by davidfowl** 2024-09-07 10:48 UTC
