### ISSUE TITLE
Dashboard should source resources from App Model, not DCP

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#1731] opened 2024-01-20 02:59 UTC
The dashboard service is still being driven by DCPs list (post #1003)of resources vs. only showing what is in the application model. The implication is that when the dashboard is registered as an executable, it is showing in the resource list which is something that we want to avoid. We should probably look to get the AppHost implementation of the resource server to only resources that are in the App Model rather than resources that may be started using DCP, but are more internal in nature.

**Comment by kvenkatrajan** [comment] 2024-01-22 16:28
Thanks. I have removed "must have for this preview" label on this one, moved the refactor to preview4 and created a new issue for #1753 for preview3

**Comment by davidfowl** [comment] 2024-01-28 03:27
Closing as dupe of https://github.com/dotnet/aspire/issues/436

**Closed by davidfowl** 2024-01-28 03:27 UTC
Labels: area-dashboard
