### ISSUE TITLE
[WebToolsE2E][Aspire] On a clean Windows machine with only .NET 9 SDK installed, when we open Aspire 8.1 solution, the restore fails and asks us to install aspire workload

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#6028] opened 2024-09-30 15:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install .NET SDK 9.0 RC2 - latest version
    - Apply dotnet9rc2feed
    - Run cred helper to authenticate the feed
1. Apply feed for Aspire 9.0 packages
    - Add dotnet8 feed

**REPRO STEPS**
1. Clone the repo WebTools-Samples-Aspire and checkout the rel/8.1 branch 
    - This is a simple repo that includes an AspireApp2_withRedis solution created using VS with Aspire 8.1.0
1. Run `dotnet restore` in the solution folder

**ACTUAL**
Message asking the user to install aspire workload

![image](https://github.com/user-attachments/assets/a1837723-6fab-4779-bb99-3d6c54acac1a)

**EXPECTED**
Clear messages that describe to the user how to upgrade their solution to Aspire 9.0

**ADDITIONAL INFO**

**dotnet --info**
![image](https://github.com/user-attachments/assets/ade907e8-e503-4c13-974c-0e24434a3678)

**dotnet workload list**
![image](https://github.com/user-attachments/assets/f1213c78-8039-4e5a-a87c-67819b8fef5c)

**Comment by DamianEdwards** [comment] 2024-09-30 18:20
This is expected. Working on Aspire 8.x projects requires the workload. It's only Aspire 9.x projects that remove the requirement for the workload.

**Comment by mitchdenny** [comment] 2024-10-04 03:38
Closing as by design.

**Closed by mitchdenny** 2024-10-04 03:38 UTC
Labels: bug, area-acquisition, by-design
