### ISSUE TITLE
[WebToolsE2E][Aspire] After adding Aspire.StackExchange.Redis.OutputCaching and related code, the published project cannot be applied to the added code.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#4492] opened 2024-06-13 07:37 UTC
**REGRESSION INFO**: Also repro on Aspire 8.0.0

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.3 [35012.203.d17.10] (Includes Aspire 8.0.0)
3. Install Aspire 8.1.0-preview.1.24312.4
4. Apply NuGet Feeds
5. Install Docker Desktop
6. Install azd

**REPRO STEPS**
1. New > Project > .NET Aspire Starter Application > Enter a Project name of AspireRedis01 > .NET 8.0 > Uncheck Use Redis for caching > Create.
2. Right-click the AspireRedis01.AppHost project > Add > .NET Aspire package > install Aspire.Hosting.Redis with matched version
3. Open Program.cs of AspireRedis01.AppHost project, replace the following code:
```
var builder = DistributedApplication.CreateBuilder(args);

var redis = builder.AddRedis("cache");

var apiService = builder.AddProject<Projects.AspireRedis01_ApiService>("apiservice");

builder.AddProject<Projects.AspireRedis01_Web>("webfrontend")
   .WithExternalHttpEndpoints()
   .WithReference(apiService)
   .WithReference(redis);

builder.Build().Run();
```
4. Right-click the AspireRedis01.Web project > Add > .NET Aspire package > install Aspire.StackExchange.Redis.OutputCaching with matched version
5. Open Program.cs of AspireRedis01.Web project, add following code:
`builder.AddRedisOutputCache("cache"); `
6. Open Components/Pages/Home.razor, update with following codes:
```
@page "/" 
@attribute [OutputCache(Duration = 10)] 
<PageTitle>Home</PageTitle> 
<h1>Hello, world!</h1> 
Welcome to your new app on @DateTime.Now 
```
7. F5 with https, the current time displayed on the Home page is updated every ten seconds.
8. Right-click the AspireRedis01.AppHost > Publish > Azure Container Apps for .NET Aspire > next > Under 'AzDev Environment', select following settings > next > Publish
• Subscription name: WTE
• Location: East US
• Environment name: type your own name
9. After publishing, open the webfrontend page.

**ACTUAL**
Publish successfully, but the current time displayed on the Home page is not updated every ten seconds.
Every time refresh the home page, the current time will change.
![image](https://github.com/dotnet/aspire/assets/109339894/b3c3b140-eae5-49c1-8e3f-3c2d0110815f)

**EXPECTED**
The application will display the current time on the home page. Refresh the browser every few seconds to see the same page returned by output caching. After 10 seconds the cache expires and the page reloads with an updated time.

**Comment by mitchdenny** [comment] 2024-06-19 11:53
Looks like you might have forgotten to add the middleware? `app.UseOutputCache();`

See docs: https://learn.microsoft.com/en-us/dotnet/aspire/caching/stackexchange-redis-output-caching-component?tabs=dotnet-cli#example-usage

**Comment by mitchdenny** [comment] 2024-06-19 11:54
Can you confirm and if this solves the issue go ahead and close the issue. If not then we can take a closer look.

**Comment by v-reinawang** [comment] 2024-06-20 01:37
This doesn't solve the issue. 

After I created the project in the first step, the code `app.UseOutputCache();` already existed in the program.cs file of AspireRedis01.Web
![image](https://github.com/dotnet/aspire/assets/109339894/5e8b4677-cb7a-47b8-9f20-ab334de935dc)

**Comment by mitchdenny** [comment] 2024-07-26 01:41
I've just tried 8.1.0 and cannot reproduce this. It works locally and deploys fine (cache expires every 10 seconds and you get a new value).

**Closed by mitchdenny** 2024-07-26 01:42 UTC
Labels: bug, area-app-model

**Comment by v-reinawang** [comment] 2024-07-31 07:02
Verify that this issue is not reproduced in 8.1.0 and 8.1.1 preview version.
