### ISSUE TITLE
Volume for service

### ISSUE THREAD

**Issue by gurelsoycaner** [dotnet/aspire#6132] opened 2024-10-05 10:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,
I just need to store photos in my service inside a docker container to a VOLUME,
sample code;

var vipasx = builder.AddProject<Projects.VipasX_Api>("vipasx-api")
.WithVolume(name, value)
.WithMount(name, value)
.WithVolumeMount(name, value)
.WithExternalHttpEndpoints()
.WithReference(rabbitmq)
.WaitFor(rabbitmq)
.WithHealthCheck();

We can't volume and/or mount mostly to our service ?

PLS NEED SOME LITTLE ASSISTANCE.

### .NET Version info

V8

**Comment by davidfowl** [comment] 2024-10-05 11:07
Not possible today, dupe of https://github.com/dotnet/aspire/issues/4359

**Closed by davidfowl** 2024-10-05 11:07 UTC
Labels: bug
