### ISSUE TITLE
Allow Aspire Dashboard to be installed to a project as middleware

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/aspire#2181] opened 2024-02-11 20:58 UTC
### Summary
I would like to be add the aspire Dashboard to my project's middleware just like i do with Swashbuckle & Openapi rather than need a dedicated project or installing the dotnet tool

### Details
By having the dashboard as a middleware package we can reach a large audience of users ie users wanting to have a dashboard showing the health of their services, allow for https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks to stop development on their UI packages 

The standalone project should simply be a kestrel processing running the middleware.

### Notes
#2182 would result in renaming of existing package to help make this nice and clear for a user

**Comment by davidfowl** [comment] 2024-02-12 11:50
Dupe of https://github.com/dotnet/aspire/issues/846

**Closed by davidfowl** 2024-02-12 11:50 UTC
Labels: area-dashboard
