### ISSUE TITLE
Add support for enabling Full-Text Search in the SQL Server hosting integration

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#6550] opened 2024-10-29 20:31 UTC
Got a question about how to enable Full-Text Search in the SQL Server container added by the `AddSqlServer` hosting integration and it turns out it requires building a custom container. We should consider adding a new `WithFullTextSearch()` extension method to the SQL Server resource that does the needful.

See https://tedspence.com/a-sql-server-docker-container-with-full-text-search-a1b7c5fc308c

**Comment by joperezr** [comment] 2024-10-29 23:35
Closing as dupe of https://github.com/dotnet/aspire/issues/6550

**Closed by joperezr** 2024-10-29 23:35 UTC
Labels: area-integrations, sqlserver
