### ISSUE TITLE
Can't access project endpoint updating from preview v1 to preview v3

### ISSUE THREAD

**Issue by murh-lego** [dotnet/aspire#2226] opened 2024-02-14 13:45 UTC
Hi,

I have upgraded from v1 to v3, workloads, dotnet, vs and all.

# Setup that worked in v1

My Projects / Services override some addresses like below:
```
   "Kestrel": {
    "Endpoints": {
      "rest": {
        "Protocols": "Http1",
        "Url": "http://+:5000"
      },
      "grpc": {
        "Protocols": "Http2",
        "Url": "http://+:5001"
      }
    }
  }
 ```
 
 I also have only one launch profile defined:
 ```
   "API": {
    "commandName": "Project",
    "launchBrowser": false,
    "launchUrl": "swagger",
    "environmentVariables": {
      "ASPNETCORE_ENVIRONMENT": "Local"
    },
    "dotnetRunMessages": true,
    "applicationUrl": "http://localhost:5000"
  }
 ```
 
 After the upgrade to v3.
 I can't issue request to `http://localhost:5000/health` nor any request actually.
 The logs suggest service is up and running. 
 Aspire dashboard shows the `http://localhost:5000` it's just that when I issue requests to it, nothing really happens.
 
 For these aspire projects. Code actually didn't change at all. In aspire and in the services.
 So not much new things. I just can't issue request suddenly :S
 
 Any guidance here?
 
 <hr>

# Reproduction repository

https://github.com/murh-lego/aspire-v3-test

This is the setup where in v1 I would:
  - See [http://localhost:5000](http://localhost:5000) in aspire dashboard
  - Be able to issue requests and access swagger and so on
  
In the repro repository:
      - There's two applicationUrls in launch settings of the API
         - Configuring port 5617 that is different than 5000, makes stuff work on 5000, but aspire dashboard renders 5617
         - Configuring 5000 makes aspire dashboard correctly render, but I can't interact with my service anymore.
         
The rest is the same as before.

So I was only able to make it work by configuring a applicationUrl that is different than 5000 (as it was before).
However, I don't necessarily enjoy that because dashboard shows wrong ports then and so on.

I'd like to keep my appsettings and launch profiles of my services intact if possible 😄 Individually services run ok and as configured.

**Comment by murh-lego** [comment] 2024-02-14 14:35
I'll close till I have a better case and repro repository :D

**Comment by cisionmarkwalls** [comment] 2024-02-14 16:47
Did you update aspire? @DamianEdwards suggested that to me for other issues between 1 and 3 and it helped.

```
dotnet workload update
dotnet workload install aspire
```

**Comment by eduardobr** [comment] 2024-02-14 18:54
Same here. From what I isolated the mere existence of Kestrel.Endpoints in my appsettings now causes the issue - everything running fine except that my services are not accessible by host machine.

**Comment by murh-lego** [comment] 2024-02-14 19:07
> Did you update aspire? @DamianEdwards suggested that to me for other issues between 1 and 3 and it helped.
> 
> ```
> dotnet workload update
> dotnet workload install aspire
> ```

Yes

>I have upgraded from v1 to v3, workloads, dotnet, vs and all.

I run 17.10 preview VS

Workload list
![image](https://github.com/dotnet/aspire/assets/149667205/33824d9e-f895-4b5e-beee-faa8e2d2e64a)

**Comment by davidfowl** [comment] 2024-02-14 20:24
This is likely a regression to do with how proxies work. There's currently no way (https://github.com/dotnet/aspire/issues/1637) to avoid the proxy that gets created. So when you take control of what ports the application is listening on, it doesn't work.

**Comment by murh-lego** [comment] 2024-02-14 21:06
> This is likely a regression to do with how proxies work. There's currently no way (#1637) to avoid the proxy that gets created. So when you take control of what ports the application is listening on, it doesn't work.

Ok, had some hunch about that, nice to see the preview 4 milestone and the tag.

Thank you for great work !

**Comment by davidfowl** [comment] 2024-02-16 02:53
Gonna close this as a duplicate of https://github.com/dotnet/aspire/issues/1637

**Closed by davidfowl** 2024-02-16 02:53 UTC
Labels: bug, area-app-model
