### ISSUE TITLE
[WebToolsE2E][Aspire] Unable to run Aspire application when project name under orchestration includes underscore ( _ ) character 

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#2083] opened 2024-02-05 14:16 UTC
**REGRESSION INFO**: Works fine with Aspire 8.0.0-preview.2

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install latest VS 17.10 P1 build from d17.10 branch (Web workload with 8.0 SDK and runtime, 6.0 runtime and 7.0 runtime checked)
    - includes Aspire workload version 8.0.0-preview.3.24081.13
3. Apply NuGet Feeds

**REPRO STEPS**
1. New Project > Web App (MVC) > name it 'WebAppMvc_Anc80_NoAuth_1' > check 'Enlist in Aspire' checkbox during project creation
    - Project name should include underscore ( _ ) character
2. Build
3. Ctrl+F5

**ACTUAL**
Error in console window
```
Unhandled exception. System.ArgumentException: Resource name 'webappmvc_anc80_noauth_1' is invalid. Name must contain only ASCII letters, digits, and hyphens. (Parameter 'name')
   at Aspire.Hosting.ApplicationModel.ModelName.ValidateName(String target, String name) in /_/src/Aspire.Hosting/ApplicationModel/ModelName.cs:line 39
   at Aspire.Hosting.ApplicationModel.Resource..ctor(String name) in /_/src/Aspire.Hosting/ApplicationModel/Resource.cs:line 30
   at Aspire.Hosting.ApplicationModel.ProjectResource..ctor(String name) in /_/src/Aspire.Hosting/ApplicationModel/ProjectResource.cs:line 10
   at Aspire.Hosting.ProjectResourceBuilderExtensions.AddProject[TProject](IDistributedApplicationBuilder builder, String name) in /_/src/Aspire.Hosting/Extensions/ProjectResourceBuilderExtensions.cs:line 27
   at Program.<Main>$(String[] args) in C:\Users\balach\source\repos\WebAppMvc_Anc80_NoAuth_1\WebAppMvc_Anc80_NoAuth_1.AppHost\Program.cs:line 3

C:\Users\balach\source\repos\WebAppMvc_Anc80_NoAuth_1\WebAppMvc_Anc80_NoAuth_1.AppHost\bin\Debug\net8.0\WebAppMvc_Anc80_NoAuth_1.AppHost.exe (process 16408) exited with code -532462766.
```
![image](https://github.com/dotnet/aspire/assets/8246794/1116ff5d-87bc-4547-9df8-a6c5d2005307)

**EXPECTED**
Ctrl+F5 to work fine

**Comment by eerhardt** [comment] 2024-02-05 17:44
I believe this was an intentional change. See https://github.com/dotnet/aspire/pull/1712/.

cc @JamesNK

**Comment by balachir** [comment] 2024-02-05 19:20
@eerhardt thanks. Yeah, the design is mentioned here: https://github.com/dotnet/aspire/issues/1399#issuecomment-1858224006. I wonder if VS tooling should be smart and convert the names to use acceptable characters when creating the AppHost project. I'll open a new issue in VS with that suggestion.

**Comment by joperezr** [comment] 2024-02-05 20:14
@JamesNK can you share more about the reasoning behind the change as well as any requests we have for the VS Team about this so that we understand what needs to be done to fix the regression?

**Comment by JamesNK** [comment] 2024-02-05 22:42
Some characters have special meaning and using them breaks functionality. This change applies rules for allowed characters in resource and endpoint names.

Original issue: https://github.com/dotnet/aspire/issues/1399

**Comment by mitchdenny** [comment] 2024-02-05 22:59
We have the ability to override the service name by using a `AspireProjectMetadataTypeName` attribute. Example: https://github.com/dotnet/aspire/blob/9f37e5f6b461e4512f7be4b64b301486137762d7/tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj#L15

**Comment by eerhardt** [comment] 2024-02-06 00:17
A workaround here is to replace the underscores with dashes in the Resource name.

```diff
-builder.AddProject<Projects.WebAppMvc_Anc80_NoAuth_1>("webappmvc_anc80_noauth_1");
+builder.AddProject<Projects.WebAppMvc_Anc80_NoAuth_1>("webappmvc-anc80-noauth-1");
```

**Comment by JamesNK** [comment] 2024-02-06 00:20
Preview 3 fix: https://github.com/dotnet/aspire/pull/2093

Preview 4 fix will be to change invalid characters to dash when writing `AddProject` reference to Aspire host project, e.g.

```cs
builder.AddProject<Projects.WebAppMvc_Anc80_NoAuth_1>("webappmvc-anc80-noauth-1");
```

**Comment by JamesNK** [comment] 2024-02-06 03:04
Fix merged into release/8.0-preview3.

@balachir The VS change to modify the resource name is needed for P4. Either look at the code or get in contact with me about how to make the project name a safe Aspire resource name.

**Comment by v-sherryfan** [comment] 2024-02-06 10:24
Verified that this issue is not reproduced on 17.10.0 Preview 1.0 [34605.110.d17.10] + Aspire.ProjectTemplates.8.0.0-preview.3.24105.21.

**Comment by JamesNK** [comment] 2024-02-06 10:40
Follow up issue to track AddProject change for preview 4: https://github.com/dotnet/aspire/issues/2102

**Comment by mitchdenny** [comment] 2024-02-07 23:11
Need to test that ACA can accept dashes, and if not figure out how this impacts service discovery and how to workaround the issue.

**Closed** 2024-02-07 23:12 UTC
Labels: area-app-model, untriaged
