### ISSUE TITLE
Javascript error when changing theme in Aspire dashboard

### ISSUE THREAD

**Issue by lt-gerjan** [dotnet/aspire#1516] opened 2023-12-29 09:36 UTC
When I try to change my theme here:

![image](https://github.com/dotnet/aspire/assets/7427231/c3adfabb-c2f2-4077-a742-720f40609d23)

I am getting errors:
 
F12 devtools console:
![image](https://github.com/dotnet/aspire/assets/7427231/33ce2fd8-434b-48ef-81f9-13f4be2c144e)

Command line console:
![image](https://github.com/dotnet/aspire/assets/7427231/ae791f4e-441f-4890-b3ae-3a27ccbfe04d)

**Comment by leslierichardson95** [comment] 2024-02-06 23:07
Closing this issue since the issue can no longer be reproduced.

**Closed by leslierichardson95** 2024-02-06 23:07 UTC
Labels: area-dashboard, untriaged
