### ISSUE TITLE
Local vs Cloud deployment

### ISSUE THREAD

**Issue by gregpakes** [dotnet/aspire#1736] opened 2024-01-20 16:47 UTC
I think I must be confused about something.  I am interested in Aspire due to the Orchestration piece, particularly during development.

I love the single line orchestration to spin up a new container.  The issue is that I don't see how this translates to production.

For example, SQL Server.:

In AppHost, I have the following (taken from the examples):

 ``` c#
// if container fails to initialize, you need to allow the directory to be mounted in docker settings - File Sharing
var sql = builder.AddSqlServerContainer("sql",sqlpassword, 60143)
// Mount the init scripts directory into the container.
.WithVolumeMount("./sqlserverconfig", "/usr/config", VolumeMountType.Bind)
// Mount the SQL scripts directory into the container so that the init scripts run.
.WithVolumeMount("../aspire.ApiService/data/sqlserver", "/docker-entrypoint-initdb.d", VolumeMountType.Bind)
// This persists the sql data - but is a dev only setting - hmmm
.WithVolumeMount("./sqldata", "/var/opt/mssql/data", VolumeMountType.Bind)
// Run the custom entrypoint script on startup.
.WithArgs("/usr/config/entrypoint.sh")
.AddDatabase("sqldata");
```

This config has very specific config for a developer environment.  

In production, I want to use Azure SQL.   I don't see how I get from here to Azure SQL?

This is fantastic for the developer experience, but I'm failing to see the production mapping.  Am I missing something?

**Comment by mitchdenny** [comment] 2024-01-21 23:55
We are still working on the end to end, but our intention is that when you deploy an Aspire application that takes a dependency on SQL Server via the `AddSqlServer(...)` method that we will translate that to an Azure SQL Database resource automatically. We are working on some of the details like how do we provide a level of customization for that eventual resource which is deployed.

We've already got some of this working for existing resources - Azure Storage for example, when deployed via AZD will provision storage accounts and inject connection strings.

We are tracking issues over on the AZD side for the end to end for Azure-focused cloud deployments.

https://github.com/Azure/azure-dev/issues/3020

**Comment by davidfowl** [comment] 2024-01-28 03:26
Closing as dupe of https://github.com/dotnet/aspire/issues/1757

**Closed by davidfowl** 2024-01-28 03:26 UTC
Labels: area-app-model
