### ISSUE TITLE
Dashboard: Metrics: Need a table of values

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/aspire#352] opened 2023-10-17 21:17 UTC
Charts are pretty, they help you visualize changes over time. But they take work to interrogate out the individual values, especially if the deltas are small in relation the value.

What I want to be able to see is what values are being emitted by my code. So in addition to the chart, there should be a table of values.
Ideally it only adds a new row, when the values have changed from the previous row.
- This is not a log of each metric value exposed from the app - its still going through the aggregation.

So I want a table of values in addition to the graph.

**Comment by davidfowl** [comment] 2024-01-27 19:36
Are we doing this now? @adamint @JamesNK ?

**Comment by DamianEdwards** [comment] 2024-01-27 21:25
There's a PR I believe

**Comment by davidfowl** [comment] 2024-01-27 21:25
cc @kvenkatrajan

**Comment by adamint** [comment] 2024-01-29 21:34
Yes, this will be completed in #1755

**Comment by adamint** [comment] 2024-02-22 18:32
dupe of #1123

**Closed by adamint** 2024-02-22 18:32 UTC
Labels: area-dashboard
