### ISSUE TITLE
[WebToolsE2E][Aspire] When naming an aspire project with only lowercase characters, the build project will get a warning: "The type name 'xxx' only contains lower-cased ascii characters."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#1681] opened 2024-01-17 08:52 UTC
**REGRESSION INFO**: Also repro on Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [34516.225.main]
3. Install Aspire Preview 3 latest build 8.0.0-preview.3.24066.3
4. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web API > give any lower-case name such as "apicproj" > .NET 8.0 > check 'Enlist in Aspire Orchestration' > Create
2. Build solution

**NOTE**

- This issue reproduces on any aspire project, not witout aspire project.

**ACTUAL**

The type name 'apiproj' only contains lower-cased ascii characters. Such names may become reserved for the language.
![image](https://github.com/dotnet/aspire/assets/71361488/64b28b20-3763-4fe0-9c1e-067b096ef3ba)

**EXPECTED**

Building solution without any warning.

**Comment by mitchdenny** [comment] 2024-01-18 13:46
Can you try adding the following attribute to the <ProjectReference /> in the App Host:

```xml
<ProjectReference Include="path\to\apiproj.csproj" ServiceNameOverride="ApiProj" />
```

This is not really a bug, but I want to make sure the override mechanim allows people to suppress the warning. I don't think it is a bug because its probably a pretty fair warning by the compiler, and it showing up is a side effect of the way we generate types for referenced projects in the app host.

**Comment by balachir** [comment] 2024-01-22 17:34
@v-sherryfan can you try the workaround that Mitch mentioned above?

**Comment by v-sherryfan** [comment] 2024-01-23 06:36
@balachir @mitchdenny Try the above workaround and it will show other error as below.
![image](https://github.com/dotnet/aspire/assets/71361488/a316a506-bf22-40e4-a875-7167873975eb)

**Comment by mitchdenny** [comment] 2024-01-23 06:43
Can you share the contents of the api service csproj whilst you are experiencing the problem?

**Comment by v-sherryfan** [comment] 2024-01-23 06:50
@mitchdenny This is the content of the api service csproj.
![image](https://github.com/dotnet/aspire/assets/71361488/ec45ae0e-b988-4076-8150-a73a57c9cf63)

**Comment by mitchdenny** [comment] 2024-05-13 09:59
Closing as this does not repro anymore.

**Closed by mitchdenny** 2024-05-13 09:59 UTC
Labels: area-app-model

**Comment by v-sherryfan** [comment] 2024-05-21 07:03
@mitchdenny I still reproduce this issue, I try again above [workaround ](https://github.com/dotnet/aspire/issues/1681#issuecomment-1898512262)but it didn't make the warning go away. The expected result should be that the warning goes away, right? Please help to check it again.
![image](https://github.com/dotnet/aspire/assets/71361488/67eb2e7e-9628-4825-b815-58f8dd4f9d74)

**Comment by mitchdenny** [comment] 2024-05-21 07:40
Change ServiceNameOverride to AspireProjectMetadataTypeName. It has changed. Additionally the root of the problem is that the lowercase type name (apiproject) is what is causing the issue - this is not an Aspire specific issue. So make the name you choose something that is valid for a .NET type name.

**Comment by v-sherryfan** [comment] 2024-05-21 08:24
@mitchdenny If I create a normal web api project with lowercase type name, it works fine without any warning. The warning only appears if I enable "Enlist in Aspire Orchestration" when creating the project, I guess this might be caused by aspire, what do you think?
Also, do you mean to change it like this? If not, can you provide me with a sample? Thanks in advance.
![image](https://github.com/dotnet/aspire/assets/71361488/7756e6b0-89bd-449a-b4be-36366dab409a)

**Comment by v-sherryfan** [comment] 2024-05-21 08:35
@mitchdenny This doesn't seem to be working, could you help me see if what I'm doing in the screenshot above is correct?

**Comment by mitchdenny** [comment] 2024-05-21 08:39
Change the type name from apiproject to ApiProject

**Comment by mitchdenny** [comment] 2024-05-21 08:45
So. Now you need to change your code in the apphost Program.cs to match the new type name (the AddProject call).

**Comment by v-sherryfan** [comment] 2024-05-21 08:55
Yes, it works after changing code in the apphost Program.cs. I closed it as by design. Thank you very much for your patient explanation.
![image](https://github.com/dotnet/aspire/assets/71361488/094d24b6-2d51-44ad-90d7-1ade7862db6a)
