### ISSUE TITLE
Having multiple AddNpgsqlDbContext calls results in second and subsequent contexts using the wrong connection string.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#2096] opened 2024-02-06 02:00 UTC
In the following playground we initialize multiple Postgres databases for use with EF:

https://github.com/dotnet/aspire/tree/main/playground/PostgresEndToEnd

While debugging I noticed that the database was only being created in the first Postgres server. Upon further inspection it looks like all the various DbContext types that are being injected into the `/` route have the wrong connection string applied (except the first one).

This is probably a bug in the registration of the underlying Postgres connection in DI.

**Comment by mitchdenny** [comment] 2024-02-06 02:11
Looks like this impacts other Aspire EF components as well.

**Comment by eerhardt** [comment] 2024-02-06 14:18
This looks like a duplicate of https://github.com/npgsql/efcore.pg/issues/2891.

cc @roji

**Comment by roji** [comment] 2024-02-06 14:21
Yep, agree with @eerhardt that this look like a dup of https://github.com/npgsql/efcore.pg/issues/2891.

Can you please try creating the NpgsqlDataSource yourself, and then explicitly passing that to AddNpgsqlDbContext rather than having it implicitly taken from DI? That should work around the problem for now (and confirm that we're discussing the same bug).

**Comment by eerhardt** [comment] 2024-02-06 14:21
> Looks like this impacts other Aspire EF components as well.

I haven't seen this affect other EF components. Can you share a repro of it affecting a non-Npgsql EF component?

**Comment by eerhardt** [comment] 2024-02-06 14:45
> This looks like a duplicate of [npgsql/efcore.pg#2891](https://github.com/npgsql/efcore.pg/issues/2891).

Looking at @mitchdenny's fix in #2097, I don't think this is same issue. The problem is that we are injecting an `NpgsqlDataSource` into DI in order to work around https://github.com/npgsql/efcore.pg/issues/2821. However, when you try adding multiple Npgsql DbContexts, we keep overwriting the NpgsqlDataSource in DI, since they aren't "keyed".

@roji - is there another way we can work around this bug? (Or even get the underlying bug fixed?) I don't really like that we are registering `NpgsqlDataSource` in DI when users add Npgsql EF. Especially since users can start depending on that DI service being registered. With the fix in #2097, it is actually making a breaking change because if users were getting an `NpgsqlDataSource` from DI, their code would no longer work because it is now keyed on the DbContext type.

**Comment by mitchdenny** [comment] 2024-02-06 23:00
> > Looks like this impacts other Aspire EF components as well.
> 
> I haven't seen this affect other EF components. Can you share a repro of it affecting a non-Npgsql EF component?

This was my mistake. Only an issue in npgsql.

**Closed** 2024-02-07 02:11 UTC
Labels: area-components, untriaged
