### ISSUE TITLE
Blazor WASM not working with Latest Aspire Preview 3

### ISSUE THREAD

**Issue by aherrick** [dotnet/aspire#1284] opened 2023-12-07 23:26 UTC
#296 mentioned this would be fixed in Preview 2. I'm on Preview 3 and still seeing this error.

`There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'`

Minimal Repo:
[BlazorApp1.zip](https://github.com/dotnet/aspire/files/13606397/BlazorApp1.zip)

**Comment by JoschiZ** [comment] 2023-12-17 16:56
Are you certain, that you are on Aspire preview 3?
Would you run `dotnet workload list` in a cmd and validate that?
Because I don't think preview 2 is released yet, you may be confusing the Aspire preview with the VS preview version.

**Comment by aherrick** [comment] 2023-12-17 21:35
I'm on the daily bits:

![image](https://github.com/dotnet/aspire/assets/586671/b7ebb388-695f-4d10-9a17-709ead21c9b5)

**Comment by JoschiZ** [comment] 2023-12-25 15:37
Aspire Preview 2 officially dropped today and this seems to still be a problem.

**Comment by oguz687** [comment] 2024-01-27 02:45
This problem still going on, when will this problem be solved?

**Comment by davidfowl** [comment] 2024-01-27 22:00
cc @joperezr

**Comment by davidfowl** [comment] 2024-01-29 15:24
Blazor standalone is not supported. We might be able to make it work for development but not deployment (at least for the initial release).

**Comment by davidfowl** [comment] 2024-03-09 23:56
cc @vijayrkn I beleive later versions of VS will support Blazor WASM https://github.com/dotnet/aspire/issues/1418

**Comment by davidfowl** [comment] 2024-03-09 23:56
OR this might be a workload issue. @joperezr

**Comment by joperezr** [comment] 2024-03-11 21:23
Not sure I'm following what seems to be wrong  here. Original post is about Blazor wasm not working with Aspire, from the above it seems like this is expected, so not sure how that relates to the workload.

**Comment by Lindsay-Mathieson** [comment] 2024-05-26 05:36
Still getting this error with current latest - Aspire GA.

The Problem is with the Service defaults project, it uses ```<FrameworkReference Include="Microsoft.AspNetCore.App" />```, this pulls in ```Microsoft.AspNetCore.App``` which is not supported in webassembly.

You get things to build/run by removing the Service Defaults project reference from the web assembly app, but then you lose all the nice telemetry stuff (and service discovery?).

**Comment by davidfowl** [comment] 2024-05-26 16:17
What issues? Service discovery and dashboard telemetry doesn't work in WASM and that's not what this issue is about. I'll close this one, and we should open new issues with specific feature requests.

See https://github.com/dotnet/aspire/issues?q=is%3Aissue+is%3Aopen+blazor+wasm+

**Closed by davidfowl** 2024-05-26 16:17 UTC
Labels: area-tooling

**Comment by Lindsay-Mathieson** [comment] 2024-05-26 16:25
> What issues?

The one from the very first comment

`There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'`

**Comment by davidfowl** [comment] 2024-05-26 16:28
Ah I see, lets treat this one as a dupe of https://github.com/dotnet/aspire/issues/1536. There's much better information in there.
