### ISSUE TITLE
Unhelpful error message if DCP dependency check fails

### ISSUE THREAD

**Issue by karolz-ms** [dotnet/aspire#4691] opened 2024-06-27 00:37 UTC
If the dependency check that uses `dcp info` command fails, with `dcp` returning non-zero code, an exception is thrown. The way we process this exception here https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs#L105 cause all output of the `dcp` command to be discarded.

The result is the user only sees a message that says "dcp info returned non-zero exit code", which is not helpful:

![image](https://github.com/dotnet/aspire/assets/15271049/00aed75d-9c12-42ee-958e-c302ab745a1a)

We should instead include all the output from `dcp` in the log, so that the user is informed about why the dependency check failed.

**Comment by JamesNK** [comment] 2024-06-27 00:45
Have you considered having dcp return specific error codes for certain situations? For example, return error code X if Docker isn't healthy and then the host can check for known error codes and print a friendly error message. It would look better than an error type + message + stack trace

**Comment by karolz-ms** [comment] 2024-06-27 00:56
Agreed, I do not think we want the stack trace here. 

We could consider having specific error codes for common issues, but ultimately DCP should be able to tell the user what part of dependency check failed, and what the user might want to try to get themselves unblocked.

**Comment by radical** [comment] 2024-06-27 01:12
Some hosting tests fail randomly on CI with `Application orchestrator dependency check had an unexpected error System.TimeoutException: The operation has timed out.` but no other information in the log. This issue - https://github.com/dotnet/aspire/issues/4640 - would also benefit from getting the details in the log.

**Comment by davidfowl** [comment] 2024-06-27 02:38
Wait is this a dupe of https://github.com/dotnet/aspire/issues/4089?

**Comment by JamesNK** [comment] 2024-06-27 02:41
It was thought to be fixed. But I still got an unhelpful error message when testing locally.

**Comment by JamesNK** [comment] 2024-06-27 02:44
FYI, this is the result from dcp info:

> {"version":"0.5.4","commitHash":"a2453505df8d60a288a1fdb30004e11ca8854b22","buildTimestamp":"2024-06-20T22:49:08Z","containers":{"runtime":"docker","hostName":"host.docker.internal","installed":true,"running":false,"error":"Docker CLI timed out while checking status. Ensure Docker CLI is functioning correctly and try again."}}

Could it have been fixed in dcp but dcp wasn't yet updated on dotnet/aspire main?

**Comment by danegsta** [comment] 2024-06-27 03:42
@JamesNK was your Docker stuck in resource saver mode when you originally hit the exit code scenario? I’ve been trying to reproduce with various states of Docker installation/running states, but haven’t been able to get an exit code response yet.

**Comment by JamesNK** [comment] 2024-06-27 05:50
Yes, it was in resource saver mode. I had to restart my machine to make it healthy.

**Comment by davidfowl** [comment] 2024-06-27 05:54
I just did that!

**Comment by danegsta** [comment] 2024-06-27 16:22
Okay, my money is on us not explicitly handling a cancellation error somewhere and letting it bubble all the way up.

**Comment by danegsta** [comment] 2024-06-27 18:28
This looks to be a simple mismatch between timeouts; DCP has a 30 second timeout configured for Docker commands, while Aspire has a 25 second timeout on the info command. We're returning a non-zero exit code because Aspire kills the DCP info check before it completes.

**Comment by danegsta** [comment] 2024-06-27 18:56
I've got a DCP PR in progress to reduce our default timeout on the info command + add a config flag that Aspire can use to override the timeout. Implementing that flag in Aspire would have to wait for a future release though, since it won't be supported in the 8.0 DCP release.

**Comment by danegsta** [comment] 2024-06-28 16:21
An updated DCP build has been merged with info timeout changes that should fix the cause of this particular non-zero exit code, but it's also worth improving the timeout logic in Aspire to provide a better error message (we probably shouldn't be throwing an exception reporting that a process exited unexpectedly when we're the ones killing the process).

**Closed** 2024-07-08 18:23 UTC
Labels: area-orchestrator
