### ISSUE TITLE
Tests timing out on CI/Linux

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#2151] opened 2024-02-09 03:42 UTC
This is before the helix tests PR merged.

- [dc8fa331](https://github.com/dotnet/aspire/commit/dc8fa33195ef1f66b920206766b9224c4c3f19bd) - [build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=559515&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=2917e7a9-bb9d-585b-890e-1ad69b6f3f65)
- [063f11b7](https://github.com/dotnet/aspire/commit/063f11b76cf95e1efcc3cf272f972ac46abc7b26) - [build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=559391&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=22fea640-1099-5f32-ec5d-316ad83f359a)

Started happening since `Build playground projects in CI` but I don't see why it would be related.

cc @joperezr @eerhardt

**Comment by eerhardt** [comment] 2024-02-09 18:54
I believe this is a dupe of https://github.com/dotnet/aspire/issues/1167.

**Closed** 2024-02-26 21:50 UTC
Labels: area-engineering-systems, untriaged, testing ☑️
