### ISSUE TITLE
Allow restarting .NET projects without restarting all containers

### ISSUE THREAD

**Issue by hades200082** [dotnet/aspire#5460] opened 2024-08-27 15:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Some code changes in a project require a stop & restart of the project in order to test them when running locally.

This becomes cumbersome in Aspire because it involves stopping the apphost, waiting for all of the containers to spin down then starting the apphost again and waiting for everything to spin back up.

### Describe the solution you'd like

There are two things I see that could be useful here.

1. Allow selective restarting of .NET applications, keeping all the other containers and applications running.
2. Allow in-place rebuilding/restarting of the solution projects without spinning down/up the container services

I'd see this as akin to docker-compose where you can keep the composed services running and stop/start your app in Visual Studio/Rider/CLI as much as you like.

**Comment by davidfowl** [comment] 2024-09-07 16:31
Dupe of https://github.com/dotnet/aspire/issues/295 and https://github.com/dotnet/aspire/issues/923

**Closed by davidfowl** 2024-09-07 16:31 UTC
Labels: area-app-model, area-orchestrator, feature
