### ISSUE TITLE
[WebToolsE2E][Aspire][Mac] Failed to launch the dashboard when Using VS Code to Debug Aspire App: 'Time out while waiting for the dashboard to be responsive'.

### ISSUE THREAD

**Issue by v-gaolisa** [dotnet/aspire#2007] opened 2024-01-31 06:08 UTC
REGRESSION INFO: Not repro on Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

Clean machine: MacOS
Install VS Code[1.85.2]
Install C# Dev Kit[1.3.8]
Install SDK 8.0.200
Install Aspire Preview 3 latest build 8.0.0-preview.3.24080.10
Apply NuGet Feeds

**REPRO STEPS**

1. Create .NET Project > .NET Aspire Application > give a name > Create
2. Right-click xxx.AppHost name > Open In Integrated Terminal > dotnet run

**Note:**
This issue is very unstable on Windows machine.

**ACTUAL**
Run aspire project with error: 'Time out while waiting for the dashboard to be responsive'
![image](https://github.com/dotnet/aspire/assets/89128759/5c5b1c31-66f4-4562-8663-ffb04b87bd44)
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: Timed out after 00:01:00 while waiting for the dashboard to be responsive.
         at Aspire.Hosting.Dcp.ApplicationExecutor.WaitForHttpSuccessOrThrow(Uri url, TimeSpan timeout, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 307
         at Aspire.Hosting.Dcp.ApplicationExecutor.CheckDashboardAvailabilityAsync(String delimitedUrlList, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 263
         at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 239
         at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 92
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.AggregateException: One or more errors occurred. (Timed out after 00:01:00 while waiting for the dashboard to be responsive.)
---> Aspire.Hosting.DistributedApplicationException: Timed out after 00:01:00 while waiting for the dashboard to be responsive.
   at Aspire.Hosting.Dcp.ApplicationExecutor.WaitForHttpSuccessOrThrow(Uri url, TimeSpan timeout, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 307
   at Aspire.Hosting.Dcp.ApplicationExecutor.CheckDashboardAvailabilityAsync(String delimitedUrlList, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 263
   at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 239
   at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 92
   at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 132
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 153
   at Program.<Main>$(String[] args) in /Users/vs/lisa3/aspire1/aspire1.AppHost/Program.cs:line 3

**EXPECTED**
No error and warning shows with run the project.

**Comment by davidfowl** [comment] 2024-01-31 06:49
@mitchdenny we have so few logs now this is hard to debug 😄. We only print the URL if we can successfully hit the endpoint.

**Comment by davidfowl** [comment] 2024-01-31 06:54
@v-gaolisa I am using 8.0.0-preview.3.24080.8 and I don't see this issue.

**Comment by v-gaolisa** [comment] 2024-01-31 07:07
I am confused, and I can also repro this issue using latest 8.0.0-preview.3.24080.10, can you share your installed steps.

**Comment by davidfowl** [comment] 2024-01-31 07:56
I can reproduce this on MacOS

**Comment by davidfowl** [comment] 2024-01-31 08:17
OK I figured this out. It seems like the dashboard isn't an executable on MacOS:

![image](https://github.com/dotnet/aspire/assets/95136/b073b553-9171-42b1-b24a-522296119f1d)

Seems like we have a publishing/packaging issue here. 

Thoughts @danegsta @drewnoakes?

cc @joperezr

**Comment by drewnoakes** [comment] 2024-01-31 10:03
@mitchdenny in this case the dashboard would have failed to start. Could the `ApplicationExecutor` know that and bypass the one minute timeout, waiting for HTTP to come online?

**Comment by mitchdenny** [comment] 2024-01-31 10:18
I think if the dashboard is supposed to start and it doesn't then we should fail. So failure here is the correct response. Perhaps what is missing is diagnostics on WHY the dashboard failed to start. Perhaps we should dump the console logs if we reach timeout with the dashboard having spun up?

**Comment by mitchdenny** [comment] 2024-01-31 10:18
.... or if we detect a non zero exit code before timeout.

**Comment by drewnoakes** [comment] 2024-01-31 12:04
Agree it should fail. I meant that it could fail sooner, rather than delaying a minute.

**Comment by davidfowl** [comment] 2024-01-31 15:45
> Quickest fix is probably be to update the discovery attributes to point to the .dll instead, since there’s already logic to handle that case in the AppHost.

I was going to suggest that we do this on OSX but I know we went through all that effort to make it use the app host 😄.

> There’s a mechanism in workload packs by which you can declare a file as an executable on Unix or Linux and dotnet will run chmod +x on the specified files when installing the pack. We should have already been doing that, but obviously something isn’t working (either the config file is missing from the pack or the declared file path to the executable is wrong).

I haven't tried linux, supposedly this is broken there too?

**Comment by danegsta** [comment] 2024-01-31 16:21
It looks like we are properly marking Aspire.Dashboard as executable (in the sense that `ls -l` on the file shows the executable flag set), but we still didn't end up with a valid executable file. Things DO work fine on Linux (I installed on WSL and the file has the executable flag set, plus I can run the Dashboard executable successfully). This is likely either a build or possibly a signing issue with the Mac binary, but either way it's going to be more work to fix the executable for Mac than we likely want to do right now.

**Comment by danegsta** [comment] 2024-01-31 16:44
Did a bit more digging; my money is on this being a signing/notarization issue with the Mac binary in the workload pack, but launching the dll instead definitely works as a quick fix.

**Closed** 2024-01-31 19:39 UTC
Labels: area-tooling

**Comment by v-gaolisa** [comment] 2024-02-01 09:17
Verified today, this issue is not repro on  8.0.0-preview.3.24081.11.

**Comment by davidfowl** [comment] 2024-02-19 07:45
@mo3in do you see it with a new project create with preview3?

**Comment by mo3in** [comment] 2024-02-19 08:28
@davidfowl i created new project with aspire and there was not any problem, everything works fine.

but in my old project i migrate from preview.2 to preview.3, i take this error and in debug folder `Aspire.Dashboard.dll` not exist!

**Comment by mo3in** [comment] 2024-02-19 08:39
i replaced AppHost `launchSettings.json` with new project launchSetting, now its run and working!

**Comment by vskliam** [comment] 2024-04-12 10:51
Migrated from preview 3 to preview 4. Updated Visual Studio, updated workload. Got same issue - Timed out after 00:01:00 while waiting for the dashboard to be responsive.
Changing ports in launchsettings did not help.

**Comment by anikitsiuk** [comment] 2024-04-12 11:16
Try Preview 5, it's already available. I don't have this issue anymore

**Comment by bhogiraju** [comment] 2024-04-14 07:12
![image](https://github.com/dotnet/aspire/assets/169258/7bd9cc88-2a86-4a78-879f-1e40e63ac888)
i  am getting the error after upgrading. anyone have work around on this?

**Comment by davidfowl** [comment] 2024-04-14 07:13
What version of the aspire workload are you using? Run:

```
dotnet workload list
```

**Comment by bhogiraju** [comment] 2024-04-14 07:15
![image](https://github.com/dotnet/aspire/assets/169258/870595fb-a0b9-4f14-9c30-a8eeceee267b)

**Comment by davidfowl** [comment] 2024-04-14 07:18
And check the package version of Aspire.Hosting in the application you are running.

**Comment by bhogiraju** [comment] 2024-04-14 07:25
Aspire version: 8.0.0-preview.4.24156.9+692dc41a65da572a7df25d53a9f2880afe59fdd8

**Comment by davidfowl** [comment] 2024-04-14 07:28
Seems like you're using eshop, it's been updated to preview 5.

**Comment by bhogiraju** [comment] 2024-04-14 07:31
Yes you are correct, what would be next  work around?

**Comment by davidfowl** [comment] 2024-04-14 07:46
Update your eshop bits and you'll have the new version that uses preview 5.

**Comment by bhogiraju** [comment] 2024-04-14 10:12
but, while upgrading, identified many of them are deprecated packages.

**Comment by bhogiraju** [comment] 2024-04-14 12:54
Working as expected after upgrading all
