### ISSUE TITLE
[WebToolsE2E] [Unstable] When running aspire application, we sometimes see KubeConfigException : kubeconfig file not found when the host is trying to start up

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#2542] opened 2024-02-29 16:38 UTC
**REPRO STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 (includes Aspire 8.0 P3)
3. Open VS > New Aspire Starter Application > AspireStarterApp2 > Build and Ctrl+F5 > works fine
4. Update to VS 17.10 Preview 2 (includes Aspire 8.0 P4 version 8.0.0-preview.4.24128.4) + Apply feeds
5. Open VS > open AspireStarterApp2, build and Ctrl+F5 again

**ACTUAL**
Hosting failed to start - kubeconfig file not found
![image](https://github.com/dotnet/aspire/assets/8246794/a8379bd9-aac2-4a1d-b491-d6b756c6f5e2)

**Workaround**: Close the VS debug console window, build and ctrl+F5 again, and it works fine

**EXPECTED**
No error in VS debug console when we do Ctrl+F5

**Comment by balachir** [comment] 2024-02-29 16:42
@karolz-ms @davidfowl , I've run into this issue a couple of times this week. So I went ahead and filed an issue but the repro is unstable and hard to reproduce consistently. I set the milestone as preview 4 in case the cause is something obvious, but we can move it out to P5 if needed. The workaround is simply to run it again.

**Comment by davidfowl** [comment] 2024-02-29 22:07
I'll be in preview5 for sure.

**Comment by karolz-ms** [comment] 2024-03-02 00:37
This should be fixed (in Aspire P5) by https://github.com/dotnet/aspire/pull/2435  Please re-open if you still see this issue.

**Closed by karolz-ms** 2024-03-02 00:37 UTC
Labels: area-orchestrator, untriaged

**Comment by davidfowl** [comment] 2024-03-02 01:23
@karolz-ms is it?

**Comment by karolz-ms** [comment] 2024-03-02 03:32
@davidfowl I have good reasons to believe it did because I have finally realized what is causing this pattern:
1. older version of DCP --> works
2. install new version --> first run cannot reach DCP (timeout in `ExecuteWithRetry` which is part of Aspire.Hosting DCP client)
3. subsequent runs --> work

The answer is: this is caused by "advanced threat protection" antivirus software. On my dev machine it can take close to 10 seconds for the AV to scan new version of DCP binaries.

The old code in DCP hosting client had a timeout of 5 seconds. The PR bumps it up to 20 seconds. Only first ever ("arctic") run is affected.
