### ISSUE TITLE
Code Generation of Project References is broken locally.

### ISSUE THREAD

**Issue by StuFrankish** [dotnet/aspire#5560] opened 2024-09-05 19:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Generated code on build of the AspireHost project is generating invalid metadata files resulting in the build failing.

Aspire package references were updated to 8.2.0 requiring updates to the installed dotnet workload on the local machine.
After updates to the workloads and package references, the solution no longer builds.

For example - a project referenced as `var clientApplication = builder.AddProject<Projects.Client>(name: "clientapp");`
Has the following generated code on build;

```c#
// <auto-generated/>

  namespace Projects
[global::System.CodeDom.Compiler.GeneratedCode("Aspire.Hosting", null)]
  [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated code.")]
  [global::System.Diagnostics.DebuggerDisplay("Type = {GetType().Name,nq}, ProjectPath = {ProjectPath}")]
  public class Client : global::Aspire.Hosting.IProjectMetadata
  {
      public string ProjectPath => """D:\source\AspireForIdentityServer\AspireForIdentityServer.ParClient\Client.csproj"""
}
```
Error list indicates missing `;` and `}` characters in the file `Client.ProjectMetadata.g.cs`

This issue occurs with all referenced projects in multiple solutions.

This issue only appears to occur locally however, the build pipeline for Windows, Mac and Ubuntu in GitHub actions builds normally.

I've tried:
- Repairing Visual Studio 2022
- Repairing the installed dotnet workloads
- Installing the latest version of .NET (8.0.401)

### Expected Behavior

Generated code is generated correctly, without missing characters.

### Steps To Reproduce

Clone repo: https://github.com/StuFrankish/AspireForIdentityServer
Using Visual Studio 2022 (including preview)
Run a Clean & Rebuild

### Exceptions (if any)

```Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS1514	{ expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\Client.ProjectMetadata.g.cs	3	
Error (active)	CS1002	; expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\Client.ProjectMetadata.g.cs	9	
Error (active)	CS1513	} expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\Client.ProjectMetadata.g.cs	10	
Error (active)	CS1514	{ expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\IdentityServer.ProjectMetadata.g.cs	3	
Error (active)	CS1002	; expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\IdentityServer.ProjectMetadata.g.cs	9	
Error (active)	CS1513	} expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\IdentityServer.ProjectMetadata.g.cs	10	
Error (active)	CS1514	{ expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\WeatherApi.ProjectMetadata.g.cs	3	
Error (active)	CS1002	; expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\WeatherApi.ProjectMetadata.g.cs	9	
Error (active)	CS1513	} expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\WeatherApi.ProjectMetadata.g.cs	10	
Error (active)	CS1514	{ expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\_AppHost.ProjectMetadata.g.cs	3	
Error (active)	CS1002	; expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\_AppHost.ProjectMetadata.g.cs	10	
Error (active)	CS1513	} expected	AspireForIdentityServer.AppHost	D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Release\net8.0\Aspire\references\_AppHost.ProjectMetadata.g.cs	11	
```

### .NET Version info

```
.NET SDK:
 Version:           9.0.100-preview.7.24407.12
 Commit:            d672b8a045
 Workload version:  9.0.100-manifests.2aef0cee
 MSBuild version:   17.12.0-preview-24374-02+48e81c6f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.7.24407.12\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166
   Manifest Version:    35.0.0-preview.7.41/9.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.7\microsoft.net.sdk.android\35.0.0-preview.7.41\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166, VS 17.11.35222.181
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166
   Manifest Version:    17.5.9231-net9-p7/9.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.7\microsoft.net.sdk.ios\17.5.9231-net9-p7\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166
   Manifest Version:    17.5.9231-net9-p7/9.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.7\microsoft.net.sdk.maccatalyst\17.5.9231-net9-p7\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166
   Manifest Version:    9.0.0-preview.7.24407.4/9.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.7\microsoft.net.sdk.maui\9.0.0-preview.7.24407.4\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      9.0.0-preview.7.24405.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  8.0.108 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]
  8.0.401 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.7.24407.12 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24406.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24405.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24405.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by davidfowl** [comment] 2024-09-05 19:27
Hmm, when I open the solution it builds fine for me. I am on a newer SDK though.

**Comment by radical** [comment] 2024-09-05 19:32
Do you get the same error when building from command line? Could you please share the binlog from that? Make sure to do this with a clean repo.

**Comment by StuFrankish** [comment] 2024-09-05 19:38
I've completely removed the solution folder and cloned it clean.
Building from the command line results in the same errors;

```
PS D:\source\AspireForIdentityServer> dotnet build
Restore complete (1.8s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  AspireForIdentityServer.ServiceDefaults succeeded (2.0s) → AspireForIdentityServer.ServiceDefaults\bin\Debug\net8.0\AspireForIdentityServer.ServiceDefaults.dll
  WeatherApi succeeded with 1 warning(s) (1.1s) → AspireForIdentityServer.ApiResource\bin\Debug\net8.0\WeatherApi.dll
    D:\source\AspireForIdentityServer\AspireForIdentityServer.ApiResource\Controllers\WeatherForecastController.cs(68,32): warning CS8600: Converting null literal or possible null value to non-nullable type.
  Client succeeded with 1 warning(s) (2.6s) → AspireForIdentityServer.ParClient\bin\Debug\net8.0\Client.dll
    D:\source\AspireForIdentityServer\AspireForIdentityServer.ParClient\Dtos\WeatherForecastDto.cs(10,18): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
  IdentityServer succeeded (2.8s) → AspireForIdentityServer.IdentityServer\bin\Debug\net8.0\IdentityServer.dll
  AspireForIdentityServer.AppHost failed with 12 error(s) (0.4s)
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\_AppHost.ProjectMetadata.g.cs(3,21): error CS1514: { expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\WeatherApi.ProjectMetadata.g.cs(3,21): error CS1514: { expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\IdentityServer.ProjectMetadata.g.cs(3,21): error CS1514: { expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\Client.ProjectMetadata.g.cs(3,21): error CS1514: { expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\WeatherApi.ProjectMetadata.g.cs(9,129): error CS1002: ; expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\IdentityServer.ProjectMetadata.g.cs(9,136): error CS1002: ; expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\Client.ProjectMetadata.g.cs(9,123): error CS1002: ; expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\_AppHost.ProjectMetadata.g.cs(10,114): error CS1002: ; expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\WeatherApi.ProjectMetadata.g.cs(10,2): error CS1513: } expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\IdentityServer.ProjectMetadata.g.cs(10,2): error CS1513: } expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\Client.ProjectMetadata.g.cs(10,2): error CS1513: } expected
    D:\source\AspireForIdentityServer\AspireForIdentityServer.AppHost\obj\Debug\net8.0\Aspire\references\_AppHost.ProjectMetadata.g.cs(11,2): error CS1513: } expected

Build failed with 12 error(s) and 2 warning(s) in 7.4s
PS D:\source\AspireForIdentityServer>
```
The binlog as requested;
[log_file.zip](https://github.com/user-attachments/files/16899444/log_file.zip)

**Comment by radical** [comment] 2024-09-05 20:56
The binlog does show that the `;` are missing, but the the code in the nuget hasn't changed and shows up as such in the binlog also. Also, I'm unable to reproduce this locally.

Somehow the nuget you have is incorrect. Your copy of the targets file at `C:\Users\Stuart\.nuget\packages\aspire.hosting.apphost\8.2.0\build\Aspire.Hosting.AppHost.targets` has:

```xml
      <AspireProjectMetadataSource Update="@(AspireProjectMetadataSource)">
        <Source>
        <![CDATA[// <auto-generated/>

  namespace Projects;
```

Note the `;` at the end of `namespace Projects;`.

And the correct copy of `aspire.hosting.apphost/8.2.0/build/Aspire.Hosting.AppHost.targets` has:
```xml
      <AspireProjectMetadataSource Update="@(AspireProjectMetadataSource)">
        <Source>
        <![CDATA[// <auto-generated/>

namespace Projects%3B
```

.. which has `;` escaped as `%3B`, which is required so msbuild will not treat `;` as a separator.

Could you confirm that the targets file indeed has that? If so, I think clearing that nuget from the cache, and rebuilding again might help.

@joperezr any idea how this could happen?

**Comment by StuFrankish** [comment] 2024-09-05 21:26
> Could you confirm that the targets file indeed has that? If so, I think clearing that nuget from the cache, and rebuilding again might help.

I can confirm what you're seeing in the targets file.
I've cleared the `.nuget\packages` folder of all Aspire related packages, re-cloned the repo (using GitHub Desktop) and with a terminal from the root of the solution run a `dotnet build` and can see it has pulled the nuget packages and built successfully.

A bad nuget does explain why other Aspire solutions were also impacted despite not having changed either.
How bizarre 😐

A learning to take forward next time I think - clear the nuget cache before going with the nuclear option of uninstalling and re-installing everything else 🤣

I'm pretty happy that I can crack on as normal now, do you you want to leave the issue open or are you happy for me to close it?

**Comment by joperezr** [comment] 2024-09-05 21:31
Looking at your binlog and looking at the .targets files that are imported and here is what I'm seeing:

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/345640ed-1119-4eaa-a4b4-846c77c6841d">

As you can see, somehow your version doesn't have the semicolon escaped and instead has it unescaped (which is what @radical was suggesting above)

I bet that now that it is working for you you'll see something like this instead:

<img width="518" alt="image" src="https://github.com/user-attachments/assets/4363b1ce-a57a-42d5-8b30-e521a0c550c0">

Which is a screenshot of my local machine installation state. @StuFrankish by any chance did you happen to edit/modify that file in your NuGet cache at some point? If not, this is indeed bizarre and we should probably loop in NuGet/MSBuild folks if we see this again.

**Comment by StuFrankish** [comment] 2024-09-05 21:40
@joperezr - I tend not to go places I don't need to - deleting the Aspire nuget caches in aid of this issue is the first time I've gone into that folder at all.

**Comment by joperezr** [comment] 2024-09-05 21:43
> @joperezr - I tend not to go places I don't need to - deleting the Aspire nuget caches in aid of this issue is the first time I've gone into that folder at all.

makes sense, and that's a good practice 👍. Even when clearing NuGet cache locally, you can do so without you having to manually make any deletions that could potentially leave you in a torn state by simply running: `dotnet nuget locals all -c` This will clear all of your nuget cache safely.

Thanks again for your report, I will close this issue for now given your problem is solved, but we will definitely keep an eye on this as in the case it keeps on happening we will reach out to NuGet/MSBuild/VS for help. Thanks again and don't hesitate to ping us if you have any other questions/comments/concerns.

**Closed** 2024-09-05 21:44 UTC
Labels: area-app-model
