### ISSUE TITLE
Filtering on Structured logs page

### ISSUE THREAD

**Issue by smitpatel** [dotnet/aspire#848] opened 2023-11-15 19:06 UTC
![image](https://github.com/dotnet/aspire/assets/1528107/d0de1651-c847-4b6f-8862-7806a400292b)

There are never enough filters. I was looking at dashboard and Filter textbox allows filtering on message but Filters menu also does the same.
1. The UI is not entirely intuitive since there are multiple times filters used so confusing what refers to what.
2. Do we need so many filtering?

**Comment by DamianEdwards** [comment] 2023-11-21 20:21
Dupe of #896?

**Comment by samsp-msft** [comment] 2023-11-21 22:04
This was something which got copied across from my prototype with little updating. 
The infra enables filtering for any field in the records, not just the ones shown. You can have multiple and they AND together - its building a set of IQueryable expressions under the covers.
I wanted a UI on the row details dialog so that you can select a field/row and apply a filter to show records with that value.

**Comment by DamianEdwards** [comment] 2023-11-21 22:06
> I wanted a UI on the row details dialog so that you can select a field/row and apply a filter to show records with that value.

Yep, that's what #896 is about. I'll close this out as a dupe.

**Closed by DamianEdwards** 2023-11-21 22:06 UTC
Labels: area-dashboard
