### ISSUE TITLE
Epic: Aspire 8.0 work

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspire#1549] opened 2024-01-04 20:25 UTC
# Aspire first release scoping

Below are the set of features and scenarios in scope for the first Aspire release (built on .NET 8.0). 

## Aspire Resources and Components
 
**OSS**
- Postgres, MySql, SQLServer, Oracle, Mongo, Redis, Kafka, RabbitMQ

**Azure**
- Cosmos, Storage (Queues, Tables, Blobs), Service Bus, KeyVault, Open AI, AI Search, Azure Redis, Azure Postgres, Azure SQL

 **Dapr**
- State Store, PubSub
 
## Dashboard
- The aspire dashboard decoupling so it can be deployed in any environment
- Native support for the aspire dashboard support in ACA
 
## Deployment
- Making sure all supported azure resources and open-source resources can be deployed to azure via AZD
- Command line CI/CD scaffolding for github actions and azdo via AZD
- First class support for Azure Monitor when deployed to ACA
- Kubernetes Support provided by the community via [aspirate](https://github.com/prom3theu5/aspirational-manifests) (thank you @prom3theu5)
 
## Tooling
- VS deployment experience driven by azd 
- VS code experience for Aspire
- VS CI/DI scaffolding for for github actions and azdo powered by AZD
 
## Top requested end to end scenarios (dev to deploy)
- (p1) #1758 
- (p1) Ability to set `dotnet user-secrets` during dev time from AZD-set envvars (related: https://github.com/Azure/azure-dev/issues/3202) 
- (p2) Ability to customize azure resources as part of deployment. Our plan B on this is that we already have support for doing this via `azd infra synth`.
- Support for podman/docker in WSL
- Developing against a container locally and deploying using ACA addons 
- Developing against a container locally and deploying using an already provisioned resource
- Developing against a container locally and deploying a managed azure resource
- Ability to add azure resources not natively supported by aspire as part of deployment
- Ability to deploy the aspire dashboard into production
- Ability to send telemetry to Azure Monitor when deployed to ACA
- Ability to use aspire orchestration with multiple repositories

 
## Out of scope

- AWS Support (in discussion, there are various prototypes)
- Local Stack support (need to figure out how AWS and local stack are exposed)
- GCP Support
- AKS support (will work via aspirate tool)
- Azure Functions

**Comment by danmoseley** [comment] 2024-01-04 22:23
@eerhardt can you help clarify above which we are committed to doing for 8.0, vs which are stretch (open to contributions) vs no plan (remove from list?)?

**Comment by eerhardt** [comment] 2024-01-12 16:55
> @eerhardt can you help clarify above which we are committed to doing for 8.0, vs which are stretch (open to contributions) vs no plan (remove from list?)?

I've categorized the above components list into "Committed for 8.0" and "Future". FYI - @DamianEdwards

**Comment by theo-albers** [comment] 2024-01-25 22:18
No plans to target Azure App Service instead of containers?

**Comment by davidfowl** [comment] 2024-01-25 23:44
> No plans to target Azure App Service instead of containers?

No, not part of v1.

**Comment by WhitWaldo** [comment] 2024-01-26 23:52
It'd be great if you could target any other deployment environment than just ACA - I've been really enjoying a POC with Aspire the last couple of days, but my larger project makes use of Dapr and their Workflows functionality. The ACA team recently indicated that [they're holding off on supporting Workflows](https://github.com/microsoft/azure-container-apps/issues/762#issuecomment-1882089067) for the time being (presumably until after their scaling limitations have been remedied), but that may take months, perhaps more than a year, before it's remedied.

As I understand it, the ACA team only tends to support Dapr components in at least a beta state. The Workflow scaling issues are tentatively tied to a new distributed scheduler building block that isn't yet expected to be released to an alpha state for ~2 releases, but then Actors and Workflows will take a dependency on it. If the ACA team waits for the scheduler to achieve beta before allowing updates to any of the three systems, it may be well over a year before everything is stable enough for ACA to support the functionality despite being usable enough on a single-node scale.

Consequently, I've had to regrettably pivot towards using Dapr more in a Kubernetes environment where I'm free to deploy Dapr with all the functionality I want (stable or not). I really enjoy using developing with Aspire locally and would love to have as easy and experience deploying it to Kubernetes where it and Dapr "Just Work". 

Please consider supporting other non-ACA targets in the short-term roadmap so I and others wanting to use Workflows (again, keeping in mind the scale issues) can also enjoy the great benefits Aspire provides.

**Comment by davidfowl** [comment] 2024-01-26 23:59
In the short term, Kubernetes support will be provided by  [aspirate](https://github.com/prom3theu5/aspirational-manifests) for the first version. 

We’ll consider more options in a later version.

**Comment by danmoseley** [comment] 2024-01-27 01:05
@WhitWaldo Does https://github.com/prom3theu5/aspirational-manifests help at all.

**Comment by WhitWaldo** [comment] 2024-01-27 02:12
> @WhitWaldo Does https://github.com/prom3theu5/aspirational-manifests help at all.
> 
> Edit: I should refresh before commenting

It certainly does - thank you!

**Comment by bradygaster** [comment] 2024-01-31 07:03
Also, I removed this item, as it seemed like a dupe of the one we've associated with #1758. Whilst there are some scenarios in which a hard separation between provisioning prior to dev and the features we'll get from an `azd provision` prior to devving, we're going to optimize for the `azd provision` before devving approach for the short term. 

> Provisioning an azure resource to develop against

**Comment by danmoseley** [comment] 2024-04-29 03:53
@eerhardt shall we close this now? if there's any remaining, could go in a new epic?

**Comment by eerhardt** [comment] 2024-04-29 14:16
I'd be fine with closing this. Maybe it would make sense to close it when we release 8.0 GA?

**Comment by drewnoakes** [comment] 2024-06-17 05:10
Seems we can close this now.

**Closed** 2024-06-17 06:06 UTC
Labels: area-meta, Epic
