### ISSUE TITLE
Deployment: local vs azure with managed services

### ISSUE THREAD

**Issue by BoBiene** [dotnet/aspire#1680] opened 2024-01-17 08:08 UTC
Hi there,

I would like to use .NET Aspire for my project and I'm trying to accomplish the following:

Define all needed resources in AppHost like
- mongodb
- influxdb container
- etc.

In local dev environment on debugging it works fine containers are running and the required connection strings are injected to my services.

How can I now do the deployment to azure with azd and point to existing managed services?

- For the mongdb I want to use mongodb atlas and point to a connectionstring in a keyvault.
- When i run azd `azd provision` it creates a mongodb container in the azure environment 
    - i have tried to use conditions in the AppHost like `if (builder.Environment.IsDevelopment())` but it does not work.

**Comment by davidfowl** [comment] 2024-01-17 15:11
and doesn’t support this yet but we’re working through a design for this.

cc @mitchdenny @ellismg

**Comment by davidfowl** [comment] 2024-01-28 03:25
Closing as dupe of https://github.com/dotnet/aspire/issues/1757

**Closed by davidfowl** 2024-01-28 03:25 UTC
Labels: area-app-model, area-deployment, azure
