### ISSUE TITLE
[WebToolsE2E][Aspire] When running the aspire project, after going to the dashboard, I got a warning in cmd: Aspire.Hosting.DistributedApplication[0] Failed to get the dashboard logs.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#3650] opened 2024-04-12 10:30 UTC
**REGRESSION INFO:** Worked on Aspre 8.0 P5

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install latest released SDK 8.0.204
3. Install Aspire 8.0 P6 [8.0.0-preview.6.24211.5]
4. Apply dotnet-tools Feed

**REPRO STEPS**

1. Open CMD, creating an Aspire Starter App using following commands:
    ```
    dotnet new aspire-starter -o aspire7
    cd aspire7\aspire7.AppHost
    dotnet run
    ```
2. Manually go to url https://localhost:xxxx
3. Then go back to cmd you will see a warning: Aspire.Hosting.DistributedApplication[0] Failed to get the dashboard logs.

**ACTUAL**

Aspire.Hosting.DistributedApplication[0] Failed to get the dashboard logs.
![image](https://github.com/dotnet/aspire/assets/71361488/0a1cb433-9f6a-483f-a30f-a72cb5684f7d)

There are no warnings in the console logs
![image](https://github.com/dotnet/aspire/assets/71361488/991eb07f-d595-4815-bd38-a35172a14ceb)
![image](https://github.com/dotnet/aspire/assets/71361488/76a92003-e71a-4cb6-9610-deebc23df472)

**Note**

1. Running with http also reproduces it.
2. Not repro on normal web app.

**EXPECTED**

After going to the dashboard there are no warnings in cmd.

**Comment by balachir** [comment] 2024-04-12 11:49
@v-sherryfan this is a dupe of #3612. I'm closing this as it should be fixed now in release/8.0 branch with this PR https://github.com/dotnet/aspire/pull/3637. If you still see this when you validate on Monday, please let me know.

**Closed by balachir** 2024-04-12 11:49 UTC
Labels: area-dashboard
