### ISSUE TITLE
Mono Repo vs Poly Repo

### ISSUE THREAD

**Issue by michalsteyn** [dotnet/aspire#891] opened 2023-11-16 19:48 UTC
Using Aspire in a Mono Repo containing multiple (all) relevant microservices makes sense. 

In larger enterprise environments where poly repos are used (and owned) by different teams for various microservices, how should aspire be used in those situations?

We are currently using a combination of Docker Compose files that brings up an entire stack or Helm Charts that allow developers to use either just containers or spin up a more full fledged Kubernetes environment. 

In all those situations, it remains tricky to do local development and have the local microservice under development properly handle configuration and service discovery of the running stack. 

But it does make it easy to define the stack in a central space.

I'm curious what the Aspire team recommends in this regard.

**Comment by ZeBobo5** [comment] 2023-11-16 21:30
Why don't you use GIT submodules in your App Host?

**Comment by DamianEdwards** [comment] 2023-11-16 23:48
Dupe of #829

**Closed by DamianEdwards** 2023-11-16 23:48 UTC

**Comment by michalsteyn** [comment] 2023-11-16 23:49
@ZeBobo5, using GIT submodules effectively turns your repo back into a mono repo. The issue is the strong coupling between the service under development and the rest of the stack that provide the dependencies. 

For smaller stacks this works, but as a solution architecture grows, the need to manage services independently becomes much greater.
