### ISSUE TITLE
[WebToolsE2E][Aspire] The "Health checks" of cache in Resources remained expanded by default after hiding the details.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6756] opened 2024-11-21 09:54 UTC
**REFRESSION INFO**

1. Reproduce in Aspire 9.0.0

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2
2. Install SDK 9.0.100
3. Install latest Aspire 9.1.0-preview.1.24570.3
4. Install Docker/Podman

**REPRO STEPS**
1. Create Aspire Starter App with Redis 
`dotnet new aspire-starter --use-redis-cache -o Aspire1`
2. Run the project and navigate to aspire dashboard by clicking the link in CLI
`dotnet run`
3. Click the cache in Resources page
4.  Hide all the details for Resource, Endpoints, Volumes, Health Checks and Environment variables.
5. Navigate to other projects in Resources page and go back to cache

**ACTUAL**
The "Health Check" remained expanded by default after hiding the details.
![Image](https://github.com/user-attachments/assets/6e158316-4f06-4865-b2ea-2b97c1f34b62)

**EXPECTED**
The details for "Health Check" should remain hidden just like the other items after hiding it.

**Comment by joperezr** [comment] 2024-11-27 00:53
Thanks for the report. This is by design as that pane is keeping state regardless of the resource that you have selected. Closing as by design for now, and we can consider it if we get customer feedback on it.

**Closed by joperezr** 2024-11-27 00:53 UTC
Labels: area-dashboard
