### ISSUE TITLE
[WebToolsE2E][Aspire] Running an Aspire project, hovering the mouse over the type name does not display the full name.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3172] opened 2024-03-26 09:18 UTC
**REGRESSION INFO**: Repro on Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 3.0 [34725.203.main] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire 8.0 Preview 5 [8.0.0-preview.5.24175.9]
4. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > .NET Aspire Starter Application > named 'AspireApp1' > .NET 8.0 > Create
2. Build and F5

**ACTUAL**
In the dashboard, hovering the mouse over the type name does not display it in full.
![type2](https://github.com/dotnet/aspire/assets/109339894/eac243fe-1576-4c77-9962-7852ccdcccad)

**EXPECTED**
Hover the mouse over the type name to display the full name.
like this:
![image](https://github.com/dotnet/aspire/assets/109339894/9a5ac31e-b4bf-4911-88f9-29c16bf3860f)

**Comment by adamint** [comment] 2024-04-03 19:33
@v-reinawang can you close this as duplicate of #3176

**Comment by adamint** [comment] 2024-04-04 17:49
Duplicate of #3176, closing

**Closed by adamint** 2024-04-04 17:49 UTC
Labels: area-dashboard, a11y, A11ySev2
