### ISSUE TITLE
[WebToolsE2E][Aspire] When using Google Chrome and Firefox to run the Aspire project, you need to enter a token every time you run it.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3648] opened 2024-04-12 09:41 UTC
**REGRESSION INFO**: New feature on Aspire 8.0 preview 6

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 4 FB [34811.107.d17.10] (Includes Aspire 8.0.0-preview.5.24201.12)
3. Install Aspire 8.0 Preview 6 [8.0.0-preview.6.24211.5]
4. Apply NuGet Feeds
5. Install Google Chrome and Firefox

**REPRO STEPS**
1. New Project > .NET Aspire Starter Application > .NET 8.0 > Create
2. Use Google Chrome or Firefox to build and F5, enter token to log in
3. Close browser, then use Google or Firefox to F5

Note: This only happens in Google Chrome and Firefox, in the edge browser you only need to enter it once

**ACTUAL**
Every time you run the same project, you need to enter a token.
![image](https://github.com/dotnet/aspire/assets/109339894/d68a84b4-0d72-4998-ae2d-a9cb2c206957)

**EXPECTED**
Only needs to be entered once.

**Comment by mitchdenny** [comment] 2024-04-12 10:06
I think this is down to the actual token that is being generated. It seems if the token has a `+` symbol in it it is rightfully being interpretted as a space character within ASP.NET Core.

We need to change VS to not use base64 encoding for the token since it is not URL safe.

/cc @JamesNK  @BillHiebert

**Comment by BillHiebert** [comment] 2024-04-12 15:36
That change is already done and will be Visual Studio Preview5

**Comment by mitchdenny** [comment] 2024-04-13 06:09
Thanks @BillHiebert I was able to confirm this.

**Comment by v-reinawang** [comment] 2024-04-15 03:15
Open an AzDO bug 2032945 to track this issue.

**Comment by mitchdenny** [comment] 2024-04-15 09:49
@v-reinawang can you please provide an example of the console output for the AppHost when you execute `dotnet run`? I'm particularly interested in the value of the `t=` argument.

> NOTE: This token is only valid for the duration of your debug session, so provided you terminate your AppHost and Aspire.Dashboard process it won't be an issue to share it here.

**Comment by v-reinawang** [comment] 2024-04-16 01:33
@mitchdenny It looks like the token does not contain + / or = symbols
![image](https://github.com/dotnet/aspire/assets/109339894/e3742d97-5712-4181-b5f6-2e40a68c10fd)

**Comment by danmoseley** [comment] 2024-04-16 01:38
If it was the base 64 issue it would be odd if it consistently fails in chrome and consistently passes in Edge. @v-reinawang is that what you see?

**Comment by balachir** [comment] 2024-04-16 01:42
@v-reinawang you mentioned that you can reproduce using CLI as well. Can you open a new issue with the 'Command line' repro steps - i.e. with no VS involved in the Install Steps or Repro Steps?

**Comment by v-reinawang** [comment] 2024-04-16 02:04
@danmoseley Yes, you need to enter the token every time you run it on Chrome, but you only need to enter it the first time on Edge.

**Comment by v-reinawang** [comment] 2024-04-16 02:30
I opened a new issue [#3715](https://github.com/dotnet/aspire/issues/3715) with the 'Command line' repro steps.

**Comment by mitchdenny** [comment] 2024-04-16 03:12
I can't repro this with `8.0.0-preview5.24214.1`. Can you try that and let us know whether it is resolved for you. Be sure to make sure you delete your cookies via the developer tools to make sure the browser is in a clean slate.

**Comment by mitchdenny** [comment] 2024-04-16 03:28
Hrm actually I was testing with a newer version of VS (IntPreview). I can repro this with Preview.

**Comment by danmoseley** [comment] 2024-04-17 06:12
Can we close this as a duplicate of https://github.com/dotnet/aspire/issues/3648 @v-reinawang ? We are fixing https://github.com/dotnet/aspire/issues/3648 tonight.

**Comment by v-reinawang** [comment] 2024-04-17 08:04
@danmoseley Yes, this bug can be closed.

**Closed** 2024-04-17 08:13 UTC
Labels: area-dashboard, area-tooling
