### ISSUE TITLE
[WebToolsE2E][Aspire] Running the AspireWithDapr.sln fails with error:"Unhandled exception. System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#2335] opened 2024-02-21 09:07 UTC
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [latest build, includes Aspire 8.0.0-preview.3.24105.21 ]
3. Install Docker Desktop for Windows
4. Install Drap CLI

**REPRO STEPS**

1. Clone aspire-samples repo from main branch
2. Open samples\AspireWithDapr.sln
3. Build and F5

**ACTUAL:**
**F5**
![image](https://github.com/dotnet/aspire/assets/71361488/d6959c6e-1037-4251-9efa-9074c29905cb)

**Ctrl+F5**
Unhandled exception. System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType()
   at Microsoft.Extensions.DependencyInjection.DaprServiceCollectionExtensions.<>c.<AddDaprClient>b__0_0(ServiceDescriptor s)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Extensions.DependencyInjection.DaprServiceCollectionExtensions.AddDaprClient(IServiceCollection services, Action`1 configure)
   at Program.<Main>$(String[] args) in C:\Users\v-sherryfan\source\repos\aspire-samples\samples\AspireWithDapr\AspireWithDapr.Web\Program.cs:line 13
![image](https://github.com/dotnet/aspire/assets/71361488/cbfc12dd-688a-4998-a1dc-5419004707f3)

**EXPECTED**
Running without any errors

**Comment by eerhardt** [comment] 2024-02-23 20:43
Did this just get fixed with https://github.com/dapr/dotnet-sdk/pull/1238?

cc @philliphoff

**Comment by DamianEdwards** [comment] 2024-03-02 17:42
Dupe of dotnet/aspire-samples#133

**Closed by DamianEdwards** 2024-03-02 17:42 UTC
Labels: area-dapr, untriaged
