### ISSUE TITLE
Support dashboard running without server

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1556] opened 2024-01-05 05:30 UTC
Support the dashboard running without a server. Configured by environment variables/command line arguments.

**Comment by drewnoakes** [comment] 2024-01-25 22:19
This was addressed in https://github.com/dotnet/aspire/pull/1815.

**Comment by davidfowl** [comment] 2024-01-30 06:56
@drewnoakes  I can't get this to work. If I manually run the dashboard from the command line, I see a blank screen and a ton of log spew:

```
info: Aspire.Dashboard[0]
      Now listening on: http://localhost:18888
info: Aspire.Dashboard[0]
      OTLP server running at: http://localhost:18889
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\davifowl\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
warn: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16]
      The WebRootPath was not found: C:\dev\git\aspire\wwwroot. Static files may be unavailable.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/ - - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/ (/)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/ (/)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/ - 200 - text/html;+charset=utf-8 69.6190ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css - 404 0 - 1.5200ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:18888/_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.bundle.scp.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.bundle.scp.css - 404 0 - 0.1562ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:18888/_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.bundle.scp.css, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/Aspire.Dashboard.styles.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/Aspire.Dashboard.styles.css - 404 0 - 0.1637ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:18888/Aspire.Dashboard.styles.css, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/css/app.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/css/app.css - 404 0 - 1.3178ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:18888/css/app.css, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/_framework/blazor.web.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/js/app.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/js/app.js - 404 0 - 0.1654ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Blazor web static files'
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:18888/js/app.js, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/js/plotly-2.26.0.min.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/js/theme.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/js/theme.js - 404 0 - 0.0757ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:18888/js/theme.js, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/js/plotly-2.26.0.min.js - 404 0 - 0.0416ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:18888/js/plotly-2.26.0.min.js, Response status code: 404
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/blazor.web.js was not modified
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Blazor web static files'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/_framework/blazor.web.js - 304 - text/javascript 4.3828ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/_blazor/initializers - - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Microsoft.AspNetCore.Routing.RouteEndpoint'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Microsoft.AspNetCore.Routing.RouteEndpoint'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/_blazor/initializers - 200 - application/json;+charset=utf-8 4.7124ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:18888/_blazor/negotiate?negotiateVersion=1 - - 0
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Microsoft.AspNetCore.Routing.RouteEndpoint'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Microsoft.AspNetCore.Routing.RouteEndpoint'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:18888/_blazor/negotiate?negotiateVersion=1 - 200 316 application/json 5.6722ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:18888/_blazor?id=_aBlKepMwY_CPtHcBKGsaw - - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Microsoft.AspNetCore.Routing.RouteEndpoint'
info: Aspire.Dashboard.Model.DashboardClient[0]
      DOTNET_RESOURCE_SERVICE_ENDPOINT_URL is not specified. Dashboard client services are unavailable.
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: DashboardClient is disabled. Check the IsEnabled property before calling this.
      System.InvalidOperationException: DashboardClient is disabled. Check the IsEnabled property before calling this.
         at Aspire.Dashboard.Model.DashboardClient.EnsureInitialized() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 135
         at Aspire.Dashboard.Model.DashboardClient.Aspire.Dashboard.Model.IDashboardClient.get_WhenConnected() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 301
         at Aspire.Dashboard.Components.ApplicationName.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/ApplicationName.razor.cs:line 29
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'iPposi130ZYphk3iBHyQ4kpa5EiBN1wPdoUSG0Vv3TY'.
      System.InvalidOperationException: DashboardClient is disabled. Check the IsEnabled property before calling this.
         at Aspire.Dashboard.Model.DashboardClient.EnsureInitialized() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 135
         at Aspire.Dashboard.Model.DashboardClient.Aspire.Dashboard.Model.IDashboardClient.get_WhenConnected() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 301
         at Aspire.Dashboard.Components.ApplicationName.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/ApplicationName.razor.cs:line 29
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot access a disposed object.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'iPposi130ZYphk3iBHyQ4kpa5EiBN1wPdoUSG0Vv3TY'.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Microsoft.AspNetCore.Routing.RouteEndpoint'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:18888/_blazor?id=_aBlKepMwY_CPtHcBKGsaw - 101 - - 154.4256ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:18888/_blazor/disconnect - multipart/form-data;+boundary=----WebKitFormBoundary1kv7UdlCdnag7WIV 359
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Microsoft.AspNetCore.Routing.RouteEndpoint'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Microsoft.AspNetCore.Routing.RouteEndpoint'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:18888/_blazor/disconnect - 200 0 - 7.7146ms
```

**Comment by davidfowl** [comment] 2024-01-30 07:01
OR maybe this was by design for preview 3? The intent was to allow the OTLP sever to work so the resources view shouldn't be visible, but the others should be.

**Comment by davidfowl** [comment] 2024-01-30 07:02
We should also disable the ASP.NET Core logs by default when you run standalone. They are noisy.

**Comment by davidfowl** [comment] 2024-01-30 07:07
Hmm, running with resource server shows me this:

<img width="1200" alt="image" src="https://github.com/dotnet/aspire/assets/95136/9961b0e5-a7e1-4bfb-a80c-f721b875bd4b">

I'm not sure if something broke this or if running the executable like this is untested.

**Comment by davidfowl** [comment] 2024-01-30 07:08
Static web assets are broken maybe?

Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:18888/_content/Microsoft.FluentUI.AspNetCore.Components/Components/Search/FluentSearch.razor.js, Response status code: 404

**Comment by davidfowl** [comment] 2024-01-30 07:11
OK I figured it out. If the working directory isn't set to executable folder then it breaks static content. I'm going to close this and open a preview 4 issue.

**Comment by davidfowl** [comment] 2024-02-07 08:12
Reopening this because we want the dashboard to work and render when there's no resource server.

**Comment by davidfowl** [comment] 2024-02-07 08:13
Putting it in p4

**Comment by JamesNK** [comment] 2024-02-07 08:29
Broken because WhenConnected task attempts to create a connection and that errors when there is no resource service. See https://github.com/dotnet/dotnet-docker/issues/5164#issuecomment-1931485840

Regression probably happened here: https://github.com/dotnet/aspire/pull/1814

Using the dashboard without a resource server isn't something we do in playground environments. It's important there is a smoke test in CI that this scenario works to prevent regressions.

**Comment by davidfowl** [comment] 2024-02-07 08:32
Lets also add a playground scenario just for this.

**Closed** 2024-02-13 03:37 UTC
Labels: area-dashboard, untriaged

**Comment by StephenCleary** [comment] 2024-02-14 04:36
Has this been fixed? I'm pulling the nightly Docker container (`"Image": "sha256:38bcbe7d883d694226cb13e459a54ce9caa49b12931d49f711ac8e42aa214b3d"`) and exporting from OTEL Collector to :18889 (deliberately not setting `DOTNET_RESOURCE_SERVICE_ENDPOINT_URL`), and when I access the Aspire dashboard, I get a blank page with these Docker logs:

```
2024-02-13 23:30:11 info: Aspire.Dashboard[0]
2024-02-13 23:30:11       Now listening on: http://0.0.0.0:18888
2024-02-13 23:30:11 info: Aspire.Dashboard[0]
2024-02-13 23:30:11       OTLP server running at: http://0.0.0.0:18889
2024-02-13 23:30:11 warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
2024-02-13 23:30:11       Storing keys in a directory '/home/app/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
2024-02-13 23:30:11 warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
2024-02-13 23:30:11       No XML encryptor configured. Key {2bb7478b-10ee-45ec-a995-e2c5075301e3} may be persisted to storage in unencrypted form.
2024-02-13 23:31:05 fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
2024-02-13 23:31:05       An exception was thrown while deserializing the token.
2024-02-13 23:31:05       Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
2024-02-13 23:31:05        ---> System.Security.Cryptography.CryptographicException: The key {0bf15c23-64fc-4686-bc01-b55ee03a8a8f} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
2024-02-13 23:31:05          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
2024-02-13 23:31:05          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
2024-02-13 23:31:05          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
2024-02-13 23:31:05          --- End of inner exception stack trace ---
2024-02-13 23:31:05          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
2024-02-13 23:31:05          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
2024-02-13 23:31:06 info: Aspire.Dashboard.Model.DashboardClient[0]
2024-02-13 23:31:06       DOTNET_RESOURCE_SERVICE_ENDPOINT_URL is not specified. Dashboard client services are unavailable.
2024-02-13 23:31:06 warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
2024-02-13 23:31:06       Unhandled exception rendering component: DashboardClient is disabled. Check the IsEnabled property before calling this.
2024-02-13 23:31:06       System.InvalidOperationException: DashboardClient is disabled. Check the IsEnabled property before calling this.
2024-02-13 23:31:06          at Aspire.Dashboard.Model.DashboardClient.EnsureInitialized() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 135
2024-02-13 23:31:06          at Aspire.Dashboard.Model.DashboardClient.Aspire.Dashboard.Model.IDashboardClient.get_WhenConnected() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 301
2024-02-13 23:31:06          at Aspire.Dashboard.Components.ApplicationName.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/ApplicationName.razor.cs:line 29
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
2024-02-13 23:31:06 fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
2024-02-13 23:31:06       Unhandled exception in circuit 'R_WZxLAb1Q7ACZbnakOLIjC7p6m9Vhn9x7JU-9TY3aw'.
2024-02-13 23:31:06       System.InvalidOperationException: DashboardClient is disabled. Check the IsEnabled property before calling this.
2024-02-13 23:31:06          at Aspire.Dashboard.Model.DashboardClient.EnsureInitialized() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 135
2024-02-13 23:31:06          at Aspire.Dashboard.Model.DashboardClient.Aspire.Dashboard.Model.IDashboardClient.get_WhenConnected() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 301
2024-02-13 23:31:06          at Aspire.Dashboard.Components.ApplicationName.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/ApplicationName.razor.cs:line 29
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
2024-02-13 23:31:06 warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
2024-02-13 23:31:06       Unhandled exception rendering component: Cannot access a disposed object.
2024-02-13 23:31:06       System.ObjectDisposedException: Cannot access a disposed object.
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
2024-02-13 23:31:06 fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
2024-02-13 23:31:06       Unhandled exception in circuit 'R_WZxLAb1Q7ACZbnakOLIjC7p6m9Vhn9x7JU-9TY3aw'.
2024-02-13 23:31:06       System.ObjectDisposedException: Cannot access a disposed object.
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by JamesNK** [comment] 2024-02-14 05:55
```
2024-02-13 23:31:06 fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
2024-02-13 23:31:06       Unhandled exception in circuit 'R_WZxLAb1Q7ACZbnakOLIjC7p6m9Vhn9x7JU-9TY3aw'.
2024-02-13 23:31:06       System.InvalidOperationException: DashboardClient is disabled. Check the IsEnabled property before calling this.
2024-02-13 23:31:06          at Aspire.Dashboard.Model.DashboardClient.EnsureInitialized() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 135
2024-02-13 23:31:06          at Aspire.Dashboard.Model.DashboardClient.Aspire.Dashboard.Model.IDashboardClient.get_WhenConnected() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 301
2024-02-13 23:31:06          at Aspire.Dashboard.Components.ApplicationName.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/ApplicationName.razor.cs:line 29
2024-02-13 23:31:06          at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```
This was fixed in https://github.com/dotnet/aspire/pull/2199. Whatever is in docker hasn't gotten the latest changes.

**Comment by StephenCleary** [comment] 2024-02-14 15:24
Indeed, it seems like the "nightly" Docker image isn't being built nightly.

Here's a one-line (Windows pwsh) repro FWIW:

```
docker pull mcr.microsoft.com/dotnet/nightly/aspire-dashboard && start http://localhost:18888 && docker run --rm -it -p 18888:18888 mcr.microsoft.com/dotnet/nightly/aspire-dashboard
```

**Comment by StephenCleary** [comment] 2024-02-14 15:35
Sorry, I posted the image sha above instead of the repository digest. The repository digest without the #2199 fix is:

```
mcr.microsoft.com/dotnet/nightly/aspire-dashboard@sha256:da20e4236c0224e7ca180620b65f522f22e6e77908a73f0d5fbeca717f13a5fb
```

And this is still `latest` as of this post.

**Comment by StephenCleary** [comment] 2024-02-16 21:58
Can confirm, this is working now! 🎉
