### ISSUE TITLE
libicu missing in aspire-dashboard:8.0.0-preview.5

### ISSUE THREAD

**Issue by paolofulgoni** [dotnet/aspire#2764] opened 2024-03-10 15:14 UTC
Hi team,

I'm getting this error when running the `aspire-dashboard:8.0.0-preview.5` image with `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0`:

```
Process terminated. Couldn't find a valid ICU package installed on the system.
Please install libicu (or icu-libs) using your package manager and try again.
Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support
```

Note that running the container with no globalization support (i.e. not setting `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0`) will cause this error instead (which seems related to https://github.com/dotnet/aspire/pull/2192):
```
2024-03-10 16:13:52 Unhandled exception. System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
2024-03-10 16:13:52 en is an invalid culture identifier.
2024-03-10 16:13:52    at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
2024-03-10 16:13:52    at Microsoft.AspNetCore.Builder.RequestLocalizationOptions.AddSupportedCultures(String[] cultures)
2024-03-10 16:13:52    at Aspire.Dashboard.DashboardWebApplication..ctor(Action`1 configureBuilder) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 125
2024-03-10 16:13:52    at Program.<Main>$(String[] args) in /_/src/Aspire.Dashboard/Program.cs:line 7
```

**Comment by adamint** [comment] 2024-03-10 15:49
Assigning to myself to investigate

**Comment by adamint** [comment] 2024-03-10 16:09
@paolofulgoni what platform are you running this on?

**Comment by davidfowl** [comment] 2024-03-10 16:58
@adamint I'm assuiming this is a container base image problem?

**Comment by paolofulgoni** [comment] 2024-03-10 17:57
Yes, the errors are logged by the container, not from my local environment, so something missing in the image.
Also, ideally, I shouldn't have to set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` via an env var.
Thanks for investigating!

**Comment by StephenCleary** [comment] 2024-03-10 18:45
I'm seeing the same thing; just pulled `mcr.microsoft.com/dotnet/nightly/aspire-dashboard` (latest) and started the container, and I'm seeing the second error described in this issue (`System.Globalization.CultureNotFoundException` for `en`).

**Comment by davidfowl** [comment] 2024-03-11 04:22
I'm assuming this is a container base image problem. We have several images to choose from varying in sizes and features.

cc @MichaelSimons

**Comment by MichaelSimons** [comment] 2024-03-11 15:50
@joperezr and @lbussell - this looks related to https://github.com/dotnet/dotnet-docker/pull/5248 and should be caught by https://github.com/dotnet/dotnet-docker/issues/5156 once implemented.

**Comment by joperezr** [comment] 2024-03-19 21:08
Seems like this was fixed by https://github.com/dotnet/dotnet-docker/pull/5276?

@paolofulgoni can you try pulling again and see if the issue is resolved for you?

**Comment by lbussell** [comment] 2024-03-19 21:15
> Seems like this was fixed by https://github.com/dotnet/dotnet-docker/pull/5276?

Yes, should be fixed, I just checked with the latest image. I forgot to come back and update this issue. Please feel free to close this if anyone else can validate it.

Related: https://github.com/dotnet/dotnet-docker/issues/5258

**Comment by joperezr** [comment] 2024-03-19 22:31
Great, thanks @lbussell . Closing this for now. @paolofulgoni feel free to reopen if you still repro.

**Closed by joperezr** 2024-03-19 22:31 UTC
Labels: area-dashboard

**Comment by paolofulgoni** [comment] 2024-03-20 12:11
I confirm this is fixed, thanks!
