### ISSUE TITLE
[Dashboard] Larger text values cut off. Enable easier ways to inspect values.

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/aspire#4174] opened 2024-05-14 14:37 UTC
When inspecting traces, there are cases where the text in the value fields is too large to fit on the display.

![image](https://github.com/dotnet/aspire/assets/46974588/ac34ed26-5add-4acf-8671-4e516008aa9e)

Currently, there's two ways I can inspect the entire value. 

1. Hover over the value which displays all of the text. 
2. Copy the value and paste it somewhere else like notepad.

I'd like to be able to have a pop-up / modal display that allows me to inspect the full text values without having to leave the dashboard.

**Comment by samsp-msft** [comment] 2024-07-02 21:47
Duplicate of #3388

**Closed by samsp-msft** 2024-07-02 21:47 UTC
Labels: area-dashboard
