### ISSUE TITLE
Support filtering traces by request path

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#1416] opened 2023-12-15 15:35 UTC
### Discussed in https://github.com/dotnet/aspire/discussions/1390

<div type='discussions-op-text'>

<sup>Originally posted by **Kralizek** December 14, 2023</sup>
My ASP.NET Core app with Razor Pages emits traces for static content. Is it possible to specify paths that should be ignored?

I also get traces for requests originated by the AWS SSM configuration provider.

Ideally, I'd love the traces to be less noisy:
- only user initiated
- avoid static content

Some screenshots:

<img width="546" alt="image" src="https://github.com/dotnet/aspire/assets/2458439/7f2fe80a-6b00-4e3e-a3b0-dcffae4ac6e5">

<img width="853" alt="image" src="https://github.com/dotnet/aspire/assets/2458439/5836d6dd-cc07-431c-ad7f-2a53b02a0800">

<img width="339" alt="image" src="https://github.com/dotnet/aspire/assets/2458439/98585b47-7adc-4f86-ad83-9356964a8b75">

</div>

**Comment by davidfowl** [comment] 2023-12-15 15:43
Shouldn't this be a generic filter based on span properties?

**Comment by DamianEdwards** [comment] 2023-12-15 15:50
> Shouldn't this be a generic filter based on span properties?

Maybe, but exposing a first-class UI ability to filter by incoming request path built on top of a generic filter would likely be useful.

**Comment by davidfowl** [comment] 2023-12-15 15:56
I don't think we should do that. These are acitivites, not requests.

**Comment by DamianEdwards** [comment] 2023-12-15 15:58
Yes understood. What is the span-centric way of describing what's being shown? Is it just the display name or is the dashboard special-casing different span types and extracting specific info. for display here?

**Comment by davidfowl** [comment] 2023-12-15 16:28
I think the span name for requests happens to be the same as the path but we want filtering based on span attributes:

<img width="1687" alt="image" src="https://github.com/dotnet/aspire/assets/95136/79c95f8f-f8a0-408a-bc95-1ab4fa3e4c09">

**Comment by samsp-msft** [comment] 2024-02-06 22:46
Are you asking to filter the requests in the UI, or suppress them being sent based on the type of the request. The latter is possible though the OTEL APIs to create a sampler that can work at the head or tail level.

https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/tail-based-sampling-span-level

**Comment by davidfowl** [comment] 2024-02-07 03:41
Filter in the UI

**Comment by JamesNK** [comment] 2024-09-17 03:04
Duplicate of https://github.com/dotnet/aspire/issues/1416

Traces should support filtering by attributes, which would include a url attribute on requests.

**Closed by JamesNK** 2024-09-17 03:04 UTC
Labels: area-dashboard, area-telemetry, enhancement, dashboard-filter-sort
