### ISSUE TITLE
Inconsistency in Configuration Schema for CosmosDb Component compared to other azure components

### ISSUE THREAD

**Issue by pantanuj** [dotnet/aspire#1394] opened 2023-12-14 17:27 UTC
[Configuration Schema for Blob](https://github.com/dotnet/aspire/blob/main/src/Components/Aspire.Azure.Storage.Blobs/ConfigurationSchema.json) follows the convention **Aspire : Azure: Storage : Blobs**, which is consistent with other Azure components like Key Vault (Aspire:Azure:Security:KeyVault) and Service Bus (Aspire:Azure:Messaging:ServiceBus).

[Schema for Cosmos DB](https://github.com/dotnet/aspire/blob/main/src/Components/Aspire.Microsoft.Azure.Cosmos/ConfigurationSchema.json) (and SQL) seems to follow a different pattern: **Aspire : Microsoft : Azure : Cosmos**.

**Comment by eerhardt** [comment] 2023-12-14 23:59
The configuration section follows the package name of the component. The package name of the component follows the underlying client library name. Since the CosmosDB library name is https://www.nuget.org/packages/Microsoft.Azure.Cosmos, the Aspire component is named `Aspire.Microsoft.Azure.Cosmos`. Then the config section follows that name.

**Comment by Pilchie** [comment] 2023-12-15 00:04
Right - Azure Cosmos DB doesn't have a Track 2 Azure SDK that follows the typical conventions, so a bunch of our naming predates the consistency of those packages.  I think this is by design.

**Comment by eerhardt** [comment] 2023-12-15 00:23
@Pilchie - do you imagine a "Track 2 Azure SDK" for Cosmos DB that follows the naming?

If so, this is why I want the Aspire components to follow the underlying client library naming. That way we don't take `Microsoft.Azure.Cosmos` and call the Aspire component `Aspire.Azure.Cosmos` and block us from ever making an Aspire component for a `Azure.Cosmos` library if it ever came.

**Comment by Pilchie** [comment] 2023-12-15 18:16
Yes, a track 2 SDK is on our roadmap, though still a ways out.  I agree that we should artificially break the pattern and use `Aspire.Azure.Cosmos` now (though I expect our Track 2 SDK would actually be `Azure.Data.Cosmos`, not just `Azure.Cosmos`.

**Comment by eerhardt** [comment] 2023-12-15 18:54
Thanks, @Pilchie.

Closing as this is by design.

**Closed by eerhardt** 2023-12-15 18:54 UTC
Labels: area-components, untriaged
