### ISSUE TITLE
[WebToolsE2E][Aspire][Tracking] Support for aspire 9.0 templates should be added.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#5568] opened 2024-09-06 02:47 UTC
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install latest .NET SDK RC1
3. Install Aspire 9.0 P4
4. Add dotnet8 feed

**REPRO STEPS**

1. Open Command Prompt, create an aspire 9.0 project fails
    `dotnet new aspire -f net9.0`

**ACTUAL**
Error: Invalid option(s):
-f net9.0
   'net9.0' is not a valid value for -f. The possible values are:
      net8.0   - Target net8.0
![image](https://github.com/user-attachments/assets/020a5f7d-6377-495c-bc3f-8fffdda94855)
![image](https://github.com/user-attachments/assets/1c5c299e-8af0-4f54-9ea2-836ec6ffb04a)

**VS Side:**
No target .NET 9.0 for Aspire App
![image](https://github.com/user-attachments/assets/62346740-b81f-4b24-a25e-be9845a99aab)

No 'Enlist in .net aspire orchestration'checkbox for web app
![image](https://github.com/user-attachments/assets/532100d2-1e57-4cb3-b084-11084a12aaa2)

**EXPECTED**
Similar to net8.0, aspire 9.0 templates can also be successfully created.
![image](https://github.com/user-attachments/assets/000e2085-cf82-450d-a4e9-5175789a2ba1)

**Comment by balachir** [comment] 2024-09-23 18:21
@joperezr will this scenario be fixed when issue https://github.com/dotnet/aspire/issues/5447 is resolved? Or is this a separate issue?

**Comment by joperezr** [comment] 2024-09-24 18:00
It will, this is a dupe of that so I'll go ahead and close it as such. Dupe of #5447

**Closed by joperezr** 2024-09-24 18:00 UTC
Labels: bug, area-templates
