### ISSUE TITLE
Hitting `ctrl+c` on `dotnet run` does not stop the various processes started by the AppHost - on Linux, and macOS

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#2027] opened 2024-02-01 00:13 UTC
I'm trying the `aspire-starter` template, and running it with `dotnet run`. The problem that I'm having is that if I hit
`ctrl+c` then the various processes started by the apphost are not being stopped.

for example:
`/Users/ankj/dev/a2/artifacts/bin/dotnet-latest/sdk/8.0.101/DotnetTools/dotnet-watch/8.0.101-servicing.23580.21/tools/net8.0/any/dotnet-watch.dll --non-interactive --no-hot-reload --project /private/tmp/asp0/asp0.ApiService/asp0.ApiService.csproj --no-launch-profile`

This is with `main` at c719174d0b59c6787dd3c9f0f6cf37f2c77bafa7 .

Note that this didn't seem to be an issue on windows, only on linux (codespaces to be specific), and macos.

cc @joperezr @mitchdenny @dbreshears

**Comment by danegsta** [comment] 2024-02-01 00:58
It seems as though `dotnet watch` doesn't clean up its forked processes when we terminate it (and the orphaned child processes don't respond to SIGTERM, which is what we send for termination by default). One workaround we could consider is sending SIGINT in addition to SIGTERM when cleaning up the process tree, since the `dotnet watch` child processes to respond to SIGINT.

**Comment by mitchdenny** [comment] 2024-02-05 00:44
That explains something I saw the other day.

**Comment by mitchdenny** [comment] 2024-10-08 05:32
@radical I don't seem to be able to reproduce this (on GitHub Codespaces). The processes do get torn down but it does seem to take a bit longer for them to do so.

**Comment by davidfowl** [comment] 2024-11-01 09:40
cc @tmat

**Comment by davidfowl** [comment] 2024-11-01 09:40
dotnet watch is being re-designed to work with aspire. That work is happening in 9.0.200 SDK which is not shipping with .NET 9. This has been fixed in that branch.

You can see the work items for watch and aspire here https://github.com/dotnet/sdk/issues?q=is%3Aissue%20label%3AAspire%20

**Closed by davidfowl** 2024-11-01 09:40 UTC
Labels: area-tooling, untriaged
