### ISSUE TITLE
stack trace for k8s.Autorest.HttpOperationException on ctrl-c

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspire#603] opened 2023-10-31 20:22 UTC
Using 8.0.0-preview.1.23530.4 on Windows. Started things up on cmd line but quickly hit Ctrl-C. 

I'm guessing we should be catching this exception and displaying it as an error message, not a stack trace?
```
Could not stop service 'identity-api': k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'NotFound', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services.usvc-dev.developer.microsoft.com \"identity-api\" not found","reason":"NotFound","details":{"name":"identity-api","group":"usvc-dev.developer.microsoft.com","kind":"services"},"code":404}

   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.DeleteClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, String name, V1DeleteOptions body, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, String dryRun, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Aspire.Hosting.Dcp.KubernetesService.<>c__DisplayClass12_0`1.<<DeleteAsync>b__0>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 109
--- End of stack trace from previous location ---
   at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 198
   at Aspire.Hosting.Dcp.ApplicationExecutor.DeleteResourcesAsync[RT](String resourceName, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 637
```

related scenario
https://github.com/dotnet/aspire/issues/73
https://github.com/dotnet/aspire/issues/222

**Comment by danegsta** [comment] 2023-11-22 22:21
This looks to be related to the KubernetsClient retry logic running into the hard timeout on the shutdown cancellation token. We may want to specifically exclude OperationCanceledException from this logging, as it's not really an error condition.

**Comment by dbreshears** [comment] 2023-11-27 17:35
Moving to app-model based on David's comments

**Comment by stbau04** [comment] 2024-01-05 17:01
@danegsta i think the exception described in this issue is a `k8s.Autorest.HttpOperationException`. The `System.OperationCanceledException ` that is logged from the same location is described in https://github.com/dotnet/aspire/issues/73 (but i could not reproduce it as mentioned in https://github.com/dotnet/aspire/issues/73#issuecomment-1878979455). Should the `k8s.Autorest.HttpOperationException` also be excluded from the logging? Or should we just provide a simpler log message or something?

**Comment by stbau04** [comment] 2024-01-06 19:32
Maybe not the right place here, but sometimes an `System.OperationCanceledException` is  thrown on ctrl-c, not in the DeleteResourcesAsync but the CreateResourcesAsync. In the CreateResourcesAsync there is currently no exception handling at all, should we catch and ignore that exception in this location?

```
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.CancellationToken.ThrowIfCancellationRequested()
         at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
         at k8s.AbstractKubernetes.ICustomObjectsOperations_CreateClusterCustomObjectWithHttpMessagesAsync[T](Object body, String group, String version, String plural, String dryRun, String fieldManager, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
         at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.CreateClusterCustomObjectWithHttpMessagesAsync(Object body, String group, String version, String plural, String dryRun, String fieldManager, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
         at Aspire.Hosting.Dcp.KubernetesService.<>c__DisplayClass10_0`1.<<CreateAsync>b__0>d.MoveNext() in C:\Users\Stephan\Documents\Projekte\aspire\aspire-stbau04\src\Aspire.Hosting\Dcp\KubernetesService.cs:line 51
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in C:\Users\Stephan\Documents\Projekte\aspire\aspire-stbau04\src\Aspire.Hosting\Dcp\KubernetesService.cs:line 198
         at Aspire.Hosting.Dcp.ApplicationExecutor.CreateResourcesAsync[RT](CancellationToken cancellationToken) in C:\Users\Stephan\Documents\Projekte\aspire\aspire-stbau04\src\Aspire.Hosting\Dcp\ApplicationExecutor.cs:line 667
         at Aspire.Hosting.Dcp.ApplicationExecutor.CreateServicesAsync(CancellationToken cancellationToken) in C:\Users\Stephan\Documents\Projekte\aspire\aspire-stbau04\src\Aspire.Hosting\Dcp\ApplicationExecutor.cs:line 114
         at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in C:\Users\Stephan\Documents\Projekte\aspire\aspire-stbau04\src\Aspire.Hosting\Dcp\ApplicationExecutor.cs:line 78
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in C:\Users\Stephan\Documents\Projekte\aspire\aspire-stbau04\src\Aspire.Hosting\Dcp\DcpHostService.cs:line 65
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

**Comment by mitchdenny** [comment] 2024-01-08 01:47
It'll be the same cause and the same fix.

**Comment by mitchdenny** [comment] 2024-01-11 06:43
Should be fixed now.

**Closed by mitchdenny** 2024-01-11 06:43 UTC
Labels: help wanted, area-app-model
