### ISSUE TITLE
[WebToolsE2E][Aspire] Sign out the vm account and reconnect to vm using the same account, then open the project that has verified the token authentication or create a new aspire project and F5, it still pops up dashboard token authentication again.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#3646] opened 2024-04-12 09:30 UTC
**REGRESSION INFO:** This is a new feature on Aspire 8.0 P6

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 4 FB
3. Install Aspire 8.0 P6 [8.0.0-preview.6.24211.5]
4. Apply dotnet-tools Feed

**REPRO STEPS**

1. Create an Aspire Starter App > give a name 'AspireApp1' > Create
2. F5 with https > popup dashboard token authentication > Input token and Log in
3. Sign out vm's account, then connect to vm again using same account
4. Open the authenticated 'AspireApp1' project, then F5 with https, it will popup dashboard token authentication again

**ACTUAL**

Sign out the vm account and reconnect to vm using the same account, then open the project that has verified the token authentication or create a new aspire project and F5, it still pops up dashboard token authentication again

**Note**

- Disconnecting server and reconnecting vm works fine.

**EXPECTED**

There is no need to reconnect vm with token authentication again.

**Comment by balachir** [comment] 2024-04-12 14:01
@v-sherryfan after you sign out and sign back in, can you check the status of your localhost cookie as shown [here](https://github.com/dotnet/aspire/issues/3613#issuecomment-2051800148)? I gave your scenario a try as well and I can see that the localhost cookie gets deleted when I sign out and sign back in. I believe that's the reason it's asking you for the token again. So, I believe that this is By Design.

Including @JamesNK to confirm

**Comment by JamesNK** [comment] 2024-04-12 14:22
I think this might be a bug. I thought we were persisting the cookie across sesssions, but it turns out sessions is no longer ended when closing the browser. A session ends when logging out of a machine.

**Closed** 2024-04-17 01:36 UTC
Labels: area-dashboard
