### ISSUE TITLE
Dashboard shows 2 instances (one 'hidden') and does not show endpoints...

### ISSUE THREAD

**Issue by DynConcepts** [dotnet/aspire#3341] opened 2024-04-02 17:09 UTC
![image](https://github.com/dotnet/aspire/assets/9969889/6f9110c4-9db4-45e0-be6a-b45a680da2bf)

for reference... Other projects show similar:
        url = https://github.com/dotnet/eShop.git
        refs/heads/aspire-preview5
        119a04c800ab5b1953cef85d7b5f5be8e715a3d6
        
   With preview 4, the dashboard seemed right.... not sure how to debug this....

**Comment by mitchdenny** [comment] 2024-04-05 01:34
Hi @DynConcepts I'm not able to reproduce this. What specific build of Preview 5 are you running?

**Comment by davidfowl** [comment] 2024-04-05 02:20
It would happen if you were on the p4 workload but running the p5 branch. The old dashboard have no idea what a hidden resource is.

**Comment by mitchdenny** [comment] 2024-04-05 02:45
Ah OK its a torn state. @DynConcepts can you look at installing the latest workload using these instructions?

https://github.com/dotnet/aspire/blob/main/docs/using-latest-daily.md#optional-using-scripts-to-install-the-latest-net-aspire-build-from-release-branches

**Comment by DynConcepts** [comment] 2024-04-05 10:12
@davidfowl , @mitchdenny  -- Thanks - I was beginning to suspect as much. But it raises a question in my mind... how would one go about having two projects [different working directories - so it could be different branches of the same project] that are intended for different versions of a workload???
It seems (and I really hope I am wrong) that things may resemble the old days of "dll hell" rather than situations like NuGet packages where one can have many different versions concurrently (provided separate folders of course).
note: I have spent more time supporting legacy clients (remember MFC :) ) and 4.x Framework projects and am doing major catchup on the state of .NET....

**Comment by mitchdenny** [comment] 2024-04-05 11:19
You will be able to have 8.0 and 9.0 of aspire installed side by side.

**Comment by DynConcepts** [comment] 2024-04-05 11:23
> You will be able to have 8.0 and 9.0 of aspire installed side by side.

Thanks... that is at least something... (but I am still unsure about this whole workload concept/implementation - beyond aspire itself; that is certainly a discussion for a different venue - and I did just reach out to you. Thanks in advance. David.)

**Comment by davidfowl** [comment] 2024-04-05 16:07
Workloads are adding a feature called workload sets that allow pinning the workload version in global.json

**Comment by adityamandaleeka** [comment] 2024-04-05 22:41
Hmm, I'm seeing this now despite being on the preview5 workload.

<img width="1480" alt="image" src="https://github.com/dotnet/aspire/assets/219224/cb3bf378-a721-4516-8dad-426ad974933c">

**Comment by adityamandaleeka** [comment] 2024-04-05 22:55
Hmm... something is holding onto state. I commented out all the services in the app host and incrementally added them back hoping to find one that causes problems, but didn't run into the problem again. The hidden nodes are gone now.

**Comment by davidfowl** [comment] 2024-04-17 05:42
This happens when the preview 4 dashboard is being used. I think we've seen this enough times to understand that this is the problem. Each time we've seen this it seems like the p4 dashboard has been launched and a clean rebuild makes it work. There's some seems to be some stale state going on with respect to what version of the workload the apphost ends up pulling in via msbuild.

**Comment by leslierichardson95** [comment] 2024-04-23 21:47
Closing since this seems to be a preview-specific issue.  Will be resolved by GA.

**Closed by leslierichardson95** 2024-04-23 21:47 UTC
Labels: area-dashboard
