### ISSUE TITLE
hosting mode does not support Fluent Web App

### ISSUE THREAD

**Issue by Hkarata** [dotnet/aspire#1278] opened 2023-12-07 11:31 UTC
when adding a fluent web app as a project in Aspire , you get this error

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Method not found: 'Void Microsoft.FluentUI.AspNetCore.Components.LibraryConfiguration.set_HostingModel(Microsoft.FluentUI.AspNetCore.Components.BlazorHostingModel)'.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run()
   at Program.<Main>$(String[] args) in C:\Users\Heri\Documents\ASP.NET\CloudLearn\AspireApp1\AspireApp1.AppHost\Program.cs:line 5

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
MissingMethodException: Method not found: 'Void Microsoft.FluentUI.AspNetCore.Components.LibraryConfiguration.set_HostingModel(Microsoft.FluentUI.AspNetCore.Components.BlazorHostingModel)'.

**Comment by DamianEdwards** [comment] 2023-12-07 15:38
This is likely caused by conflicts between the version of Fluent UI used in the project added and the AppHost project. This should get resolved automatically as part of #1003

**Comment by mitchdenny** [comment] 2024-01-11 06:50
Flagged for offsite as its related to P2P references.

**Comment by mitchdenny** [comment] 2024-01-22 22:20
@eerhardt I am assigning this to you because I think your changes will actually resolve this.

**Closed** 2024-01-24 21:55 UTC
Labels: area-app-model, area-app-model-offsite
