### ISSUE TITLE
Unable to consistently see "Copy to clipboard" button on Safari

### ISSUE THREAD

**Issue by adamint** [dotnet/aspire#2648] opened 2024-03-05 17:32 UTC
See attached recording, works in Edge but the copy button rarely appears in Safari.

https://github.com/dotnet/aspire/assets/20359921/ba1cf434-ead5-4892-8899-1a5690b8a379

**Comment by adamint** [comment] 2024-03-05 17:33
cc @kvenkatrajan

**Comment by kvenkatrajan** [comment] 2024-03-05 17:35
Duplicate of #1724

**Closed by kvenkatrajan** 2024-03-05 17:35 UTC
Labels: bug, area-dashboard, untriaged, safari
