### ISSUE TITLE
[WebToolsE2E][Aspire]After adding Azure Key Vault to AppHost project, F5 failed with exception:  One or more errors occurred. (No output for vaultUri)

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2674] opened 2024-03-06 09:59 UTC
**REGRESSION INFO**: Works fine on Aspire 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34701.141.d17.10] (Includes Aspire 8.0.0-preview.4.24129.7)
3. Apply NuGet Feeds
4. Install Docker Desktop

**REPRO STEPS**
1. New Project > ASP.NET Core Empty project > name it AspireKeyVault02 > .NET 8.0 > check 'Enlist in Aspire Orchestration' > create
2. Open appsettings.json of AppHost project, add connection string:
```
"ConnectionStrings": {
  "secretConnectionName": "https://<vault_account_name>.vault.azure.net/"
}
```
3. In your AppHost project, install the Aspire Azure Hosting package and save the file
5. Open Program.cs of AspireKeyVault02.AppHost project, add following codes:
```
	var keyVault = builder.AddAzureKeyVault("[secretConnectionName]");
        var myService = builder.AddProject<Projects.AspireKeyVault02>("aspirekeyvault02")
                       .WithReference(keyVault);
```
6. Build and F5

**ACTUAL**
It shows an exception during F5
![image](https://github.com/dotnet/aspire/assets/82028229/b35caf52-2ad1-4c30-aeed-2018fe62f641)
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (No output for vaultUri)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run()
   at Program.<Main>$(String[] args) in C:\Users\v-cazhang\source\repos\WebApplication2\WebApplication2.AppHost\Program.cs:line 11

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: No output for vaultUri

**EXPECTED**
F5 successfully.
![image](https://github.com/dotnet/aspire/assets/82028229/2b004016-6ad5-4ce6-97d3-cff672621205)

**Comment by davidfowl** [comment] 2024-03-06 15:14
This pattern no longer works for azure resources. Dupe of https://github.com/dotnet/aspire/issues/2395

**Comment by balachir** [comment] 2024-03-06 15:26
@davidfowl the [README file](https://www.nuget.org/packages/Aspire.Azure.Security.KeyVault/8.0.0-preview.3.24105.21#readme-body-tab) for Aspire.Azure.Security.KeyVault component recommends this `builder.AddAzureKeyVault` pattern in the AppHost section of the README. Will the README also get updated as part of the fix for https://github.com/dotnet/aspire/issues/2395 or should we open a separate issue to fix the README for P5?

**Comment by davidfowl** [comment] 2024-03-06 15:32
That's a good point. It applies to the application and to the app host as well, but not the AddKeyVault method. @eerhardt What do you think? Do we update the readmes to add this "use existing keyvault vs new keyvault" scenario?

**Comment by eerhardt** [comment] 2024-03-06 16:05
If the READMEs no longer point to valid information/scenarios we need to update them. What is the recommended pattern here for someone who isn't using AzureProvisioning? (or do we start recommend using AzureProvisioning in the READMEs?)

**Comment by davidfowl** [comment] 2024-03-06 16:38
This: https://github.com/dotnet/aspire/issues/2395#issuecomment-1965864077

**Comment by eerhardt** [comment] 2024-04-22 22:58
This has been completed with https://github.com/dotnet/aspire/pull/3793.

**Closed by eerhardt** 2024-04-22 22:58 UTC
Labels: area-components
