### ISSUE TITLE
Cosmos DB OpenTelemetry traces aren't emitted

### ISSUE THREAD

**Issue by jcocchi** [dotnet/aspire#5711] opened 2024-09-14 00:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Even when enabled via settings, OpenTelemetry traces aren't emitted from the Cosmos DB SDK unless the experimental switch is also enabled manually in the `Extensions.cs` `ConfigureOpenTelemetry()` function. 

Experimental switch to add when tracing is enabled:
`AppContext.SetSwitch("Azure.Experimental.EnableActivitySource", true);`

### Expected Behavior

Enabling OpenTelemetry via settings should also set the experimental switch. Expected behavior is one trace per client operation with the custom attributes described [here](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/sdk-observability?tabs=dotnet#trace-attributes).

Image of expected traces in Aspire Dashboard
![image](https://github.com/user-attachments/assets/7c4479fb-50ba-47f4-84c7-cf22b2e53a68)

### Steps To Reproduce

1. Add reference to `Aspire.Microsoft.Azure.Cosmos`
2. Enable tracing when setting up Cosmos client
```csharp
builder.AddAzureCosmosClient("cosmos",
    settings =>
    {
        settings.DisableTracing = false;
    });
```

No traces are emitted from Cosmos.

1. Add below switch to `Extensions.cs` `ConfigureOpenTelemetry()` function
`AppContext.SetSwitch("Azure.Experimental.EnableActivitySource", true);`

Traces are now emitted as expected.

**Comment by eerhardt** [comment] 2024-09-16 16:37
I assume that the Cosmos client library's tracing is still experimental. As such, you need to enable the experimental switch in Azure.

cc @lmolkova @Pilchie 

> Enable tracing when setting up Cosmos client
builder.AddAzureCosmosClient("cosmos",
    settings =>
    {
        settings.DisableTracing = false;
    });

Note that you don't need to do this. The default is `false`. But the issue is in the Cosmos library since the tracing is still experimental. You need to explicitly opt-in.

**Comment by lmolkova** [comment] 2024-09-16 16:54
we ask users to enable experimental tracing for other Azure SDKs (where it's still experimental), so I'd expect the same for Cosmos.

Good side of the story is that OTel database semantic conventions is on track to stabilize by Nov, so Cosmos can stabilize tracing support soon and remove the experimental switch (or limit it's scope to yet-to-be-stabilized)  things.

**Comment by eerhardt** [comment] 2024-09-16 17:11
Given this information, I'm going to close this issue, as there isn't anything Aspire can do. When the semantic conventions get stablized, the underlying Cosmos library should remove the experimental switch, and then tracing will "Just work".

**Closed by eerhardt** 2024-09-16 17:11 UTC
Labels: bug, area-integrations, azure, azure-cosmosdb

**Comment by jcocchi** [comment] 2024-09-16 17:58
Makes sense. We document this experimental switch in the Cosmos docs, I'll update the Aspire docs to mention it as well
