### ISSUE TITLE
Support specifying a path for custom endpoints

### ISSUE THREAD

**Issue by cfbao** [dotnet/aspire#4199] opened 2024-05-16 13:39 UTC
Some apps' best entrypoint URL isn't the root path, but some path below that, e.g. http://localhost:12345/swagger.

If using `AddProject`, we can now get the Aspire dashboard to show a custom path by specifying appropriate properties in launchSettings.json.
However, for executable resources with custom endpoints (added using [WithEndpoint](https://learn.microsoft.com/en-us/dotnet/api/aspire.hosting.resourcebuilderextensions.withendpoint?view=dotnet-aspire-8.0)), there's no way for the dashboard to show a custom path, because [EndpointAnnotation](https://learn.microsoft.com/en-us/dotnet/api/aspire.hosting.applicationmodel.endpointannotation?view=dotnet-aspire-8.0) doesn't support that.

It'd be nice to support specifying a path for custom endpoints, and have the dashboard display that to be more helpful.

**Comment by SteWilson** [comment] 2024-06-13 15:38
This would be useful when configuring the endpoint for the cosmos emulator when running locally. I have to keep adding /_explorer/index.html

**Comment by davidfowl** [comment] 2024-09-16 08:06
Closing this as dupe of https://github.com/dotnet/aspire/issues/5209

**Closed by davidfowl** 2024-09-16 08:06 UTC
Labels: area-app-model, feature
