### ISSUE TITLE
HTTP calls timeout during debugging, hurting developer experience

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/aspire#704] opened 2023-11-06 16:56 UTC
This is not necessarily Aspire-specific but Aspire might provide a solution.

When debugging apps which issue HTTP calls, breakpoints often cause calls to timeout. By the time the debugger suspends the application, loads the necessary data, and the develop inspects the call site or steps the program, enough time has typically elapsed so that any on-going HTTP calls will have timed out.

One potential solution is to extend the response timeout when a debugger is attached. This could be considered an _opinion_, and hence it may belong in Aspire (eg, in Service Defaults).

Another idea is to leverage `TimeProvider`, eg, to stop the wall clock when the process is suspended. This could cause the system to behave in unexpected ways, however. Having a clock which diverges from the one hanging on the wall could be considered a feature or a bug (stressing wall-clock-dependent behavior), but it's most likely a detractor when you're trying to debug something else.

cc @glennc, who suggested I open an issue for this.

**Comment by DamianEdwards** [comment] 2023-11-27 20:52
This is likely a dupe of https://github.com/dotnet/aspnetcore/issues/52031

**Comment by davidfowl** [comment] 2024-02-24 17:53
Moving to backlog

**Comment by cmeyertons** [comment] 2024-07-24 20:33
For anybody coming here wondering why the heck when you're debugging Aspire, your cancellation tokens keep aborting, it's most likely due to:

```csharp
builder.Services.ConfigureHttpClientDefaults(http => {
    http.AddStandardResilienceHandler(); // problem child
    http.AddServiceDiscovery();
});
```

adding the following is a naive workaround:
```csharp
if (Debugger.IsAttached) {
    var timeout = TimeSpan.FromMinutes(10); // 10 min timeout while debugging

    services.ConfigureHttpClientDefaults(clientBuilder => {
        clientBuilder.ConfigureHttpClient(client => {
            client.Timeout = timeout;
        });
    });

    services.ConfigureAll<HttpStandardResilienceOptions>(options => {
        options.AttemptTimeout.Timeout = timeout;
        options.TotalRequestTimeout.Timeout = timeout * 2;
        options.CircuitBreaker.SamplingDuration = timeout * 2;
    });
}
```

**Comment by DamianEdwards** [comment] 2024-08-23 19:14
@davidfowl do you think it's worth suggesting that the standard resilience handler be better updated to handle the debugger is attached scenario? Should we update the Service Defaults template instead?

**Comment by maddymontaquila** [comment] 2024-09-19 23:59
Can't fix because ASP.NET closed as can't fix

**Closed by maddymontaquila** 2024-09-19 23:59 UTC
Labels: area-templates, enhancement
