### ISSUE TITLE
Log streams not showing up

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#3458] opened 2024-04-06 21:32 UTC
Seems like after #3343 the log streams are not responding and printing to the screen. 

https://github.com/dotnet/aspire/assets/4821/e0f8f872-5154-4473-b19d-47d49ea293ec

**Comment by davidfowl** [comment] 2024-04-06 23:05
Bug was caused by the [log virtualization changes](https://github.com/dotnet/aspire/pull/3075): Surprised nobody has seen this until now.

```
System.InvalidOperationException: 'The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.'
```

**Comment by ReubenBond** [comment] 2024-04-06 23:35
Thanks for investigating @davidfowl. Let's revert it and apply it only to the non-Blazor bits, which are the ones the test was complaining about anyway.

**Comment by davidfowl** [comment] 2024-04-06 23:40
I think most of them are fine, I reverted the one that touches ui.

**Comment by davidfowl** [comment] 2024-04-07 00:19
Moving this out of p6 since it wasn't backported.

**Closed** 2024-04-07 03:48 UTC
Labels: area-dashboard
