### ISSUE TITLE
Lliterals with {} break ReferenceExpression

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3787] opened 2024-04-17 20:48 UTC
Repro:

```C#
var s = "{x}";
var expr = ReferenceExpression.Create($"{s}").ValueExpression
```

This explodes. We should handle this.

**Comment by davidebbo** [comment] 2024-07-10 12:57
@davidfowl Can't this just be a one-line fix in `ExpressionInterpolatedStringHandler`, e.g.

```c#
        public readonly void AppendFormatted(string? value)
        {
            _builder.Append(value?.Replace("{", "{{").Replace("}", "}}"));
        }
```

Basically, the `value` that comes in is a literal string, but the `_builder` later gets treated as a format string. So we just need to escape the braces.

**Comment by mitchdenny** [comment] 2024-07-28 23:05
Moving to 8.2 as we'll want to tackle this one.

**Comment by davidebbo** [comment] 2024-08-06 13:31
@mitchdenny I think the only blocker here is to make sure we agree on the intended behavior, per https://github.com/dotnet/aspire/pull/4869#issue-2405163107.

**Closed** 2024-08-12 10:20 UTC
Labels: bug, good first issue, help wanted, area-app-model

**Comment by jeffl8n** [comment] 2024-08-13 13:18
I was creating a PR to add the tests separately from my PR, but this group of tests where the expression string has both parameter and non-parameter brackets is failing with the latest change.  Is this a valid expression string to handle, or is the scope of this issue only for an expression without input parameters?

```
    [Theory]
    [InlineData("{0} {x}", "abc123", "abc123 {x}")]
    [InlineData("{x} {0}", "abc123", "{x} abc123")]
    [InlineData("{0} test {x}", "abc123", "abc123 test {x}")]
    [InlineData("{x} test {0}", "abc123", "{x} test abc123")]
    public void ReferenceExpressionHandlesValueWithBothParameterAndNonParameterBrackets(string input, string parameterValue, string expected)
    {
        var expr = ReferenceExpression.Create($"{input}", [new HostUrl("test")], [parameterValue]).ValueExpression;
        Assert.Equal(expected, expr);
    }
```
