### ISSUE TITLE
[WebToolsE2E][Aspire] When running the Aspire Starter App project, some contents in the dashboard are not localized.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3310] opened 2024-04-01 09:21 UTC
**REGRESSION INFO**: Repro on the latest version Aspire 8.0.0-preview.5.24179.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 22h2 DEU
2. Install Dev17.10.0 Preview 3.0 [34730.35.d17.10] (Includes Aspire 8.0.0-preview.5.24178.3)
3. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > .NET 8.0 > Create
2. Build and F5
3. In the dashboard, go to the Metrics page to open a resource

**ACTUAL**
In the dashboard, some content is not localized.
![image](https://github.com/dotnet/aspire/assets/109339894/a3ac390b-eab9-4ca3-96fc-452a9dddcd83)
![image](https://github.com/dotnet/aspire/assets/109339894/869ef3d1-c1c9-46d7-9121-2232c4f72fbc)

**EXPECTED**
Browser pages should be localized.

**Comment by v-reinawang** [comment] 2024-04-15 05:05
@phenning Is this issue being addressed? I am still repro on VS 17.10.0 Preview 4.0 [34814.14.d17.10] (including Aspire 8.0.0-preview.5.24201.12)

**Comment by phenning** [comment] 2024-04-15 13:58
I know nothing on how the dashboard is localized, or where this string comes from. Although this seems like it may be a runtime localization issue, at least in the way resource assemblies are loaded from the dashboard

@tlmii ?

**Comment by adamint** [comment] 2024-04-15 14:07
@tlmii I agree. The name column does have a loc entry, whereas we do not localize instrument name/descriptions. @JamesNK do you know why that is?

**Comment by JamesNK** [comment] 2024-04-16 00:33
The name/description/unit are read from the instrument that is part of .NET.

Aspire has no control over localizing these.

**Comment by adamint** [comment] 2024-04-16 01:08
Thanks for the response, this can then be closed as not a bug.

**Closed by adamint** 2024-04-16 01:08 UTC
Labels: area-dashboard
