### ISSUE TITLE
[WebToolsE2E][Aspire] After running AspireAzureFunctionsSample, some resources related to ServiceBus fail to run and there are error messages in the console logs

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#6353] opened 2024-10-17 05:18 UTC
**INSTALL STEPS**

Clean machine: Win11 x64 23h2 ENU
Install Dev17.12 Preview 3
Install Aspire 9.0.0-rc.1.24511.1
Install docker desktop for windows
Install git for windows
Install AZ CLI for windows

**REPRO STEPS**
1. Clone [AspireAzureFunctionsSample ](https://github.com/captainsafia/AspireAzureFunctionsSample) repo 
2. Build and run

**ACTUAL**
Some resources can not run successful: messaging, apiservice, funcapp
![Image](https://github.com/user-attachments/assets/f97b77ce-3df5-4940-a93e-e4a947e4fbb3)
Logs information of resource messaging:
Resource could not be provisioned because Azure subscription, location, and resource group information is missing. See https://aka.ms/dotnet/aspire/azure/provisioning for more details.
![Image](https://github.com/user-attachments/assets/1d7611fa-1b29-42dd-a5c7-b51f890bd81e)

Logs information of resource apiservice:
Failed to apply configuration value 'ConnectionStrings__messaging'. A dependency may have failed to start.
![Image](https://github.com/user-attachments/assets/bf04ef5e-d0ce-4891-919b-2bfe33a32f10)

Logs information of resource funcapp:
Failed to apply configuration value 'messaging__fullyQualifiedNamespace'. A dependency may have failed to start.
Failed to apply configuration value 'Aspire__Azure__Messaging__ServiceBus__messaging__FullyQualifiedNamespace'. A dependency may have failed to start.
![Image](https://github.com/user-attachments/assets/e6d2842e-1ff4-4399-b103-079da150ea3b)

Add the following code to the secrets.json file of the AppHost project to configure local provisioning:
```
{
  "Azure": {
    "SubscriptionId": "<Your subscription id>",
    "AllowResourceGroupCreation": true,
    "ResourceGroup": "<Valid resource group name>",
    "Location": "<Valid Azure location>"
  }
}
```
Build and run again, all the resource run successfully, but there are some error logs info under funcapp resource:
![Image](https://github.com/user-attachments/assets/8ec4cf9f-dd67-4c2f-aa33-714609b0cbb3)
2024-10-17T05:06:13 For detailed output, run func with --verbose flag.
2024-10-17T05:06:17 [2024-10-17T05:06:17.576Z] Host lock lease acquired by instance ID '00000000000000000000000098C6CF1E'.
2024-10-17T05:06:26 [2024-10-17T05:06:26.779Z] Message processing error (Action=Receive, EntityPath=myqueue, Endpoint=messaging-msvgyruqlulte.servicebus.windows.net)
2024-10-17T05:06:26 [2024-10-17T05:06:26.779Z] Message processing error (Action=Receive, EntityPath=myqueue, Endpoint=messaging-msvgyruqlulte.servicebus.windows.net)
2024-10-17T05:06:26 [2024-10-17T05:06:26.779Z] Message processing error (Action=Receive, EntityPath=myqueue, Endpoint=messaging-msvgyruqlulte.servicebus.windows.net)
2024-10-17T05:06:26 [2024-10-17T05:06:26.779Z] Message processing error (Action=Receive, EntityPath=myqueue, Endpoint=messaging-msvgyruqlulte.servicebus.windows.net)
2024-10-17T05:06:26 [2024-10-17T05:06:26.782Z] System.Private.CoreLib: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://messaging-msvgyruqlulte.servicebus.windows.net/myqueue'. TrackingId:13a16764ec5b4312bc53cf773af506e0_G30, SystemTracker:gateway10, Timestamp:2024-10-17T05:06:26[2024-10-17T05:06:26.780Z] Message processing error (Action=Receive, EntityPath=myqueue, Endpoint=messaging-msvgyruqlulte.servicebus.windows.net)[2024-10-17T05:06:26.780Z] Message processing error (Action=Receive, EntityPath=myqueue, Endpoint=messaging-msvgyruqlulte.servicebus.windows.net)
2024-10-17T05:06:26 [2024-10-17T05:06:26.784Z] System.Private.CoreLib: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://messaging-msvgyruqlulte.servicebus.windows.net/myqueue'. TrackingId:13a16764ec5b4312bc53cf773af506e0_G30, SystemTracker:gateway10, Timestamp:2024-10-17T05:06:26[2024-10-17T05:06:26.780Z] Message processing error (Action=Receive, EntityPath=myqueue, Endpoint=messaging-msvgyruqlulte.servicebus.windows.net)
2024-10-17T05:06:26 [2024-10-17T05:06:26.785Z] System.Private.CoreLib: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://messaging-msvgyruqlulte.servicebus.windows.net/myqueue'. TrackingId:13a16764ec5b4312bc53cf773af506e0_G30, SystemTracker:gateway10, Timestamp:2024-10-17T05:06:26
2024-10-17T05:06:26 [2024-10-17T05:06:26.781Z] System.Private.CoreLib: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://messaging-msvgyruqlulte.servicebus.windows.net/myqueue'. TrackingId:13a16764ec5b4312bc53cf773af506e0_G30, SystemTracker:gateway10, Timestamp:2024-10-17T05:06:26
2024-10-17T05:06:26 [2024-10-17T05:06:26.787Z] For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
2024-10-17T05:06:26 [2024-10-17T05:06:26.780Z] Message processing error (Action=Receive, EntityPath=myqueue, Endpoint=messaging-msvgyruqlulte.servicebus.windows.net)

**EXPECTED**
All resources run successfully and no errors are reported on the console page

**Comment by davidfowl** [comment] 2024-10-17 06:17
This so by design. There’s no local emulator for service bus and you need to configure the azure provisioning config to allow developing against the remote azure resource. See https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/local-provisioning for more details

**Comment by joperezr** [comment] 2024-10-22 23:21
Closing as per above.

**Closed by joperezr** 2024-10-22 23:21 UTC
Labels: untriaged
