### ISSUE TITLE
[WebToolsE2E][Aspire] On a clean Windows machine with only .NET 9 SDK installed, run `dotnet workload install aspire` should not install the aspire workload

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#6029] opened 2024-09-30 15:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install .NET SDK 9.0 RC2 - latest version
    - Apply dotnet9rc2feed
    - Run cred helper to authenticate the feed
1. Apply feed for Aspire 9.0 packages
    - Add dotnet8 feed

**REPRO STEPS**
1. Open new command prompt
2. Run `dotnet workload update` and `dotnet workload install aspire` 

**ACTUAL**
When we run 'dotnet workload update', it updates the aspire manifest from version 8.2.0 to 8.2.1

![image](https://github.com/user-attachments/assets/f0093cb8-b3eb-452a-ad92-2f7e09478efd)

When we run 'dotnet workload install aspire', it installs the aspire 8.2.1 workload

![image](https://github.com/user-attachments/assets/97d5f5db-0b71-45bd-aec9-ad7574db1eb6)

**EXPECTED**
With the .NET 9 SDK, Aspire manifest should not be included. 

And running 'dotnet workload update' or 'dotnet workload install aspire' should not update or install aspire workload.

**ADDITIONAL INFO**

**dotnet --info**
![image](https://github.com/user-attachments/assets/ade907e8-e503-4c13-974c-0e24434a3678)

**Comment by DamianEdwards** [comment] 2024-09-30 18:18
This isn't a bug IIUC. Customers need to be able to use the .NET 9 SDK to work on Aspire 8.x projects and that means they need to be able to install the workload.

**Comment by DamianEdwards** [comment] 2024-10-03 23:12
@joperezr can you confirm?

**Comment by joperezr** [comment] 2024-10-03 23:17
Closing as this is not a bug.

**Closed by joperezr** 2024-10-03 23:17 UTC
Labels: bug, area-acquisition
