### ISSUE TITLE
Service lifetime for PSQL DbContext

### ISSUE THREAD

**Issue by adamtrip** [dotnet/aspire#1504] opened 2023-12-27 21:15 UTC
After some digging I did not find a way to define the DbContext Service Lifetime. I believe that by default, the DbContext is being registered as a singleton because of Context Pooling. 
Is that for any specific reason? Can it be changed somehow? 

This because I want to inject some scoped services on my dbcontext and I'm unable to do so. Getting an error:
`Cannot resolve scoped service 'CalGest.Shared.Common.Interfaces.ICurrentUser' from root provider.`

Thanks in advance!

**Comment by mitchdenny** [comment] 2024-01-11 04:21
Db contexts are pooled by default. You can change this setting:

https://learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-entity-framework-component?tabs=dotnet-cli#use-configuration-providers

@eerhardt is there a blessed way via the Aspire component's signature to get at lifetime scope for the dbcontext?

**Comment by eerhardt** [comment] 2024-01-11 15:48
This should be resolved when #1403 is addressed. The EF Aspire components will no longer register the DbContext, but instead the app will register it using EF APIs.

**Comment by DamianEdwards** [comment] 2024-01-11 16:58
Closing as dupe of #1403

**Closed by DamianEdwards** 2024-01-11 16:58 UTC
Labels: area-components

**Comment by adamtrip** [comment] 2024-01-12 10:08
Thanks everyone! I ended up by making the DbContext not pooled and worked for me. However, I'll keep an eye on https://github.com/dotnet/aspire/issues/1403 

Thanks once again 😄
