### ISSUE TITLE
[WebToolsE2E][Aspire] Aspire 9 templates should not be installed with Aspire 8 templates.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#6263] opened 2024-10-12 06:23 UTC
**REPRO STEPS**

1. Install SDK 9.0 RC2
2. Install Aspire 9.0 template -latest version 9.0.0-rc.1.24511.1
    - Add dotnet8 feed
    - dotnet new install Aspire.ProjectTemplates::9.0.0-rc.1.24511.1 --force

**ACTUAL**

- When you install the aspire 9 template, the aspire 8 template is also included.

  ![Image](https://github.com/user-attachments/assets/6e2c4397-5333-451e-a835-93ac1ca70ea3)

- Creating aspire-starter-8 project fails with following error

  ![Image](https://github.com/user-attachments/assets/31862620-bddf-4d1e-8ae8-ae5a4e11dc3f)

- Creating aspire-starter-8 project again fails with another error

  ![Image](https://github.com/user-attachments/assets/56c984ab-64ce-4e67-8679-3fc98795e747)

**EXPECTED**

Aspire 9 templates should not include Aspire 8 templates.

**Comment by davidfowl** [comment] 2024-10-12 14:02
I'm pretty sure this was an intentional change. @joperezr ?

**Comment by joperezr** [comment] 2024-10-12 16:02
Correct, this was intentional in order to simplify our template story. Given you don't have the workload installed, they won't be listed in dotnet new list, nor visual studio. The intent of including them is to rename their shortname, so they don't clash with aspire 9 templates.

**Comment by joperezr** [comment] 2024-10-12 16:04
Closing as this is by design. Feel free to reopen if you think we should do something different here.

**Closed** 2024-10-12 16:04 UTC
Labels: bug
