### ISSUE TITLE
How to setup Front End Debugging?

### ISSUE THREAD

**Issue by AceHack** [dotnet/aspire#1793] opened 2024-01-23 22:55 UTC
How do I set up Aspire so I can hit breakpoints on the Client side in a Blazor Auto Render Mode app? Preferably, I can hit breakpoints in both C# and JavaScript.

**Comment by AceHack** [comment] 2024-01-24 08:51
Here is my project, and I'm running in Visual Studio on Windows 11. using AppHost as the start project  Please let me know if you need anymore information.

https://github.com/AlephZ-ai/blazor-samples

**Comment by davidfowl** [comment] 2024-01-28 02:46
@vijayrkn can we investigate Blazor WASM projects working with debugging and F5.

**Comment by davidfowl** [comment] 2024-01-28 02:49
cc @bradygaster

**Comment by davidfowl** [comment] 2024-01-29 15:32
Dupe of https://github.com/dotnet/aspire/issues/1418

**Closed by davidfowl** 2024-01-29 15:32 UTC
Labels: area-tooling
