### ISSUE TITLE
Support manual container restart

### ISSUE THREAD

**Issue by TheDevelolper** [dotnet/aspire#6003] opened 2024-09-28 12:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to run multiple containers, but sometimes one needs restarting when changes are made locally.

### Describe the solution you'd like

I'd like the ability to restart containers from the aspire dashboard.

### Additional context

It would be nice to have a little refresh icon next to each container that when pressed would restart it.

**Comment by TheDevelolper** [comment] 2024-09-28 12:27
I did search but couldn't find mention of this elsewhere. I'm thinking that it would be quite easy to implement.

**Comment by afscrome** [comment] 2024-09-28 14:00
This is coming in 9.0 - https://x.com/JamesNK/status/1837039173058060645 .  Not a restart button, but you can stop then start the cotnainer to get a restart.

**Comment by davidfowl** [comment] 2024-09-28 14:31
Dupe of https://github.com/dotnet/aspire/issues/295 which is part of aspire 9

**Closed by davidfowl** 2024-09-28 14:31 UTC

**Comment by TheDevelolper** [comment] 2024-09-29 07:39
> Dupe of https://github.com/dotnet/aspire/issues/295 which is part of aspire 9

Ah sorry, I thought someone would have suggested it already.
