### ISSUE TITLE
Provide Dashboard Extensibility

### ISSUE THREAD

**Issue by dansiegel** [dotnet/aspire#2258] opened 2024-02-15 20:01 UTC
# Description

When creating a new Aspire app we get a fairly straightforward Dashboard. It would be good if the Dashboard could be extended with custom components. Like let's say I want the "Dan's Awesome Component" to collect custom data about my app and/or provide a mix of custom data with data already being collected by Aspire and present it in a custom view from a custom menu option. In this example I might then have 3 top level menu options:

- Resources
- Monitoring
- Dan's Awesome Component

![image](https://github.com/dotnet/aspire/assets/3860573/883c63f0-694a-4082-9984-f9c26178008a)

**Comment by davidfowl** [comment] 2024-02-15 23:50
No plans in the first version to enable this. Maybe in a later version we'll get here.

**Comment by davidfowl** [comment] 2024-02-15 23:51
Dupe of https://github.com/dotnet/aspire/issues/1868

**Closed by davidfowl** 2024-02-15 23:51 UTC
Labels: area-dashboard, untriaged
