### ISSUE TITLE
[WebToolsE2E][Aspire] After adding Aspire.StackExchange.Redis.OutputCaching and related codes, run the Aspire Starter project, it shows StackExchange.Redis.RedisConnectionExceptionerrors on the dashoboard

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2883] opened 2024-03-14 10:01 UTC
**REGRESSION INFO**: Also repro on Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 3.0 [34713.193.main] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire.ProjectTemplates.8.0.0-preview.5.24163.18
4. Apply NuGet Feeds
5. Install Docker Desktop
6. Install azd

**REPRO STEPS**

1. New > Project > .NET Aspire Starter Application > Enter a Project name of AspireRedis02 > .NET 8.0 > Uncheck Use Redis for caching > Create. 
2. Right-click the AspireRedis02.Web project > Add > .NET Aspire Component > install Aspire.StackExchange.Redis.OutputCaching with matched version
3. Open appsettings.json of AspireRedis02.Web project, add following codes: 
```
"ConnectionStrings": { 
    "cache": "localhost:6379" 
  }  
"Aspire": { 
    "StackExchange": { 
      "Redis": { 
        "ConfigurationOptions": { 
          "ConnectTimeout": 3000, 
          "ConnectRetry": 2 
        }, 
        "HealthChecks": false, 
        "Tracing": true 
      } 
    } 
  } 
```
4. Open Program.cs of AspireRedis02.Web project, add following code: 
```
builder.AddRedisOutputCache("cache"); 
```
5. Open Components/Pages/Home.razor, update with following codes:
```
@page "/" 
@attribute [OutputCache(Duration = 10)] 
<PageTitle>Home</PageTitle> 
<h1>Hello, world!</h1> 
Welcome to your new app on @DateTime.Now 
```
6. F5 with https/http

**ACTUAL**
It will show errors on the dashboard
![image](https://github.com/dotnet/aspire/assets/82028229/69b6a10c-b4d3-45c7-923e-1c4ee66250c8)
StackExchange.Redis.RedisConnectionException: UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 3s ago, last-write: 3s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 3s ago, v: 2.7.27.49176
...
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). ConnectTimeout

**Note**:

1. This issue also repro on Aspire 8.0.0-preview.4.24156.9
2. If don't add "ConnectionString" to the appsettings.json file F5 will failed with an exception: 
![image](https://github.com/dotnet/aspire/assets/82028229/3c5be30a-b6aa-4eaa-a29f-f6786d142db1)
System.InvalidOperationException
  HResult=0x80131509
  Message=No endpoints specified. Ensure a valid connection string was provided in 'ConnectionStrings:cache' or for the 'Aspire:StackExchange:Redis:ConnectionString' configuration key.
  Source=Aspire.StackExchange.Redis
  StackTrace:
   at Microsoft.Extensions.Hosting.AspireRedisExtensions.GetConfigurationOptions(IServiceProvider serviceProvider, String connectionName, String configurationSectionName, String optionsName)
   at Microsoft.Extensions.Hosting.AspireRedisExtensions.<>c__DisplayClass5_0.<AddRedisClient>b__2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.<>c__DisplayClass4_0.<AddRedisInstrumentation>b__1(IServiceProvider sp)
   at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracerProviderBuilderExtensions.<>c__DisplayClass2_1`1.<AddInstrumentation>b__1()
   at OpenTelemetry.Trace.TracerProviderBuilderSdk.AddInstrumentation[TInstrumentation](Func`1 instrumentationFactory)
   at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracerProviderBuilderExtensions.<>c__DisplayClass2_0`1.<AddInstrumentation>b__0(IServiceProvider sp, TracerProviderBuilder builder)
   at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracingServiceCollectionExtensions.ConfigureTracerProviderBuilderCallbackWrapper.ConfigureBuilder(IServiceProvider serviceProvider, TracerProviderBuilder tracerProviderBuilder)
   at OpenTelemetry.Trace.TracerProviderSdk..ctor(IServiceProvider serviceProvider, Boolean ownsServiceProvider)
   at OpenTelemetry.Trace.TracerProviderBuilderBase.<>c.<.ctor>b__3_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.Initialize(IServiceProvider serviceProvider)
   at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<<StartAsync>b__15_1>d.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<ForeachService>d__18`1.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\Users\v-cazhang\source\repos\AspireRedis02\AspireRedis02.Web\Program.cs:line 44

**EXPECTED**
No error shows

**Comment by eerhardt** [comment] 2024-04-15 20:05
Closing as this is the intended behavior. If you don't configure a Redis server to connect to, you will get an error.

**Closed by eerhardt** 2024-04-15 20:05 UTC
Labels: area-components
