### ISSUE TITLE
Errors debugging Aspire in VS Code on Mac after upgrading to Sequoia

### ISSUE THREAD

**Issue by jeffa00** [dotnet/aspire#5860] opened 2024-09-23 19:23 UTC
### Discussed in https://github.com/dotnet/aspire/discussions/5822

<div type='discussions-op-text'>

<sup>Originally posted by **jeffa00** September 21, 2024</sup>
After upgrading to Sequoia I get an error trying to start debugging on the AppHost project.

The specific error I get is "The JSON-RPC connection with the remote party was lost before the request could complete."

Google and Bing haven't yielded much help. I find a similar error in Visual Studio from back in 2019ish, but nothing recent.

I've uninstalled extensions, then VS Code, but no joy.

I can debug the web app just fine, but the error always occurs when trying to start AppHost.

I'm trying to figure out if it is indeed something in Sequoia. I have a work mac with Sonoma that doesn't have the issue.

Just curious if anyone else has seen this or if I'm just super lucky. :-)</div>

**Comment by jeffa00** [comment] 2024-09-23 21:03
FYI I am on an M2, so Apple silicon. Someone else replied in the discussion topic I originally created that on an Intel Mac, he is not experiencing the same error.

**Comment by RobertWeaver** [comment] 2024-09-24 12:25
I also have the same issue. M1 with Aspire 8.2.0 

Here is what I can see... 
![image](https://github.com/user-attachments/assets/7816f47b-c35e-45bc-9d90-3c80ee5e65ab)

My dotnet --info
```
.NET SDK:
 Version:           9.0.100-rc.1.24452.12
 Commit:            81a714c6d3
 Workload version:  9.0.100-manifests.67cd1eb6
 MSBuild version:   17.12.0-preview-24422-09+d17ec720d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  15.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/9.0.100-rc.1.24452.12/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 9.0.100-rc.1
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.2.0/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-rc.1.24431.7
  Architecture: arm64
  Commit:       static

.NET SDKs installed:
  8.0.401 [/usr/local/share/dotnet/sdk]
  9.0.100-rc.1.24452.12 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.1.24452.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24431.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by captainsafia** [comment] 2024-09-24 14:45
I'm seeing the same thing on Apple Silicon (M2) as well. Issue seems to have shown up after the Sequoia upgrade as well. Similar to you, I can debug test cases and other non-Aspire apps fine so I suspect that the bug is manifesting from the Aspire-specific debugging hooks?

I can provide logs but not sure what the right log source is for these specific issues.

cc: @WardenGnaw for any insights on logs we can gather or people we can loop in

**Comment by WardenGnaw** [comment] 2024-09-24 16:12
"The JSON-RPC connection with the remote party was lost before the request could complete" is generally something failed with brokered service communication.

I don't think we have specific logs for this section unless you see an actual debug session start. 

Things that could be helpful for this investigation: 
- The version of C# Extension + C# Dev Kit used.
- Is the AppHost not starting to debug or are the projects listed under the AppHost not starting to debug?

**Comment by captainsafia** [comment] 2024-09-24 17:44
I was able to repro this on both the pre-release and release builds of the extensions.

C# extension version: v2.48.31 (pre-release), v2.45.25
C# Dev Kit version: v1.11.9 (pre-release), v1.10.18

The AppHost itself is not starting to debug.

**Comment by jeffa00** [comment] 2024-09-24 18:04
C#: v2.45.25
C# Dev Kit: v1.10.18

![image](https://github.com/user-attachments/assets/89c1e55a-2184-445c-9a67-cf70febbec93)

The AppHost fails to start, but other apps can start (example an ASP app).

**Comment by jeffa00** [comment] 2024-09-24 18:06
Also, can run AppHost from the CLI.

**Comment by smitpatel** [comment] 2024-09-24 23:45
Likely root cause https://github.com/dotnet/announcements/issues/324
AspireServerService is failing to start due to above.

**Comment by RobertWeaver** [comment] 2024-09-25 04:26
After trying the workaround here https://github.com/dotnet/runtime/issues/106775#issuecomment-2370577838 I can now launch the dashboard and everything in debug mode but I cannot hit any breakpoints? I did try to add the "requireExactSource" but that does not work either.

![image](https://github.com/user-attachments/assets/f2c71d42-d29d-44cb-a7a9-5d5f35075eeb)

**Comment by kamalraj2000** [comment] 2024-09-27 17:19
I am also running into this issue on a M3 Mac. It started after upgrading to Sequoia.

C# Dev Kit: v1.10.18
C# Extension: v2.45.25

I can run the AppHost from CLI but not when launching through VSCode debug mode.

**Comment by Fiontan** [comment] 2024-09-30 18:14
Same- M3, all good until latest OSequoia upgrade

**Comment by DamianEdwards** [comment] 2024-10-08 20:28
The fix for this issue in the .NET SDK was included in today's releases of .NET 8.0.10 and .NET 9.0-rc.2. Would be good if someone can upgrade and confirm the issue is fixed for them.

**Comment by captainsafia** [comment] 2024-10-09 16:13
I'm able to debug my Aspire apps after upgrading. Would be good to get confirmation from other folks as well.

**Comment by xtqqczze** [comment] 2024-10-09 19:51
> 8.0.403 was just released that does fix this.
> 
> 
> 
> But you need to run:
> 
> 
> 
> dotnet dev-certs https --clean
> 
> dotnet dev-certs https --trust
> 
> 
> 
> And then you should be back in business. 

 _Originally posted by @jhancock-taxa in [#9532](https://github.com/dotnet/core/issues/9532#issuecomment-2400712842)_

**Comment by webreidi** [comment] 2024-10-11 22:14
My debugging works after upgrading as well.

**Comment by kamalraj2000** [comment] 2024-10-19 16:56
I am also confirming that Aspire debugging is working on a M3 Mac after upgrading to .NET 8.0.10

**Comment by DamianEdwards** [comment] 2024-10-19 23:44
Thanks for the confirmations folks. Closing this out.

**Closed** 2024-10-19 23:44 UTC
Labels: area-tooling, vs-code, untriaged
