### ISSUE TITLE
API proposal for Azure resources

### ISSUE THREAD

**Issue by vicancy** [dotnet/aspire#4401] opened 2024-06-06 02:13 UTC
## Issue to resolve
When writing the component for WebPubSub, everytime I locally run my sample project `xxx.AppHost` with `AddAzureWebPubSub` it always provisions a new Azure service, and after 5 times it hits our service free resource limitation 5. It makes me wondering what is the common workflow when a customer uses aspire with Azure services. IMHO, it follows these steps:
1. Add AppHost that helps provisioning the service
2. Add web app that consumes the service
3. Local debug to see if the workflow works -> aspire provisions the service, web app successfully consumes the service, and web app runs successfully
4. There might be some issues found in web app: update the application code and rerun the code
5. Aspire provisions another service for the web app to consume

Step 5 sounds not necessary and  if customer reruns for application code updates, an API like `GetOrAdd...` could help.

## API proposal
I am wondering if this is a common need and if we could have some general patterns for Azure service provisioning, with APIs like:
```csharp
AddAzure{Service}("name");
GetOrAddAzure{Service}("name");
AddOrUpdateAzure{Service}("name");
TryGetAzure{Service}("name");
```

**Comment by mitchdenny** [comment] 2024-06-08 00:53
It shouldn't be provisioning a new resource each time. When you run the apphost for the first time it should be storing connection information for the resource in secrets.json.

The only way it would generate a new resource each time is if you were generating a custom resource name each time or where deploying to a new resource group each time.

Are all the resources deployed into the same user group?

**Comment by davidfowl** [comment] 2024-06-08 06:22
I'd like to figure out how to address the "use a custom resource but not using a connection string to see if this is a valuable feature in general". I've been playing with this scenario, my team has a pre-provisioned keyvault that I'm using to get secrets and I want to point to it in the apphost:

```C#
var builder = DistributedApplication.CreateBuilder(args);

var kv = builder.AddExistingKeyVault("kv", "vault");

builder.AddProject<Projects.WebApplication1>("api")
       .WithReference(kv)
       .WithExternalHttpEndpoints();

builder.Build().Run();
```

Here's the implementation:

```C#
public static class KeyVaultExtensions
{
    public static IResourceBuilder<AzureKeyVaultResource> AddExistingKeyVault(this IDistributedApplicationBuilder builder, string name, string vaultName)
    {
        AzureKeyVaultResource? resource = null;

        resource = new AzureKeyVaultResource(name, c =>
        {
            // Add the principal id parameter
            // c.AddParameter(c.PrincipalIdParameter);

            // Get the existing key vault resource based on the name
            var kv = KeyVault.FromExisting(c, $"'{vaultName}'");

            // Do role assignments
            // kv.AssignRole(RoleDefinition.KeyVaultAdministrator);

            // This name is important because it maps to AzureKeyVaultResource.VaultUri.Name
            kv.AddOutput(resource!.VaultUri.Name, k => k.Properties.VaultUri);
        });

        return builder.AddResource(resource)
                      // Tell the system that we want the principal id to produce role assignments
                      // .WithParameter(AzureBicepResource.KnownParameters.PrincipalId)
                      .WithManifestPublishingCallback(resource.WriteToManifest);
    }
}
```

The idea is that you just need the resource name, and we will "do the rest". It's unclear if we should do role assignments as well. Maybe it should opt-in.

PS: This feels like a dupe of https://github.com/dotnet/aspire/issues/2395

**Comment by vicancy** [comment] 2024-08-28 01:12
Ah I see, why I have the feeling of always provisioning is that I work from several different devices, a new device runs the same code and start a new provisioning.

> It shouldn't be provisioning a new resource each time. When you run the apphost for the first time it should be storing connection information for the resource in secrets.json.
> 
> The only way it would generate a new resource each time is if you were generating a custom resource name each time or where deploying to a new resource group each time.
> 
> Are all the resources deployed into the same user group?

**Comment by davidfowl** [comment] 2024-09-08 03:06
Dupe of https://github.com/dotnet/aspire/issues/2395

**Closed by davidfowl** 2024-09-08 03:06 UTC
Labels: area-integrations, azure
