### ISSUE TITLE
Custom filters in dashboard traces

### ISSUE THREAD

**Issue by lvde0** [dotnet/aspire#5290] opened 2024-08-14 14:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am using the standalone dashboard and would really like to filter the traces for properties (e.g. http status code, or custom ones I enriched the spans with). Are there any plans to implement that?

### Describe the solution you'd like

Filter option similar to the one in structured logs.

**Comment by davidfowl** [comment] 2024-09-29 05:35
See https://github.com/dotnet/aspire/pull/5984

**Comment by JamesNK** [comment] 2024-09-30 00:08
Duplicate of https://github.com/dotnet/aspire/issues/5100

Already done and will ship in Aspire 9.

**Closed by JamesNK** 2024-09-30 00:08 UTC
Labels: area-dashboard, area-telemetry, feature, dashboard-filter-sort
