### ISSUE TITLE
Method not found Exception when Microsoft.FluentUI.AspNetCore.Components 4.0.0 is referenced

### ISSUE THREAD

**Issue by ProH4Ck** [dotnet/aspire#948] opened 2023-11-18 14:50 UTC
<img width="951" alt="image" src="https://github.com/dotnet/aspire/assets/8057670/bf617646-f201-45be-8ea4-73fab96fbba2">

# Problem description

When a project referenced by `AppHost` references `Microsoft.FluentUI.AspNetCore.Components` version 4.0.0 startup breaks with the following exception:

`Method not found: 'Void Microsoft.FluentUI.AspNetCore.Components.LibraryConfiguration.set_HostingModel(Microsoft.FluentUI.AspNetCore.Components.BlazorHostingModel)'.`
```
   at Aspire.Dashboard.DashboardWebApplication.<>c.<.ctor>b__7_2(LibraryConfiguration options)
   at Microsoft.FluentUI.AspNetCore.Components.ServiceCollectionExtensions.AddFluentUIComponents(IServiceCollection services, Action`1 configuration)
   at Aspire.Dashboard.DashboardWebApplication..ctor(ILogger`1 logger, Action`1 configureServices)
   at Aspire.Hosting.Dcp.DcpHostService..ctor(DistributedApplicationModel applicationModel, DistributedApplicationOptions options, ILoggerFactory loggerFactory, IOptions`1 dcpOptions, IOptions`1 publishingOptions, ApplicationExecutor appExecutor, Locations locations, KubernetesService kubernetesService)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Aspire.Hosting.DistributedApplication.<RunAsync>d__13.MoveNext()
```

# Repro steps
- Create a new project using the starter template
- Add to `Web` project a reference to `Microsoft.FluentUI.AspNetCore.Components` v. 4.0.0
- Run AppHost

**Comment by ProH4Ck** [comment] 2023-11-18 15:12
Found a workaround: this is fixed in preview.2. 
Add NuGet feed to `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json` and update `Aspire.Hosting` package to version `8.0.0-preview.2.23567.5`:

<img width="533" alt="image" src="https://github.com/dotnet/aspire/assets/8057670/0b809991-13fd-4e3e-ac7e-6ea93952a006">

**Comment by davidfowl** [comment] 2023-11-18 17:59
This is a bug as the version you use shouldn't affect the dashboard. This is currently an issue with how we use project references.

**Comment by efonsecab** [comment] 2023-11-18 20:41
I just got this error while I was trying to convert some of my demo projects to FluentUI.
I tried to use a similar trick to other issue by forcing excluding assets, though it did not work for this specific case.

**Comment by iskandersierra** [comment] 2023-12-12 22:50
> Found a workaround: this is fixed in preview.2.
> Add NuGet feed to `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json` and update `Aspire.Hosting` package to version `8.0.0-preview.2.23567.5`:

I can confirm this workaround work for me! Googling this issue only resulted in two answers, and this issue was not one of them. It should be! Thanks @ProH4Ck.

**Comment by leslierichardson95** [comment] 2023-12-13 23:58
This will be fixed when decoupling the dashboard is completed.

**Comment by JamesNK** [comment] 2024-03-07 02:35
This should be fixed because the dashboard is decoupled.

Comment if this is still a problem and we'll reopen and take another look.

**Closed by JamesNK** 2024-03-07 02:35 UTC
Labels: area-dashboard
