### ISSUE TITLE
Using CPM Breaks AppHost build on linux with preview 9

### ISSUE THREAD

**Issue by lawrencek76** [dotnet/aspire#6588] opened 2024-11-01 14:38 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

After updating a project created with  `dotnet new aspire-starter`  using the 9x templates and then modifying the project to us central package management we start failing to build on `ubuntu-latest` with github actions giving the following error: 

```
/home/runner/.nuget/packages/aspire.apphost.sdk/9.0.0-rc.1.24511.1/Sdk/Sdk.targets(89,5): error : test-aspire.AppHost is a .NET Aspire AppHost project that needs a package reference to Aspire.Hosting.AppHost version 8.2.0 or above to work correctly. [/home/runner/work/test-aspire/test-aspire/test-aspire.AppHost/test-aspire.AppHost.csproj]
```

### Expected Behavior

Builds without error

### Steps To Reproduce

https://github.com/lawrencek76/test-aspire

add directory.packages.props and make relevant changes to proj files.

### .NET Version info

```
.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.cea95dba
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/9.0.100-rc.2.24474.11/

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0-rc.2.24473.5
  Architecture: x64
  Commit:       990ebf52fc

.NET SDKs installed:
  6.0.427 [/usr/share/dotnet/sdk]
  7.0.410 [/usr/share/dotnet/sdk]
  8.0.403 [/usr/share/dotnet/sdk]
  9.0.100-rc.2.24474.11 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.35 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.2.24474.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.35 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24473.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  /home/runner/work/test-aspire/test-aspire/global.json
```

### Anything else?

Locally on windows and wsl this error does not occur only seems to happen with github actions.  I have tried to setup my wls ubuntu identically with same versions of .net core as actions but i'm not able to find the difference.

**Comment by davidfowl** [comment] 2024-11-01 15:31
cc @joperezr

**Comment by joperezr** [comment] 2024-11-01 16:58
Thanks for the report, @lawrencek76 . I'm pretty sure this is fixed in our latest release 8.2.2. Can you try updating to 8.2.2 and verifying? Alternatively, can you share a minimal repro that we can use in case you are still seeing issues?

**Comment by joperezr** [comment] 2024-11-01 17:00
Scratch that, just saw you have a repro 😄, sorry for not reading through. I'll validate that this is fixed there.

**Comment by joperezr** [comment] 2024-11-01 17:23
I see what the issue is here. In your repro project, your CPM file is named using lowercase-syntax: `directory.packages.props` instead of `Directory.Packages.props` which is what the SDK and NuGet will look for and automatically import. If you are on a case-sensitive OS (like Linux) then your CPM file will not get imported and result in issues of package references not having their versions defined. You hit this issue with Aspire first because it happens that Aspire is one of the first ones that is trying to load a package version, but you'd hit this issue as well with a non-aspire project as well as versions from your CPM file won't be used at all.

**Comment by joperezr** [comment] 2024-11-01 17:27
I submitted a PR to your repo with the fix. Please pull that and validate that the issue is fixed: https://github.com/lawrencek76/test-aspire/pull/1

Thanks again for reporting this @lawrencek76, I'm closing this as it isn't really a bug in Aspire, that said, please feel free to reopen if you have any follow up questions :).

**Closed by joperezr** 2024-11-01 17:27 UTC
Labels: area-acquisition, untriaged
