### ISSUE TITLE
Restarting projects/executables prints file in use errors from orchestrator

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#5830] opened 2024-09-22 07:42 UTC
I reproduced from VS and on the command line so it doesn't seem related to IDE mode.

```
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"api-npekzskr"}, "Reconciliation": 13, "path": "C:\\Users\\davifowl\\AppData\\Local\\Temp\\aspire.lielf4bo.gxy\\api-npekzskr_out_42b19d6c-e19e-45a6-8cb2-039eb80b4b51", "error": "remove C:\\Users\\davifowl\\AppData\\Local\\Temp\\aspire.lielf4bo.gxy\\api-npekzskr_out_42b19d6c-e19e-45a6-8cb2-039eb80b4b51: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"api-npekzskr"}, "Reconciliation": 13, "path": "C:\\Users\\davifowl\\AppData\\Local\\Temp\\aspire.lielf4bo.gxy\\api-npekzskr_err_42b19d6c-e19e-45a6-8cb2-039eb80b4b51", "error": "remove C:\\Users\\davifowl\\AppData\\Local\\Temp\\aspire.lielf4bo.gxy\\api-npekzskr_err_42b19d6c-e19e-45a6-8cb2-039eb80b4b51: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"api-npekzskr"}, "Reconciliation": 14, "path": "C:\\Users\\davifowl\\AppData\\Local\\Temp\\aspire.lielf4bo.gxy\\api-npekzskr_out_42b19d6c-e19e-45a6-8cb2-039eb80b4b51", "error": "remove C:\\Users\\davifowl\\AppData\\Local\\Temp\\aspire.lielf4bo.gxy\\api-npekzskr_out_42b19d6c-e19e-45a6-8cb2-039eb80b4b51: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"api-npekzskr"}, "Reconciliation": 14, "path": "C:\\Users\\davifowl\\AppData\\Local\\Temp\\aspire.lielf4bo.gxy\\api-npekzskr_err_42b19d6c-e19e-45a6-8cb2-039eb80b4b51", "error": "remove C:\\Users\\davifowl\\AppData\\Local\\Temp\\aspire.lielf4bo.gxy\\api-npekzskr_err_42b19d6c-e19e-45a6-8cb2-039eb80b4b51: The process cannot access the file because it is being used by another process."}
``

**Comment by dbreshears** [comment] 2024-09-23 18:22
@davidfowl ,  appears to be a dupe of #5853.  Closing this in favor of that issue.

**Closed by dbreshears** 2024-09-23 18:22 UTC
Labels: bug, area-orchestrator

**Comment by davidfowl** [comment] 2024-09-23 18:27
I filed this first! 😄
