### ISSUE TITLE
Service Discovery does not work in WASM/InteractiveWebAssembly mode

### ISSUE THREAD

**Issue by AceHack** [dotnet/aspire#1659] opened 2024-01-15 07:42 UTC
If creating a `HttpClient` in `WASM` mode, the endpoint remains unchanged like `apiservice` and never gets replaced with the real value when running in the browser.  Works fine in `InteractiveServer` breaks in `InteractiveWebAssembly`, flakey in `InteractiveAuto` as it switches back and fourth and sometimes works, sometimes does not.

**Comment by ReubenBond** [comment] 2024-01-19 00:07
@AceHack Service Discovery does not support Blazor client-side apps today. For that scenario, I would recommend using YARP on the web application hosting Blazor service and proxying routing requests through that.

See how this is done in eShop for loading catalog images, for example: https://github.com/dotnet/eShop/blob/3b49f61a888656b038b5f044b0d4c5096fc9f073/src/WebApp/Program.cs#L29

**Comment by AceHack** [comment] 2024-01-24 08:44
In case you are wondering you can see me trying to use it in the WASM browser client here
https://github.com/AlephZ-ai/blazor-samples

I do a workaround by adding the URLs in the Service section of appsettings.config

**Comment by mip1983** [comment] 2024-04-12 08:58
At the moment I put the API url on the config of the client project, but it does mean I have to do transformation on this config when it get's pushed to different environments,so was wondering if it could pull the API url from the host on start up.

I'm not dead set, but I think I'd rather not do the YARP reverse proxy thing, adding an extra hop when the client could go direct to the API.

I was thinking of putting a simple client config endpoint on the web project that leveraged aspires service discovery to pass the API direct url and call that once in the program.cs of the client. i.e.

```
app.MapGet("/config/client", async (IDontKnowWhatThisShouldBeEndPointResolver resolver) =>
{
	var config = new ClientConfig
	{
		ApiUrl = resolver.Resolve("my-api"),
	};

	return config;
});
```

Is that possible (or a good idea?). I was having a nose around what 'AddServiceDefaults' adds for endpoint resolution but didn't find a public interface so far.

**Comment by davidfowl** [comment] 2024-05-26 16:28
Closing as dupe of https://github.com/dotnet/aspire/issues/1536

**Closed by davidfowl** 2024-05-26 16:28 UTC
Labels: area-service-discovery
