### ISSUE TITLE
[WebToolsE2E][Aspire] Add an API project to the aspire solution and debug it, then click the "API" endpoint and the swagger page cannot be found.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#1290] opened 2023-12-08 09:18 UTC
**REGRESSION INFO**: Works fine on Aspire.ProjectTemplates.8.0.0-preview.1.23557.2

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install the latest VS Code
3. Download the latest released C# DevKit [1.2.2]
4. Install 8.0.100 SDK
5. CLI workload update and install aspire: [Aspire.ProjectTemplates.8.0.0-preview.2.23606.12]
6. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS Code, click 'Extension' tab, click '...' to installl the C# DevKit.
2. Click create .NET project > .NET Aspire Application > named with 'AspireApp1'> Create 
3. Right-click solution name > new project > ASP.NET Core Web API > named with 'API'
4. Right-click xxx.AppHost > Add Project Reference > API
5. Open xxx.AppHost / Program.cs file and add code `builder.AddProject<Projects.API>("API");`
6. Right-click xxx.AppHost > Debug > Start New Instance
7. Go to URL http://localhost:18888
8. Click the endpoint of 'API'

**ACTUAL**
This localhost page can’t be found
![image](https://github.com/dotnet/aspire/assets/71361488/2a83f631-fbe2-4d37-b89e-f8f12889ee4b)

**Note**

-  This issue also reproduce on windows / macos / linux.

**EXPECTED**
The swagger page can display well.

**_Note_**: Steps to repro using command-line (i.e. without VS Code)

```
C:\Solutions>
dotnet new aspire -o AspireApp2
cd AspireApp2
cd AspireApp2.AppHost
dotnet run
cd..

C:\Solutions\AspireApp2>
dotnet new webapi -o ApiApp2
dotnet sln AspireApp2.sln add ApiApp2\ApiApp2.csproj
cd AspireApp2.AppHost

dotnet add AspireApp2.AppHost.csproj reference ..\ApiApp2\ApiApp2.csproj
notepad Program.cs 
// add the line builder.AddProject<Projects.ApiApp2>("apiapp2");
dotnet run
```

**Comment by DamianEdwards** [comment] 2023-12-08 17:53
Almost certainly same root cause as #1277

**Comment by v-cazhang** [comment] 2023-12-11 09:45
Verified on Aspire.ProjectTemplates.8.0.0-preview.2.23610.1, this issue has been fixed, so close this issue.
![image](https://github.com/dotnet/aspire/assets/82028229/ec04cedc-9a8d-4642-a72d-41c41060fd49)

**Closed** 2023-12-11 09:48 UTC
Labels: bug, area-templates
