### ISSUE TITLE
How can App Host reference microservice projects across multiple repos?

### ISSUE THREAD

**Issue by julioct** [dotnet/aspire#895] opened 2023-11-16 20:12 UTC
In a true microservices-based system, each microservice has its own code base and lives in its own repo. This is also true for the frontend and inspired by the popular [Twelve-Factor App](URL).

However, the App Host project requires project references to each of the microservices that it will host, which is not possible if those live in other repos:

```csharp
var apiservice = builder.AddProject<Projects.AspireApp_ApiService>("apiservice");
```

Sadly that kind of thing would not make sense in a real microservices-based system where you have dozens of repos, each one dedicated to one, and only one microservice.

Ideally, I would spin up a new repo that would have only my App Host and Service Defaults project, and the App Host project there would still be able to discover and host all my microservices.

How to achieve this?

P.S The fact that the [eShop](https://github.com/dotnet/eShop) project lives in a single repo is a bad practice, even when it shows great patterns for implementing microservices (and seems to make use of Aspire).

**Comment by ZeBobo5** [comment] 2023-11-16 21:29
Why don't you use GIT submodules in your App Host?

**Comment by DamianEdwards** [comment] 2023-11-16 23:48
Dupe of #829

**Closed by DamianEdwards** 2023-11-16 23:48 UTC
