### ISSUE TITLE
Can't add multiple Blazor Web Apps to Aspire

### ISSUE THREAD

**Issue by sp00ky** [dotnet/aspire#851] opened 2023-11-15 20:05 UTC
1. Create an empty solution
2. Add new Blazor Web App project to solution 
3. Add a second Blazor Web App project to the solution
4. Add .NET Aspire Application to the solution.
5. Add .NET Aspire Orchestrator Support to each Blazor app
6. Run

The following error occurs:C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(475,5): error : Conflicting assets with the same target path '_framework/blazor.boot.json'. For assets 'Identity: C:\Users\kelly.CRIB\source\repos\AspireTest\BlazorApp1\BlazorApp1.Client\bin\Debug\net8.0\wwwroot\_framework\blazor.boot.json, SourceType: Project, SourceId: BlazorApp1.Client, ContentRoot: C:\Users\kelly.CRIB\source\repos\AspireTest\BlazorApp1\BlazorApp1.Client\bin\Debug\net8.0\wwwroot\, BasePath: /, RelativePath: _framework/blazor.boot.json, AssetKind: Build, AssetMode: All, AssetRole: Primary, AssetRole: , AssetRole: , RelatedAsset: , AssetTraitName: WasmResource, AssetTraitValue: manifest, CopyToOutputDirectory: PreserveNewest, CopyToPublishDirectory: Never, OriginalItemSpec: obj\Debug\net8.0\blazor.boot.json' and 'Identity: C:\Users\kelly.CRIB\source\repos\AspireTest\BlazorApp2\BlazorApp2.Client\bin\Debug\net8.0\wwwroot\_framework\blazor.boot.json, SourceType: Project, SourceId: BlazorApp2.Client, ContentRoot: C:\Users\kelly.CRIB\source\repos\AspireTest\BlazorApp2\BlazorApp2.Client\bin\Debug\net8.0\wwwroot\, BasePath: /, RelativePath: _framework/blazor.boot.json, AssetKind: Build, AssetMode: All, AssetRole: Primary, AssetRole: , AssetRole: , RelatedAsset: , AssetTraitName: WasmResource, AssetTraitValue: manifest, CopyToOutputDirectory: PreserveNewest, CopyToPublishDirectory: Never, OriginalItemSpec: obj\Debug\net8.0\blazor.boot.json' from different projects.

A GitHub repo with a sample solution that produces this error can be fount at

https://github.com/sp00ky/AspireTest

**Comment by mitchdenny** [comment] 2023-11-15 23:47
Thanks for reporting this issue. I've managed to reproduce it with the help of your sample. As a temporary workaround to get you unblocked, you should be able to do this to your project references (note `ExcludeAssets` attribute).

```xml
  <ItemGroup>
    <ProjectReference Include="..\..\BlazorApp1\BlazorApp1\BlazorApp1.csproj" ExcludeAssets="all" />
    <ProjectReference Include="..\..\BlazorApp2\BlazorApp2\BlazorApp2.csproj" ExcludeAssets="all" />
  </ItemGroup>
```

The AppHost doesn't actually depend on the build assets on the referenced projects, it just uses some of the project metadata so this will stop the conflict occuring in this instance. We'll reach out to the Blazor team and figure out what is going on here.

**Comment by mitchdenny** [comment] 2023-11-15 23:54
@SteveSandersonMS wondering if I could get your input here. The way that Aspire works is that the AppHost references the web apps which will be part of the Aspire app model. I think what is happening here is that each blazor server app references its respective client projects, but each client project wants to lay down the blazor JS file.

TBH I am not sure this is an Aspire specific issue other than its someone uncommon for a web project to be referenced by another project.

**Comment by sp00ky** [comment] 2023-11-16 01:45
Thanks @mitchdenny I'll give it a try.

**Comment by Terrence77** [comment] 2023-11-19 15:17
>>TBH I am not sure this is an Aspire specific issue other than its someone uncommon for a web project to be referenced by another project.

Hopefully it won't be uncommon now that Aspire is here.

I want to use Aspire to manage / glue  many "sub" Blazor apps together so I don't have to build one big monolithic Blazor apps.

These are line of business app that all need to share Auth and other housekeeping functions but should be able to talk with each other.

**Comment by mitchdenny** [comment] 2023-11-27 13:22
Reopening this because I'd still appreciate @SteveSandersonMS input on how we might be able to handle this so folks don't need to manually edit the AppHost csproj file.

**Comment by SteveSandersonMS** [comment] 2023-11-27 14:28
Since this is a static web assets issue, pinging @javiercn for input on this.

**Comment by p1971** [comment] 2023-12-07 17:01
Just ran into this issue  - we often have admin / user sites or external / internal versions of sites - so it is a scenario that we will encounter - thanks for the workaround with ExcludeAssets

As a fix can the reference project output be written to a subfolder?

**Comment by mitchdenny** [comment] 2023-12-09 05:36
Waiting for @javiercn for his input.

**Comment by davidfowl** [comment] 2024-01-11 07:23
Is this also related to using project references? We should link the issue if so

**Comment by DamianEdwards** [comment] 2024-01-11 19:59
I can't repro this using latest bits. Possibly already fixed?

**Comment by javiercn** [comment] 2024-01-12 07:28
I'm able to repro this.

What's happening here is that the app host is bringing Microsoft.Net.Sdk.Web and that's bringing in static web assets. Since there are two projects that put assets in the `/`, there is a conflict as the AppHost will try to pull the assets.

I think these needs to either be a change on the SDK/build package to prevent the assets from being brought into the app host. 

Is it fair to assume/accept that the app host will "never" need to consume web content files from the referenced content?

**Comment by javiercn** [comment] 2024-01-12 07:33
I was wrong, Aspire is importing static web assets explicitly at `build\Aspire.Hosting.props` so I'm going to assume is needed for something

**Comment by javiercn** [comment] 2024-01-12 07:43
I've confirmed that the host is bringing in the static web assets SDK and that's causing the issue. I did a quick experiment to disable copying the assets from referenced projects (please don't dump the code below in an SDK, let's do it proper) but I need more context to know what the desired behavior here is. I'm not sure what the app host needs in terms of web content from any of the project that references.

```
  <Target Name="_DisableProjectAssets" BeforeTargets="ResolveReferencedProjectsStaticWebAssets">
	  <ItemGroup>
		  <StaticWebAssetProjectConfiguration Remove="@(StaticWebAssetProjectConfiguration)" />
	  </ItemGroup>
  </Target>
```

**Comment by davidfowl** [comment] 2024-01-12 14:50
> I was wrong, Aspire is importing static web assets explicitly at build\Aspire.Hosting.props so I'm going to assume is needed for something

This might be left over from when the dashboard was being hosted directly in-process. We might be able to remove it now.

**Comment by DamianEdwards** [comment] 2024-01-12 20:17
@javiercn did you try with Aspire daily builds or preview.2? I couldn't repo with daily Aspire workload. Am I holding it wrong?

**Comment by drewnoakes** [comment] 2024-01-12 22:39
I'm in the process of moving the dashboard to a separate process and am reworking some static assets as part of that. Will keep this in mind.

**Comment by javiercn** [comment] 2024-01-15 12:56
@DamianEdwards I think I tried preview.2, didn't use the daily workload.

**Comment by drewnoakes** [comment] 2024-01-16 03:07
Static asset hosting is removed from the hosting process in #1667. There are a few other things blocking that PR from merging just yet, but we're working through them.

**Closed** 2024-01-24 12:08 UTC
Labels: area-dashboard, area-app-model
