### ISSUE TITLE
[WebToolsE2E][Aspire] Running an API with aspire checked project with HTTPS, send test request shows 'Failed to fetch' on HTTP endpoint link.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#3066] opened 2024-03-21 05:27 UTC
**REGRESSION INFO**: Running with HTTPS is new feature on Aspire 8.0 preview 5

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 3.0 [34720.177.main] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire.ProjectTemplates.8.0.0-preview.5.24170.9
4. Apply NuGet Feeds

**REPRO STEPS**

1. New > Project >ASP.NET Core Web API > Enter a Project name of AspireSerBus01 > .NET 8.0 > check 'Enlist in Aspire Orcheatration' > Create
2. Right-click the AspireSerBus01 > add > .NET Aspire Component > install Aspire.Azure.Messaging.ServiceBus with matched version
3. Open appsettings.json of AspireSerBus01 project, add following codes:
```
	"ConnectionStrings": {
	  "serviceBusConnectionName":"Endpoint=sb://aspserbus.servicebus.windows.net/;SharedAccessKeyName=AspireTest;SharedAccessKey=xxx"
	},
	
	"Aspire": {
	  "Azure": {
	    "Messaging": {
	      "ServiceBus": {
	        "HealthCheckQueueName": "myQueue",
	        "Tracing": true,
	        "ClientOptions": {
	          "Identifier": "CLIENT_ID"
	        }
	      }
	    }
	  }
	},
```

4. Open Program.cs of AspireRedis01 project, add following code:
```
builder.AddAzureServiceBusClient("serviceBusConnectionName"); 
```
5. Open Program.cs of AspireSerBus01, add following codes behind the `app.MapDefaultEndpoints();`:
```
	app.MapPost("/notify", static async (ServiceBusClient client, string message) =>
	{
	    var sender = client.CreateSender("[TopicName]");
	
	    // Create a batch
	    using ServiceBusMessageBatch messageBatch =
	        await sender.CreateMessageBatchAsync();
	
	    if (messageBatch.TryAddMessage(
	            new ServiceBusMessage($"Message {message}")) is false)
	    {
	        // If it's too large for the batch.
	        throw new Exception(
	            $"The message {message} is too large to fit in the batch.");
	    }
	
	    // Use the producer client to send the batch of
	    // messages to the Service Bus topic.
	    await sender.SendMessagesAsync(messageBatch);
	
	    Console.WriteLine($"A message has been published to the topic.");
	});

```
6. F5 with https
7. On the dashboard, open 'http' endpoint link
8. On the Swagger UI page, expand the /notify endpoint and select Try it out.
9. Enter a test message in the message input box.
10. Select Execute to send a test request.

**ACTUAL**
It show 'Failed to fetch.' error
Possible Reasons:
CORS
Network Failure
URL scheme must be "http" or "https" for CORS request
![image](https://github.com/dotnet/aspire/assets/82028229/54f92c4d-e0e0-44b6-a7e9-8197b6dca1f3)

**Note**:

1. This issue doesn't repro on opening 'https' endpoint link when running with https
2. This issue doesn't repro when F5 with http 

**EXPECTED**
No error shows
![image](https://github.com/dotnet/aspire/assets/82028229/3094f2b7-f20b-4361-9e12-865f034c23ed)

**Comment by eerhardt** [comment] 2024-03-25 22:43
@DamianEdwards @davidfowl @ReubenBond @JamesNK @mitchdenny - do we have a problem with CORS here? "No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by DamianEdwards** [comment] 2024-03-26 01:25
Yep this scenario requires that the Swagger UI be viewed over HTTPS (or CORS enabled) but the Web API templates don't add the HTTPS redirect middleware and the Aspire Starter App template doesn't add Swagger UI by default. I think this is by design.

**Comment by eerhardt** [comment] 2024-03-26 20:28
@DamianEdwards - can you take a look at this and decide if there is something we need to change here? Or close it if it is behaving "by design"?

**Comment by DamianEdwards** [comment] 2024-03-28 17:53
Yeah this is by design. You can't do a fetch POST from an http:// origin to an https:// destination. It's a CORS violation and the templates aren't configured for CORS by default. The Web API template has the `UseSwaggerUI()` line **before** the `UseHttpsRedirection()` line (for some reason) so you don't get redirected to HTTPS when navigating to the Swagger UI over HTTP.

![image](https://github.com/dotnet/aspire/assets/249088/c5b2e40a-a7c3-407f-a1a9-49013ba45bea)

**Closed by DamianEdwards** 2024-03-28 17:53 UTC
Labels: area-templates, area-app-model, area-service-discovery
