### ISSUE TITLE
[WebToolsE2E][Aspire] With the latest build of Aspire 9.0 GA, some packages (Aspire.Hosting.Azure.*, Asprire.Hosting.Elasticsearch, etc.) have 9.0.0-preview.5 branding

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#6428] opened 2024-10-22 09:44 UTC
**With latest builds of Aspire 9.0 GA (10/25)**

Some packages still have 9.0.0-preview.5 branding.

![Image](https://github.com/user-attachments/assets/4252d106-c511-4444-bede-20f2cf304767)

![Image](https://github.com/user-attachments/assets/7b6d2c59-0b77-4d51-ba63-4bdcde2ab662)

![Image](https://github.com/user-attachments/assets/58a3b409-f017-422f-94b6-442c85155d1b)

![Image](https://github.com/user-attachments/assets/eefc37fc-8ecb-4d53-a92c-9dad06de579c)

![Image](https://github.com/user-attachments/assets/b752a298-b99c-40a4-96ed-79c9da822dd0)

**Comment by v-elenafeng** [comment] 2024-10-24 10:51
Captured a pic with more 9.0.0-rtm packages.
![Image](https://github.com/user-attachments/assets/94438b3a-fb23-4bed-ad7d-99998b8a84b0)

**Comment by balachir** [comment] 2024-10-25 12:43
@joperezr I've updated the title and details of this issue again based on what we're seeing with the latest builds, and added more clarity. 

Our question with this issue is whether all these packages will ship with the `9.0.0-preview.5` branding for the Aspire 9.0 GA release or does the branding need to be updated?

**Comment by eerhardt** [comment] 2024-10-25 21:03
The ones that will ship with `9.0.0-preview.5` branding for the Aspire 9.0 GA release:

* Aspire.Azure.AI.OpenAI
* Aspire.OpenAI
* Aspire.Hosting.Milvus
* Aspire.Milvus.Client
* Aspire.Hosting.Keycloak
* Aspire.Keycloak.Authentication
* Aspire.Hosting.Elasticsearch
* Aspire.Elastic.Clients.Elasticsearch

The Aspire.Hosting.Azure* packages are waiting for https://github.com/dotnet/aspire/issues/6376 before they can be "stable" branded. This will happen before the 9.0 GA release.

The Aspire.Hosting.Python package will get stable branding with https://github.com/dotnet/aspire/pull/6460.

Then finally Aspire.Npgsql.EntityFrameworkCore.PostgreSQL can't ship stable on the day that Aspire 9.0 GA releases because it has a dependency on https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/9.0.0-rc.2, which won't ship stable on that day. So we will need to ship an `rc2` version of that package on Aspire 9.0 GA release day, and shortly after when the underlying library gets released stable, we can ship a `9.0.0` stable version of it.

See also https://github.com/dotnet/aspire/issues/6492

cc @joperezr

**Comment by joperezr** [comment] 2024-10-28 16:43
Thanks for the validation, @balachir. Closing since you've confirmed that the only ones remaining in preview branding are the expected ones.

**Closed by joperezr** 2024-10-28 16:43 UTC
Labels: area-engineering-systems

**Comment by v-elenafeng** [comment] 2024-11-19 06:45
> Then finally Aspire.Npgsql.EntityFrameworkCore.PostgreSQL can't ship stable on the day that Aspire 9.0 GA releases because it has a dependency on https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/9.0.0-rc.2, which won't ship stable on that day. So we will need to ship an `rc2` version of that package on Aspire 9.0 GA release day, and shortly after when the underlying library gets released stable, we can ship a `9.0.0` stable version of it.

Hi [eerhardt](https://github.com/eerhardt), I checked that "Npgsql.EntityFrameworkCore.PostgreSQL" has released its 9.0.0 version, will we ship version 9.0.0 of "Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" soon? Thanks!
