### ISSUE TITLE
Support Azure App Configuration

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspire#2411] opened 2024-02-25 23:33 UTC
Just as future iterations of Aspire aim to support the reading and writing of secrets to an Azure Key Vault, I'd like to also request support for the reading and writing of non-secret values to Azure App Configuration. Further, where Key Vault values tend to be looked up and cached as part of DI registration, App Configuration consumers can receive updates when these non-secret values change.

My own use case calls for having a central store of key/value pairs that allow me to make a change in one place to have near-immediate effect everywhere else. I'd use this to support A/B testing and feature flag toggling - functionality that doesn't pair well using Key Vaults alone.

Thank you for the consideration!

**Comment by davidfowl** [comment] 2024-09-08 02:06
Dupe of https://github.com/dotnet/aspire/issues/787

**Closed by davidfowl** 2024-09-08 02:06 UTC
Labels: area-integrations, enhancement, azure
