### ISSUE TITLE
Add phpMyAdmin option for MySql 

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#2051] opened 2024-02-02 20:15 UTC
Similar to how RedisCommander and pgAdmin are available as options for those resources, consider adding phpMyAdmin for the MySql resource type.

Enabling:
```
var mysql = builder.AddMySqlContainer("mysql")
    .WithPhpMyAdmin();
```

**Comment by davidfowl** [comment] 2024-02-02 20:30
Dupe of https://github.com/dotnet/aspire/issues/1936

**Closed** 2024-02-02 21:41 UTC
Labels: area-app-model, untriaged
