### ISSUE TITLE
Component configuration schema isn't published

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/aspire#4844] opened 2024-07-10 13:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to create a custom .NET Aspire component following the official guidance. One of the areas describes the requirement for a `*Settings` class, and corresponding JSON configuration schema. However, the configuration generator isn't published as a package. Making it really difficult to follow this guidance.

Tagging @eerhardt and @mitchdenny

### Describe the solution you'd like

I would love for the configuration source generator bits to be published, so that new components outside of .NET Aspire - can adhere to this guidance and benefit from the same underlying mechanics by which the product itself gen config schemas.

### Additional context

Link to existing tool: https://github.com/dotnet/aspire/tree/main/src/Tools/ConfigurationSchemaGenerator

Detailed guidance:
https://github.com/dotnet/aspire/blob/main/src/Components/Aspire_Components_Progress.md#json-schemaconfiguration

Config link:
https://github.com/dotnet/aspire/blob/main/src/Components/README.md#configuration

**Comment by mitchdenny** [comment] 2024-07-10 13:29
@eerhardt would it be better for the schema generation tool to be a MSBuild task where people could add a package to their components that allows it to trigger schema generation?

**Comment by eerhardt** [comment] 2024-07-10 14:02
Duplicate of https://github.com/dotnet/aspire/issues/3309

**Closed by eerhardt** 2024-07-10 14:02 UTC
Labels: area-components
