### ISSUE TITLE
[WebToolsE2E][Aspire] Run an aspire project and then select a project resource on the dashboard and click 'Restart', restart succeeded, but some errors occurred in CMD dialog

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#5853] opened 2024-09-23 09:30 UTC
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Run preinstall
3. Install Dev17.12 Preview 3 [main-35322.26]
4. Install Aspire 9.0.0-preview.4.24472.1

**REPRO STEPS**
1. File > New project > .NET Aspire Starter App > create
2. Build and run
3. On the daskboard, click 'Restart' option behind the apiservice/webfrontend resource

**Note**: This is a new feature for Aspire 9.0 P4

**ACTUAL**
Restart succeeded, but some errors occurred in CMD dialog
![Animation](https://github.com/user-attachments/assets/1742792b-eacd-4c60-89f8-6dcf08ae744d)
![image](https://github.com/user-attachments/assets/7aa01ae6-c978-4f88-9997-f8c4bb260f92)
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"apiservice-pwvnzjwk"}, "Reconciliation": 24, "path": "C:\\Users\\v-xxx\\AppData\\Local\\Temp\\aspire.grwrxwhu.0xn\\apiservice-pwvnzjwk_out_152e1834-0940-46ad-b6ea-643e79995b10", "error": "remove C:\\Users\\v-xxx\\AppData\\Local\\Temp\\aspire.grwrxwhu.0xn\\apiservice-pwvnzjwk_out_152e1834-0940-46ad-b6ea-643e79995b10: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"apiservice-pwvnzjwk"}, "Reconciliation": 24, "path": "C:\\Users\\v-xxx\\AppData\\Local\\Temp\\aspire.grwrxwhu.0xn\\apiservice-pwvnzjwk_err_152e1834-0940-46ad-b6ea-643e79995b10", "error": "remove C:\\Users\\v-xxx\\AppData\\Local\\Temp\\aspire.grwrxwhu.0xn\\apiservice-pwvnzjwk_err_152e1834-0940-46ad-b6ea-643e79995b10: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard output file   {"Executable": {"name":"apiservice-pwvnzjwk"}, "Reconciliation": 25, "path": "C:\\Users\\v-xxx\\AppData\\Local\\Temp\\aspire.grwrxwhu.0xn\\apiservice-pwvnzjwk_out_152e1834-0940-46ad-b6ea-643e79995b10", "error": "remove C:\\Users\\v-xxx\\AppData\\Local\\Temp\\aspire.grwrxwhu.0xn\\apiservice-pwvnzjwk_out_152e1834-0940-46ad-b6ea-643e79995b10: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not remove process's standard error file    {"Executable": {"name":"apiservice-pwvnzjwk"}, "Reconciliation": 25, "path": "C:\\Users\\v-xxx\\AppData\\Local\\Temp\\aspire.grwrxwhu.0xn\\apiservice-pwvnzjwk_err_152e1834-0940-46ad-b6ea-643e79995b10", "error": "remove C:\\Users\\v-xxx\\AppData\\Local\\Temp\\aspire.grwrxwhu.0xn\\apiservice-pwvnzjwk_err_152e1834-0940-46ad-b6ea-643e79995b10: The process cannot access the file because it is being used by another process."}

**EXPECTED**
Restart succeeded and no error occur

**Comment by vmykagapuz** [comment] 2024-09-23 10:28
@davidfowl Regarding the new update just want to confirm if this is the expected result, once the project is stop and starting it again then the original logs will be cleared out.

https://github.com/user-attachments/assets/b0f9c49d-f8fb-463e-823c-d5aa4aa9f4cd

**Comment by vmykagapuz** [comment] 2024-09-23 10:40
@davidfowl When running the project the default displayed in Console log is "None", so when selecting project logs on the Resources it will navigate to the Console logs diplaying the selected project log and when clicking the Console log button again it should go back to "None" and this is expected in Aspire 8.2.0. Below is result for Aspire 9.0, this is another confirmation if it's an expected change in Aspire 9.0 preview 4. 

https://github.com/user-attachments/assets/2ef00593-b4ee-46df-b16c-56a8812eae3d

**Comment by davidfowl** [comment] 2024-09-23 13:35
This is a duplicate of https://github.com/dotnet/aspire/issues/5803 and https://github.com/dotnet/aspire/issues/5830.

> @davidfowl When running the project the default displayed in Console log is "None", so when selecting project logs on the Resources it will navigate to the Console logs diplaying the selected project log and when clicking the Console log button again it should go back to "None" and this is expected in Aspire 8.2.0. Below is result for Aspire 9.0, this is another confirmation if it's an expected change in Aspire 9.0 preview 4.

@JamesNK ?

**Comment by danegsta** [comment] 2024-09-23 21:31
@v-bennettyue I've been trying to reproduce this, but haven't had any luck yet. Is this reproducing consistently or just periodically?

**Comment by davidfowl** [comment] 2024-09-23 22:25
Which issue?

**Comment by danegsta** [comment] 2024-09-23 22:27
File in use error; Devin was able to repro though, so I'm grabbing some logs from him to try and dig in.

**Comment by davidfowl** [comment] 2024-09-24 09:28
@JamesNK ?

**Comment by JamesNK** [comment] 2024-09-25 06:23
> @davidfowl When running the project the default displayed in Console log is "None", so when selecting project logs on the Resources it will navigate to the Console logs diplaying the selected project log and when clicking the Console log button again it should go back to "None" and this is expected in Aspire 8.2.0. Below is result for Aspire 9.0, this is another confirmation if it's an expected change in Aspire 9.0 preview 4.

This is an explicit change. Console pages now remembers the last selected resource. If you navigate away and come back to the page, the last resource is automatically selected. Clicking on `Console` in the menu bar does the same thing.

Remembering the selected resource is now consistent across all the pages.

**Comment by danegsta** [comment] 2024-09-26 22:26
The file in use errors should be resolved in the latest builds.

**Comment by v-bennettyue** [comment] 2024-09-27 06:00
@danegsta After install the latest aspire 9.0.0-preview.4.24476.8, clicking 'restart', there is some new error message:
![image](https://github.com/user-attachments/assets/1496ead6-9133-48df-b579-ba4f386d5383)
 Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      could not stop the Executable     {"Executable": {"name":"webfrontend-wtyfwnrp"}, "Reconciliation": 14, "RunID": "17188", "error": "some children processes could not be stopped: TerminateProcess: Access is denied."}

**Comment by v-bennettyue** [comment] 2024-09-29 05:09
@danegsta After install the latest aspire 9.0.0-preview.4.24478.1, I can not repro this issue, but I can still repro the follow error when I use the CLI to run:
![image](https://github.com/user-attachments/assets/98eb25ea-84d1-49c2-8b62-e2622023cd2d)
Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
could not stop the Executable {"Executable": {"name":"webfrontend-wtyfwnrp"}, "Reconciliation": 14, "RunID": "17188", "error": "some children processes could not be stopped: TerminateProcess: Access is denied."}

**Comment by karolz-ms** [comment] 2024-09-30 17:54
I opened https://github.com/dotnet/aspire/issues/6030 to track the "some children processes could not be stopped" issue, which seems different from the one mentioned above.

**Comment by joperezr** [comment] 2024-09-30 19:30
Closing as @karolz-ms opened another one to track the remaining work, but the original issue is now fixed.

**Closed by joperezr** 2024-09-30 19:30 UTC
Labels: area-orchestrator
